pom.xml

this is just removing a typo from the pom I introduced on my last PR

removing wrong comment

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/uri/URISchema.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/ServerLocator.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/uri/ServerLocatorParser.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/uri/TCPTransportConfigurationSchema.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQJMSConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQQueueConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQTopicConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQXAConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQXAQueueConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQXATopicConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/DefaultConnectionProperties.java
pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ServerLocatorConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/client/ConnectionTest.java

This is a dependency for me on the examples work

Connection Factory updates

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/ActiveMQFrameDecoder2.java
pom.xml

https://issues.apache.org/jira/browse/ARTEMIS-120
This is working around the change at https://github.com/netty/netty/commit/55fbf007f04fbba7bf50028f3c8b35d6c5ea5947
Where a message is necessary at this point

ARTEMIS-120 Upgrade Netty

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/SharedNothingBackupQuorum.java

https://issues.apache.org/jira/browse/ARTEMIS-131
the connection failure listener doesnt get called in some circumstances so ive added a session failure listener as well

ARTEMIS-131 - Replicated server is not activating over certain killed scenarios

---

artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/persistence/impl/journal/JMSJournalStorageManagerImpl.java

This should fix the 3 tests failing from org.apache.activemq.artemis.tests.integration.persistence seen at https://builds.apache.org/job/ActiveMQ-Artemis-Nightly-Regression-Test/173/testReport/

ARTEMIS-142 JMS journal test fix

---

docs/hacking-guide/en/code.md
docs/hacking-guide/en/maintainers.md

Update the Hacking Guide based on a recent conversation on the dev
list.

Update hacking guide

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/CompactJournal.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-145

ARTEMIS-145 moving compact command under tools

---

pom.xml

ARTEMIS-148 Upgrade to alpha 2 JAR.

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQSessionContext.java
artemis-website/src/main/resources/hacking-guide/index.html
artemis-website/src/main/resources/user-manual/index.html

https://issues.apache.org/jira/browse/ARTEMIS-153
This is bringing some small changes recent made on the legacy implementation

ARTEMIS-153 Improving reconnection log.debug

---

tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/BrokerService.java
tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/artemiswrapper/ArtemisBrokerWrapper.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/JmsTestSupport.java

-- added addConnector() method so new connector can be created for tests
-- fix zero-byte key store files that cause test failures
-- fix a invm issue in test

Fix activemq-unit-test failure

---

artemis-distribution/pom.xml
artemis-distribution/src/main/assembly/dep.xml
artemis-protocols/artemis-mqtt-protocol/pom.xml
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnection.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTFailureListener.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTLogger.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTMessageInfo.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolHandler.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolManagerFactory.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTPublishManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTRetainMessageManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSession.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionCallback.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionState.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSubscriptionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTUtil.java
artemis-protocols/artemis-mqtt-protocol/src/main/resources/META-INF/services/org.apache.activemq.artemis.spi.core.protocol.ProtocolManagerFactory
artemis-protocols/pom.xml
pom.xml
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/FuseMQTTClientProvider.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/MQTTClientProvider.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/MQTTTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/MQTTTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/PahoMQTTTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/util/ResourceLoadingSslContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/util/Wait.java

Creates a new MQTT protocol module.  
There is currently no support (at least tested support) for using MQTT to/from other protocols.
There are a number of outstanding items of work outlined in TODO/FIXME in the PR.  These will be transferred to JIRA when/if the code is accepted.

Added Initial MQTT Protocol Support

---

artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompFrame.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/v11/StompFrameV11.java

This is the PR I mentioned in #87. I managed to run the tests with IDEA.

STOMP encoding improvements, cleanups

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/FactoryFinder.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionState.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSubscriptionManager.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConnectionContext.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSecurityContext.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalserver/DumbServer.java
artemis-rest/src/main/java/org/apache/activemq/artemis/rest/queue/ConsumersResource.java
artemis-rest/src/main/java/org/apache/activemq/artemis/rest/topic/SubscriptionsResource.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4062Test.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/transport/tcp/SocketTstFactory.java

Declare ConcurrentMaps instead of ConcurrentHashMaps

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionBridge.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/ClusteredGroupingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/cluster/BindingsClusterTest.java

I left each of these commits distinct so there would be a record of why each specific change was made since they had potentially far-reaching consequences.

ARTEMIS-179

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/topology/TopologyClusterTestBase.java

This test will fail occasionally because of stale UDP messages indicating that a node has gone up when the node has already gone up and gone down.  Here's an example: https://builds.apache.org/job/ActiveMQ-Artemis-Nightly-Regression-Test/226/testReport/junit/org.apache.activemq.artemis.tests.integration.cluster.topology/HAClientTopologyWithDiscoveryTest/testReceiveNotificationsWhenOtherNodesAreStartedAndStopped/

Fix HAClientTopologyWithDiscoveryTest

---

tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/BrokerService.java
tests/activemq5-unit-tests/src/test/resources/org/apache/activemq/transport/tcp/activemq-ssl.xml

Added missing resource file
Added accessor methods to let the test pass

Openwire test fix:

---

artemis-boot/src/main/java/org/apache/activemq/artemis/boot/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/ActionContext.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCLIPlugin.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCreatePlugin.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java
pom.xml

I did this over some debugging I was doing.

Improving bootstrap

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/artemiswrapper/ArtemisBrokerBase.java
tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/artemiswrapper/ArtemisBrokerWrapper.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/RemoveDestinationTest.java

-Using core api to inspect queue status
-Catch command visit() exceptions in order to
pass it back to client.
-Correct destination add/remove handlings

ARTEMIS-191 Refactor RemoveDestinationTest

---

artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java

https://issues.apache.org/jira/browse/ARTEMIS-219
The fix will basically use Path.resolve insead of URI.resolve

ARTEMIS-219 fixing path resolution for windows

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivationSpec.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/ActiveMQMessageHandlerTest.java

This reverts commit 1c933cfbaeae6518e2fcf55bcb58f3b714f04370.

Revert "ARTEMIS-225 validate clientID is set for durable sub"

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompUtils.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v11/StompV11Test.java

This is incomplete, haven't really tested it yet. I'm just opening this PR so we can start discussing the implementation.

[WIP] ARTEMIS-230 Copy STOMP content-header back and forth

---

docs/user-manual/en/using-server.md

Updating documentation cmds from activemq to artemis

Updating documentation cmds

---

artemis-service-extensions/src/main/java/org/apache/activemq/artemis/service/extensions/xa/recovery/ActiveMQXAResourceWrapper.java

set the client protocol manager factory on the server locator
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-236

[ARTEMIS-236] Improve Legacy support on older migrating clients

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/ActiveMQClient.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientMessageBundle.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java

Use the callFailoverTimeout for both blocking and non-blocking calls.

ARTEMIS-255 make non-blocking-failover-timeout configurable

---

artemis-boot/src/main/java/org/apache/activemq/artemis/boot/Artemis.java

https://issues.apache.org/jira/browse/ARTEMIS-263

ARTEMIS-263 - added etc folder to runtime

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/FailoverTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java

https://issues.apache.org/jira/browse/ARTEMIS-269

ARTEMIS-269 - set restartBackup to true by default

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalFilesRepository.java
artemis-journal/src/main/java/org/apache/activemq/artemis/journal/ActiveMQJournalBundle.java

https://issues.apache.org/jira/browse/ARTEMIS-321

ARTEMIS-321 - server should stop if no more journal fil can be created.

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/DuplicateIDCache.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/DuplicateIDCacheImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionBridge.java

https://issues.apache.org/jira/browse/ARTEMIS-328

ARTEMIS-328 Fixing message loss through the bridge

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/cluster/AutoCreateQueueClusterTest.java

I'm not 100% certain this is the problem described on ARTEMIS-218, but I did find a problem with auto-creating JMS queues in a cluster and I've resolved it.

ARTEMIS-218 auto-create in cluster

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile.cmd

The artemis.profile.cmd change is untested (no Windows here), just happened to stumble upon it.

cli logmanager fixes

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ManagementHelper.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/MessageImpl.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/api/jms/management/JMSQueueControl.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQMessage.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/management/impl/JMSQueueControlImpl.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/management/impl/openmbean/JMSCompositeDataConstants.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/management/impl/openmbean/JMSOpenTypeSupport.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/openmbean/CompositeDataConstants.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/openmbean/OpenTypeSupport.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AcknowledgeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/management/JMSQueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/management/JMSQueueControlUsingJMSTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/management/JMSUtil.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java

https://issues.apache.org/jira/browse/ARTEMIS-334

ARTEMIS-334 - Add Management browse functionality similar to ActiveMQ

---

docs/user-manual/en/project-info.md

This sets working URL to Apache ActiveMQ Artemis project page.

Fix URL to project page

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java

https://issues.apache.org/jira/browse/ARTEMIS-350

ARTEMIS-350 - add timeout to avoid deadlock

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/MessageImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionReceiveMessage.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionSendMessage.java

https://issues.apache.org/jira/browse/ARTEMIS-357

ARTEMIS-357 Avoiding possible races on encoding messages

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/uri/URISchema.java
artemis-commons/src/test/java/org/apache/activemq/artemis/utils/URIParserTest.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/uri/schema/serverLocator/TCPServerLocatorSchema.java
artemis-jms-client/src/test/java/org/apache/activemq/artemis/uri/ConnectionFactoryURITest.java

https://issues.apache.org/jira/browse/ARTEMIS-361

ARTEMIS-361 Fixing URI Encoding of Connection Factory properties

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/buffers/impl/ResetLimitWrappedActiveMQBuffer.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientMessageImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/MessageImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/MessageBufferTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/xa/BasicXaRecoveryTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/xa/BasicXaTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/xa/XaTimeoutTest.java

@jbertram  helped figuring out the growing buffer issue

ARTEMIS-357 fixing an issue created by my previous commit on this

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/api/jms/management/JMSServerControl.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/management/impl/JMSServerControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/management/JMSServerControlUsingJMSTest.java

https://issues.apache.org/jira/browse/ARTEMIS-378

ARTEMIS-378 - expose some Network info via the management interfaces

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/ProtonProtocolManager.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/handler/ProtonHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/handler/impl/ProtonHandlerImpl.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/context/AbstractConnectionContextTest.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/invm/InVMTestConnector.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/invm/ProtonINVMSPI.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalclient/SimpleAMQPConnector.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalserver/MinimalServer.java

added functionality to tick every n seconds where n is 1/2 the idle timeout
https://issues.apache.org/jira/browse/ARTEMIS-398

ARTEMIS-398 - AMQP protocol idle timeout issue

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile

https://issues.apache.org/jira/browse/ARTEMIS-404

ARTEMIS-404 fixing space issues on scripts

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/FailureXATest.java

ARTEMIS-421 wrong XA_RETRY XAException error code returned on crash for 1PC

ARTEMIS-421 wrong XA_RETRY XAException error code returned on crash for 1PC

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/PendingTask.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/plug/ProtonSessionIntegrationCallback.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionCallback.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQServerConsumer.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQServerSession.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/handler/ProtonHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/handler/impl/ProtonHandlerImpl.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/context/AbstractConnectionContextTest.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/invm/ProtonINVMSPI.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalclient/SimpleAMQPConnector.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalserver/MinimalServer.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/CoreSessionCallback.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/protocol/SessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/HangConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTest.java

Avoiding deadlocks between acks and other factors

ARTEMIS-437 Improving lock over certain protocols

---

artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/CertificateLoginModule.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/PropertiesLoginModule.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/ReloadableProperties.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/TextFileCertificateLoginModule.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/security/jaas/PropertiesLoginModuleTest.java
artemis-server/src/test/resources/login.config
artemis-server/src/test/resources/rolesReload.properties
artemis-server/src/test/resources/usersReload.properties

These are from ActiveMQ 5.x, specifically https://issues.apache.org/jira/browse/AMQ-6214 and https://issues.apache.org/jira/browse/AMQ-5876.

ARTEMIS-451 JAAS user/role props reload

---

artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AmqpSupport.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonContextSender.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonReceiverContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/ProtonDeliveryHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/ProtonTransactionHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerSenderContext.java

took this code from ActiveMQ which was over hawled in this area
https://issues.apache.org/jira/browse/ARTEMIS-494

ARTEMIS-494 - implement filters correctly

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/converter/ActiveMQJMSVendor.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/converter/JMSMappingInboundTransformer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/converter/JMSMappingOutboundTransformer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/converter/ProtonMessageConverter.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/converter/jms/ServerDestination.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/converter/jms/ServerJMSObjectMessage.java

some extra fixes needed
https://issues.apache.org/jira/browse/ARTEMIS-503

ARTEMIS-503 - replace proton-jms with proton-jms from ActiveMQ

---

tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/FailureXATest.java

create consumer before sending message so queue is auto created

fixing test

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/plug/ProtonSessionIntegrationCallback.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPClientConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPClientSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPSessionCallback.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonContextSender.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonReceiverContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/ProtonDeliveryHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/ProtonTransactionHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerSenderContext.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalserver/MinimalSessionSPI.java
docs/user-manual/en/protocols-interoperability.md
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonPubSubTest.java

https://issues.apache.org/jira/browse/ARTEMIS-535

ARTEMIS-535 - Improve amqp protocol to support topics

---

artemis-jdbc-store/pom.xml
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/JDBCUtils.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/AbstractJDBCDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/derby/DerbySQLProvider.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/mysql/MySQLSQLProvider.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/postgres/PostgresSQLProvider.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/postgres/PostgresSequentialSequentialFileDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCFileFactoryDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFile.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactory.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactoryDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalImpl.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/sql/GenericSQLProvider.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/sql/SQLProvider.java
artemis-jdbc-store/src/test/java/org/apache/activemq/artemis/jdbc/file/JDBCSequentialFileFactoryTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JDBCJournalStorageManager.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ThreadLeakCheckRule.java
pom.xml
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/largemessage/LargeMessageTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/RolesConfigurationStorageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/StorageManagerTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/xa/BasicXaRecoveryTest.java
tests/stress-tests/pom.xml

Refactor the JDBC storage layer.  Adds Postgres and MySQL drivers.

Jdbc refactor post

---

artemis-distribution/src/test/scripts/validate-spaces.sh
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/util/JMSClusteredTestBase.java

Only merge this after 1.3.0 is tagged

script to validate spaces on the installation

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRALogger.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivationSpec.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMAcceptor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/ColocatedHAManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ColocatedActivation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/FileLockNodeManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/InVMNodeManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RefsOperation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingBackupActivation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedStoreBackupActivation.java

JIRA: https://issues.apache.org/jira/browse/ARTEMIS-603

[ARTEMIS-603] Remove e.printStackTrace() from code

---

artemis-distribution/src/test/scripts/run-examples.sh
examples/features/standard/message-priority/src/main/java/org/apache/activemq/artemis/jms/example/MessagePriorityExample.java

the current examples can't be executed in sequence as maven will OME.
The script will help it validating it.

ARTEMIS-555 Allowing examples to be executed as part of a testsuite

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactory.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-selector/src/main/java/org/apache/activemq/artemis/selector/filter/UnaryExpression.java
artemis-selector/src/test/java/org/apache/activemq/artemis/selector/filter/UnaryExpressionTest.java
examples/features/standard/security-ldap/src/main/java/org/apache/activemq/artemis/jms/example/ldap/InMemoryDirectoryServiceFactory.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/transport/tcp/SslTransportFactoryTest.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/jms/xa/JMSXDeliveryCountTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/JournalCrashTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/PagingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/topology/NonHATopologyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/JmsProducerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v11/StompV11Test.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v12/StompV12Test.java
tests/jms-tests/src/test/java/org/apache/activemq/artemis/jms/tests/message/JMSCorrelationIDHeaderTest.java
tests/jms-tests/src/test/java/org/apache/activemq/artemis/jms/tests/message/foreign/ForeignMessageTest.java
tests/stress-tests/src/test/java/org/apache/activemq/artemis/tests/stress/journal/JournalCleanupCompactStressTest.java

Most found by skimming what FindBugs has to say. Some more coming later.

Miscellaneous little fixes

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ActiveMQException.java
artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ActiveMQExceptionType.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/plug/ProtonSessionIntegrationCallback.java
artemis-protocols/artemis-proton-plug/pom.xml
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/ProtonTransactionHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPException.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPIllegalStateException.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPInternalErrorException.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPInvalidFieldException.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPNotImplementedException.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPResourceLimitExceededException.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/exceptions/ActiveMQAMQPTimeoutException.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagingStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/AddressSettingsTest.java
docs/user-manual/en/flow-control.md
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSession.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpTransactionContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTest.java
tests/performance-tests/src/test/java/org/apache/activemq/artemis/tests/performance/storage/PersistMultiThreadTest.java

For discussion purposes.  Do not merge.
Closing the coordinator link on reject presettled tx is described in spec here: http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transactions-v1.0-os.html#doc-idp145616

Amqp hard soft limits

---

examples/features/clustered/clustered-static-discovery/src/main/java/org/apache/activemq/artemis/jms/example/StaticClusteredQueueExample.java

https://issues.apache.org/jira/browse/ARTEMIS-675

[ARTEMIS-675] incorrect commentary in examples

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/SimpleOpenWireTest.java

ARTEMIS-706 No Keep Alives from Broker (test improvement)

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/plug/ProtonSessionIntegrationCallback.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTest.java

https://issues.apache.org/jira/browse/ARTEMIS-723

ARTEMIS-723 - AMQP subscriptions aren't deleted properly

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/QuorumVoteServerConnect.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/SharedNothingBackupQuorum.java

https://issues.apache.org/jira/browse/ARTEMIS-742

ARTEMIS-742 = replication quorum broken

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/plug/ActiveMQProtonConnectionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/plug/ProtonSessionIntegrationCallback.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPConnectionCallback.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPSessionCallback.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/ProtonTransactionHandler.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerReceiverContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerSenderContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/logger/ActiveMQAMQPProtocolMessageBundle.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/context/AbstractConnectionContextTest.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/invm/ProtonINVMSPI.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalclient/AMQPClientSPI.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalserver/MinimalConnectionSPI.java
artemis-protocols/artemis-proton-plug/src/test/java/org/proton/plug/test/minimalserver/MinimalSessionSPI.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ServerSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpMessage.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpReceiver.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSender.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpTransactionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTestForHeader.java

https://issues.apache.org/jira/browse/ARTEMIS-738

ARTEMIS-738 Improving TX support on AMQP

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/QuorumVoteServerConnectTest.java

https://issues.apache.org/jira/browse/ARTEMIS-742

 ARTEMIS-742 - test fixes

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/message/JMSMappingOutboundTransformer.java

Missed by sevntu-checkstyle, but not the Eclipse compiler.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/458

Remove redundant type arguments

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpDeliveryAnnotationsTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpDescribedTypePayloadTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReceiverDrainTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpScheduledMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveTest.java

Adds several tests for AMQP expectations in various use cases.

ARTEMIS-792 Add additional tests for AMQP protocol

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-816

ARTEMIS-816 Log warning during boot if no dead letter/expire address is configured

---

artemis-features/src/main/resources/features.xml
artemis-protocols/artemis-openwire-protocol/pom.xml

Here is a patch to fix the bundle issues with artemis-openwire and add the osgi feature

ARTEMIS-860 add artemis-openwire protocol to osgi feature and fix bundle

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ActiveMQAddressDoesNotExistException.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/CreateQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/RoutingTest.java

Add some routing and createQueue tests to deal with new semantics.
Also fix a few bugs exposed by the new tests.

ARTEMIS-789 add tests; fix bugs from tests

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContext.java
pom.xml
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSender.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSession.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/util/UnmodifiableLink.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/util/UnmodifiableReceiver.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/util/UnmodifiableSender.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/util/UnmodifiableSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveTest.java

https://issues.apache.org/jira/browse/ARTEMIS-891

ARTEMIS-891 - upgrade proton to 0.16

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/message/AMQPMessageSupport.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/message/InboundTransformer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/message/JMSMappingOutboundTransformer.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveTest.java

https://issues.apache.org/jira/browse/ARTEMIS-888

ARTEMIS-888 - AMQP headers arent always set

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ProtonHandler.java

https://issues.apache.org/jira/browse/ARTEMIS-892

ARTEMIS-892 - add lock to tick method

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/message/InboundTransformer.java

https://issues.apache.org/jira/browse/ARTEMIS-888

ARTEMIS-888 - default to false if header durable not set

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/AbstractJDBCDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/JDBCUtils.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactory.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalImpl.java

Added log of SQL Warnings/Exceptions details (SQL statements related, SQL state, error codes and message).

ARTEMIS-920 Log SQL Exceptions and Warnings

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java

Add synchronized block against the properties before iterating on them.
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-926

ARTEMIS-962 Fix CME when parsing system properties

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingLiveActivation.java

In a cluster of replicated live/backup pairs if a backup crashes and
then its live crashes the cluster will retain the topology information
of the live such that when the live server restarts it will check the
cluster to see if its nodeID is present (which it will be) and then it
will activate as a backup rather than a live. To prevent this situation
an additional check is necessary to see if the server with the matching
nodeID is actually active or not which is done by attempting to make a
connection to it.

ARTEMIS-978 replicating live restarts as backup

---

artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/impl/JMSServerManagerImpl.java

(cherry picked from commit b58252401702b80a8ffa67f4252803ec09ea4fc5)

ARTEMIS-919 JMS reloader reading core queues

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap-web-settings.txt
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java

https://issues.apache.org/jira/browse/ARTEMIS-1008

ARTEMIS-1008 - Allow web server host to be set on create

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/message/CoreMessageTest.java
examples/features/standard/divert/src/main/java/org/apache/activemq/artemis/jms/example/AddForwardingTimeTransformer.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ConsumerTest.java

there was an issue with running older clients
Found by this testsuite:
https://github.com/clebertsuconic/messaging-versioning
this will fix further compatibility issues

ARTEMIS-1009 Fixing compatibility

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/management/TopicControlClusterTest.java

Test didn't account for "remote" queue bindings from other cluster
member which caused a race condition.

NO-JIRA fix race in TopicControlClusterTest

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/amq/ProducerAutoCreateQueueTest.java

https://issues.apache.org/jira/browse/ARTEMIS-1023

ARTEMIS-1023 - fixx Openwire auto creation of queues

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPConnectionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPSessionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/transaction/ProtonTransactionHandler.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/util/DeliveryUtil.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpTransactionTest.java

These two commits are part of some work I have been doing
with performance tests
and some work I was doing with @tabish121 to ensure TX are not stalling.
These both commits are related and I don't know if 1046 would work without 1045, 
so, I'm sending both commits on a single PR.

Two Performance and TX changes

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpTransactionTest.java

When a message is sent to the broker with a TransactionState indicating
that he message should be included in a transaction the disposition from
the broker indicating acceptance of the message should be done using a
TransactionState value that contained the TX ID and the Accepted
disposition.

ARTEMIS-59 Accept transacted message using AMQP TransactionState

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java

JIRA: https://issues.apache.org/jira/browse/ARTEMIS-1057

[ARTEMIS-1057] Log AMQ214023 at DEBUG level

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java

https://issues.apache.org/jira/browse/ARTEMIS-1075

ARTEMIS-1075 - Add Routing Type to QueueControl management API

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionContinuationMessage.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionReceiveContinuationMessage.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionSendContinuationMessage.java

(cherry picked from commit 1686b3545d14cdf591e00e6d04228b48b2b74a9f)

ARTEMIS-1036 Streaming huge messages between cluster nodes causes java.lang.OutOfMemoryError: Direct buffer memory

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/Connection.java

(cherry picked from commit 27cfb2d90208403cec6727dd595f9dd1380ef441)

ARTEMIS-1025 Improve flow control on NettyConnection

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/ProtonTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlTest.java

https://issues.apache.org/jira/browse/ARTEMIS-1107

ARTEMIS-1107 - fix and Test AddressControl.sendMessage()

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/RunnableEx.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalFilesRepository.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPConnectionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/client/AMQPClientConnectionFactory.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/EventHandler.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ProtonHandler.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/transaction/ProtonTransactionHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/smoke-tests/pom.xml
tests/smoke-tests/src/main/resources/servers/expire/broker.xml
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/expire/TestSimpleExpire.java

These are all related to some work I'm doing...

Many fixes around some tests I'm doing

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/AbstractJDBCDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/storage/DatabaseStorageConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreFactoryDatabase.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JDBCJournalStorageManager.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
docs/user-manual/en/persistence.md

(cherry picked from commit 256773206b75e6040d15cf06722843a7a9107ca8)

ARTEMIS-1124 JDBC Network Timeout configuration

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/ActiveMQThreadFactory.java

https://issues.apache.org/jira/browse/ARTEMIS-874

ARTEMIS-874: ThreadGroup memory leak

---

pom.xml

Updates Qpid JMS to 0.23.0
Updates Proton-j to 0.19.0

ARTEMIS-1168 Update Qpid JMS and Proton-J to latest versions

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveInterceptorTest.java

Add Outgoing call
https://issues.apache.org/jira/browse/ARTEMIS-1169

ARTEMIS-1169 - Implement Interceptors for the AMQP protocol

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java

this will fix a few multiple protocol tests on ConsumerTests.
And a few other AMQP tests dealing with conversions.
You would get a classCastException without this commit.

ARTEMIS-1169 Fixing protocol conversion

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java

This closes #1301
This commit replaces #1301

ARTEMIS-1195 Filters should be independent on create

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/ClientDefinedMultiConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSSharedConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSSharedDurableConsumerTest.java

Add test case, to prove the issue, and then obviously ensure it works, post fix.
Apply changes in logic of createQueueName to handle global better and fix the behaviour.

ARTEMIS-1205: AMQP Shared Durable Subscriber incorrect behaviour.

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/JournalFileSizeTest.java

https://issues.apache.org/jira/browse/ARTEMIS-1224

ARTEMIS-1224 - change the journal file size to nearest multiple

---

artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/impl/JMSServerManagerImpl.java

JIRA: https://issues.apache.org/jira/browse/ARTEMIS-1232

[1.x] [ARTEMIS-1232] Configure deserialization lists on regular JMS CF

---

docs/user-manual/en/perf-tuning.md
docs/user-manual/en/rest.md

fix some typos in documentation

NO-JIRA fix typos in documentation

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/RemotingConnectionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/ReplicationResponseMessageV2.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationEndpoint.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ReplicationError.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingBackupActivation.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/LargeMessageFailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedMultipleServerFailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/util/TransportConfigurationUtils.java

(cherry picked from commit b4e5c483cabf3908beffce733522764912500f6a)

(1.x) ARTEMIS-1269 replication won't finish synchronization

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/MultipleProducersTest.java

(cherry picked from commit ab92306d81df10e6cfdc771973b39980721a6f98)

ARTEMIS-1274 MultipleProducersTest.wrongQueue fails

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpPurgeOnNoConsumersTest.java

make sure rollback doesn't add messages back
https://issues.apache.org/jira/browse/ARTEMIS-1277

ARTEMIS-1277 - purgeOnNoConsumer is not working properly

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/AbstractJournalUpdateTask.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalCompactor.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/CrashOnCompactTest.java

The system would become irresponsive if crashed right at the
control file writing.

ARTEMIS-1288 crash during compact control files issues

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/QuorumVoteServerConnect.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/ServerConnectVote.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/SharedNothingBackupQuorum.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConnectVoteHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingBackupActivation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingLiveActivation.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/QuorumFailOverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/QuorumVoteServerConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java

Add a check on top of just being able to connect to a live broker
https://issues.apache.org/jira/browse/ARTEMIS-1296

ARTEMIS-1296 - fix quorum vote

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/OrderedExecutorFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

(cherry picked from commit 8a90d1bc3de5ad0d941195e7df8dc72e2f03c256)

ARTEMIS-1328 Improving direct delivery check

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSLVQTest.java

Add support for LVQ, using the same property key as core "_AMQ_LVQ_NAME"
Add test case for AMQP LVQ.

ARTEMIS-1348 Support LVQ for AMQP

---

docs/user-manual/en/client-reconnection.md

@jbertram as your rightly pointed out I caused this confusion, undoing previous pr/correcting back the document

ARTEMIS-1355 - correct doc Undo PR 1438

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/Packet.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/PacketImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/ReplicationSyncFileMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingLiveActivation.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/MQTTInterceptorPropertiesTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/MQTTTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/replication/ReplicationTest.java

This is based on the work @jbertram made at the github pr #1466 and the discussions we had there

ARTEMIS-1353 Initial replication of large messages out of executor

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/CriticalAnalyzerPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/en/configuration-index.md
docs/user-manual/en/critical-analysis.md

The Critical Analyzer is extended with a LOG action policy on failures.

ARTEMIS-1367 Add LOG to the Critical Analyzer policies

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java

There is a leak on replication tokens in the moment when a backup is
shutdowned or killed and the ReplicationManager is stopped. If there
are some tasks (holding replication tokens) in the executor, these
tokens are simply ignored and replicationDone method isn't called on
them. Because of this, some tasks in OperationContextImpl cannot be
finished.

ARTEMIS-1368 Artemis gets to state when it doesn't respond to producer

---

docs/hacking-guide/en/book.json
docs/migration-guide/en/book.json
docs/user-manual/en/address-model.md
docs/user-manual/en/architecture.md
docs/user-manual/en/book.json
docs/user-manual/en/clusters.md
docs/user-manual/en/configuration-index.md
docs/user-manual/en/core-bridges.md
docs/user-manual/en/diverts.md
docs/user-manual/en/examples.md
docs/user-manual/en/flow-control.md
docs/user-manual/en/last-value-queues.md
docs/user-manual/en/libaio.md
docs/user-manual/en/message-expiry.md
docs/user-manual/en/messaging-concepts.md
docs/user-manual/en/persistence.md
docs/user-manual/en/preface.md
docs/user-manual/en/project-info.md
docs/user-manual/en/protocols-interoperability.md
docs/user-manual/en/security.md
docs/user-manual/en/slow-consumers.md
docs/user-manual/en/undelivered-messages.md

Remove some out-dated material, fix a few links, & clean up a few
random bits.

NO-JIRA clean up docs

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java

Avoid null checking each disposition before then checking the type, also
account for not knowing the type.  Rearrange the handling code to
prioritize the most common case which is "Accepted"

ARTEMIS-1377 Refactor the disposition handling code

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java

Clean up toString code and properly log error message.

ARTEMIS-1395 Clean up toString code

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSMessageConsumerTest.java

Added test case for cross protocol on JMSDeliveryMode proving issue, and asserting fix
Added fix to AmqpCoreConverter to ensure durability (JMSDeliveryMode) is retained.

ARTEMIS-1413: FIX JMSDeliveryMode/Priority on AMQP to CORE conversion

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ActiveMQProtonRemotingConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/client/AMQPClientConnectionFactory.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/client/ProtonClientConnectionManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/EventHandler.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ProtonHandler.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/sasl/ClientSASL.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/sasl/ClientSASLFactory.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpOutboundConnectionTest.java

Update ProtonHandler to allow for both client and server side SASL
and other related changes to allow for setting of client side mechanism

ARTEMIS-1454: Support SASL in outgoing AMQP

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/BasicOpenWireTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/FQQNOpenWireTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/OpenWireDivertExclusiveTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/OpenWireDivertNonExclusiveTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/OpenWireDivertTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/OpenWireTestBase.java

Adding 2 tests that showing how openwire clients
interact with core Divert.

NO-JIRA Adding Openwire basic divert tests

---

scripts/rebuild-snapshot.sh

I use this script all the time when I'm debugging stuff.
I"m not sure if other people would think it's useful as well. it would certainly help me having it under scripts.

NO-JIRA Script I use to rebuild snapshots under the distribution

---

pom.xml

Update to latest Qpid-JMS and match its Proton-J dependency

ARTEMIS-1504 Update to QpidJMS 0.27.0 and Proton-j 0.23.0

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/jms/ServerJMSBytesMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/jms/ServerJMSMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/LargeServerMessageImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpLargeMessageTest.java

I'm doing an overal improvement on large message support for AMQP
However this commit is just about a Bug on the converter.
It will be moot after all the changes I'm making, but I would rather keep this separate
as a way to cherry-pick on previous versions eventually.

ARTEMIS-1514 Large message fix

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java

This will cache the last query, optimizing most of the cases
This won't optimize the case where you are sending producers with different address,
but this is not the one I'm after now.

ARTEMIS-1416 Implementing cache on queue and address querying

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/critical/CriticalAnalyzer.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/critical/CriticalAnalyzerImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/AbstractSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/SequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/buffer/TimedBuffer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/critical/analyzer/CriticalAnalyzerFaultInjectionTestBase.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/critical/analyzer/FileSystemSyncBlockedTest.java

Also, making TimedBuffer.stop() synchronized to avoid issues during device outages

ARTEMIS-1531 Adding timedbuffer operations on critical analyzer

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/security/SecurityTest.java

to make sure queue name is in the error message

NO-JIRA Adding extra assertions to test

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ConfigurationUtils.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ha/ReplicaPolicyConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ha/ReplicatedPolicyConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/ReplicaPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/ReplicatedPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/QuorumManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/SharedNothingBackupQuorum.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingBackupActivation.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
docs/user-manual/en/network-isolation.md

ARTEMIS-1565 - replica should retry quorum vote
https://issues.apache.org/jira/browse/ARTEMIS-1565

https://issues.apache.org/jira/browse/ARTEMIS-1565

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivationSpec.java

ARTEMIS-1658 Add prefix option to ActivationSpec

---

artemis-core-client-osgi/pom.xml
artemis-features/src/main/resources/features.xml
artemis-jms-client-osgi/pom.xml
artemis-server/pom.xml
pom.xml
tests/integration-tests/pom.xml
tests/karaf-client-integration-tests/pom.xml
tests/karaf-client-integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/karaf/client/ArtemisAMQPClientFeatureIT.java
tests/karaf-client-integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/karaf/client/ArtemisCoreClientFeatureIT.java
tests/karaf-client-integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/karaf/client/ArtemisJMSClientFeatureIT.java
tests/karaf-client-integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/karaf/client/ArtemisTransactionalJMSClientFeatureIT.java
tests/karaf-client-integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/karaf/client/PaxExamOptions.java
tests/pom.xml

[ARTEMIS-1630](https://issues.apache.org/jira/browse/ARTEMIS-1630)
This adds support for CORE, JMS and AMQP artemis client karaf features with some IT tests. Let me know if you have any questions.
Thanks!

[ARTEMIS-1630] Create Artemis Client features

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/CreateQueueMessage_V2.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/CreateSharedQueueMessage_V2.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionBindingQueryResponseMessage_V4.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/SessionQueueQueryResponseMessage_V3.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQSession.java

ARTEMIS-853 - Support for exclusive consumers - Coverity fix's

---

docs/user-manual/en/SUMMARY.md
docs/user-manual/en/address-model.md
docs/user-manual/en/exclusive-queues.md
docs/user-manual/en/last-value-queues.md

Exclusive Queue documents added to detail behaviour and how to configure.
Also update docuents for last-value queue to cover addtional ways to configure

ARTEMIS-853 - Add documents

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java

For address and queue create check for the already exists exceptions and
ignore as another client might have just created the same

ARTEMIS-1707 Check for already exists exceptions and ignore

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/TransportConstants.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java
docs/user-manual/en/configuring-transports.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/security/SecurityTest.java

Support setting wantClientAuth on a netty acceptor

ARTEMIS-1706 - Add support for wantClientAuth

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/OpenwirePluginTest.java

fix NPE inside getClientId() in OpenWireConnection

ARTEMIS-1713 - Fix NPE inside OpenWireConnection

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/JMXAccessControlList.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/management/JMXAccessControlListTest.java

https://issues.apache.org/jira/browse/ARTEMIS-1736

ARTEMIS-1736 - make sure access methods are ordered when used

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java

Jira: https://issues.apache.org/jira/browse/ARTEMIS-1770
Master PR: https://github.com/apache/activemq-artemis/pull/1990

[ARTEMIS-1770] Log warning when connection is closed

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/bridge/BridgeTest.java

This is still part of ARTEMIS-1776 fix, which still part of the same release as we are on now.
Hence I'm not opening a new JIRA for this one.

ARTEMIS-1776 Blocked Bridge is not resuming after reconnect

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/FailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/LiveToLiveFailoverTest.java

@michaelandrepearce @mtaylor this one will interest you I think

ARTEMIS-1814 Try original connection when every other node failed

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/ActiveMQChannelHandler.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptorFactory.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/jdbc/JdbcLeaseLockTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/impl/netty/NettyAcceptorTest.java

This is fixing existing tests, so no more tests are needed.

ARTEMIS-1837 Replication Initial catchup deadlocks if clients disconnect

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java

@clebertsuconic  , @jbertram 
New hopefully to fix #2060 . Plz have a deep look before merge.

ARTEMIS-1768: Update to fix handling of internalSession for OpenWireConnection

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/amqp-acceptor.txt
artemis-features/src/main/resources/artemis.xml
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AmqpSupport.java
artemis-server/src/test/resources/ConfigurationTest-full-config-wrong-address.xml
examples/features/standard/broker-plugin/src/main/resources/activemq/server0/broker.xml
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSender.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpValidator.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFlowControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSenderTest.java
tests/smoke-tests/src/main/resources/servers/expire/broker.xml
tests/smoke-tests/src/main/resources/servers/mqtt/broker.xml

More details at https://issues.apache.org/jira/browse/ARTEMIS-1862

ARTEMIS-1862: fix 'amqpLowCredits' XML config, update code defaults

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/SecureConfigurationTest.java
tests/integration-tests/src/test/resources/multicast_topic.xml

Ensure CREATE_ADDRESS is security setting is honored and behavior is consistent across protocols.

ARTEMIS-1872 Fixing address security checks

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

No tests required as there is no semantic changes here.
Current tests should validate this change.

ARTEMIS-1915 Expiry Scanner is holding a lock on the queue

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java

JIRA :- https://issues.apache.org/jira/browse/ARTEMIS-1936

[ARTEMIS-1936]getQueueNames(String routingType) method should be mark as Operation instead of Attribute

---

pom.xml

Update to latest release of Qpid JMS

ARTEMIS-1938 Update to Qpid JMS 0.33.0

---

pom.xml
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpReceiver.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpLargeMessageTest.java

As before with #2221, but now cherry picked to 2.6.x with needed fixups.

ARTEMIS-1978: update to proton-j 0.27.3 to resolve sequencing issues

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/message/AMQPMessageTest.java

Ensure that the Body of the message is never decoded in the partial
decode phase of the message processing and also gaurd against the
decode of ApplicationProperties which should be done lazily.  Add
lazy decode of DeliveryAnnotations as they are not used at present.

ARTEMIS-2083 Decode only the relavent portions of the message

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ConfigurationUtils.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ha/ReplicaPolicyConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ha/ReplicatedPolicyConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/ReplicaPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/ReplicatedPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AnyLiveNodeLocatorForReplication.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/NamedLiveNodeLocatorForReplication.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingBackupActivation.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/HAPolicyConfigurationTest.java
artemis-server/src/test/resources/replica-hapolicy-config.xml
artemis-server/src/test/resources/replicated-hapolicy-config.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java

https://issues.apache.org/jira/browse/ARTEMIS-2075

ARTEMIS-2075 - allow Extra backups to try to replicate more than once

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/RedeployTest.java
tests/integration-tests/src/test/resources/reload-backup-changed.xml
tests/integration-tests/src/test/resources/reload-backup-original.xml
tests/integration-tests/src/test/resources/reload-live-changed.xml
tests/integration-tests/src/test/resources/reload-live-original.xml

(cherry picked from commit cce0e19)

ARTEMIS-2094 - Fix Configuration change loss when network Issue

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/client/MessageTest.java

Upstream Issue: https://issues.apache.org/jira/browse/ARTEMIS-1874
Issue: https://issues.jboss.org/browse/JBEAP-15516
No upstream PR required, changes already in master
This is just a backport of the fix into the 1.x branch. I've setup the PR just to make the backport easy for devs, if you prefer to cherry-pick this fix later on yourself, feel free to simply close this PR! (or ask me to do it).

ARTEMIS-1874 fix NPE setting object property

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/html/deleteQueue.html

Changing the view layout from horizontal to vertical avoid the resizing
issue

ARTEMIS-2114 hawtio dest delete/purge buttons overlap if pane resized

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ExtraBackupReplicatedFailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedMultipleServerFailoverExtraBackupsTest.java

Some tests were added to a class that was extended, Ive moved these into their own class

NO-JIRA - fixing up some broken tests

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagingStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
tests/performance-tests/src/test/java/org/apache/activemq/artemis/tests/performance/storage/PersistMultiThreadTest.java

Previous change on Flow control in OpenWire broke Blocked cases
This is a better fix.

ARTEMIS-2159 Fixing OpenWire Blocker Producer

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RefsOperation.java

Fixed regression caused by previous commit
b36dc37c152cabe3a0d9af178db043f842bfcdc0

ARTEMIS-2197 Page deleted before transaction finishes

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java

Picked up by code analysis checks

NO-JIRA Check data != null during encode

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/ActiveMQThreadPoolExecutor.java

Revert ARTEMIS-1451
Remove synchronization by simplifying original code and using atomics (addressing concerns in ARTEMIS-1451)

ARTEMIS-2236 Address Latency Impact caused by ARTEMIS-1451

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/QueueQueryTest.java

My previous commit to fix this was amended which nullified the fix.

NO-JIRA fix race condition in QueueQueryTest

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/PriorityCollection.java

https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#im-computation-of-average-could-overflow-im-average-computation-could-overflow
CC @michaelandrepearce

NO-JIRA Fix a "Computation of average could overflow" SpotBugs warning

---

docs/user-manual/en/config-reload.md

Add docs to clarify the need to touch broker.xml for modularised config to reload

NO-JIRA Document reloading when using modularised broker.xml

---

pom.xml

Also upgrade netty-tcnative along with it.

ARTEMIS-2271 - Upgrade to Netty Libs to Latest 4.1.34.FINAL

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

Address code review comment not address when PR was merged.

ARTEMIS-1604 Artemis deadlock using MQTT Protocol

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java

ARTEMIS-2292 - Fix queue level auto-delete for topic subscription queue

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/Env.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/CheckDependencies.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java

just checking for NoClassDefFound and return false

ARTEMIS-2301 Minor change on Epoll and kQueue.isAvailable

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/transaction/ProtonTransactionImpl.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/transaction/ProtonTransactionRefsOperation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RefsOperation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/Transaction.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/impl/BindingsTransactionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/InterruptedLargeMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jmx/JmxConnectionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/BindingsImplTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/FakeQueue.java

Also including a new metric for ack attempts that will keep the former semantic.

ARTEMIS-2305 ACK counters to only increment after commit

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/crossprotocol/RequestReplyNonJMSTest.java

Add a broader range of tests for AMQP message reply to handling
across protocols to help spot potential future regressions.

ARTEMIS-2311 Add additional tests for reply to cross protocol

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v12/StompV12Test.java

ARTEMIS-2333 NettyConnection is not writeable if disconnected

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQSession.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/compatible1X/ActiveMQCompatibleMessage.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/compatible1X/ActiveMQTextCompatibleMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/ServerSessionPacketHandler.java
tests/compatibility-tests/src/main/resources/jmsReplyToQueue/artemisServer.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToQueue/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToQueue/sendMessagesAddress.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTempQueue/artemisServer.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTempQueue/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTempQueue/sendMessagesAddress.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTempTopic/artemisServer.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTempTopic/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTempTopic/sendMessagesAddress.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTopic/artemisServer.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTopic/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jmsReplyToTopic/sendMessagesAddress.groovy
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToQueueTest.java
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToTempQueueTest.java
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToTempTopicTest.java
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToTopicTest.java

There are a few issues with prefixing and compatibility.
This is basically an issue when integrated with Wildfly or any other case
where prefix is activated
and playing with older versions.

ARTEMIS-2339 Compatibility around prefixing

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationSecurityPluginTest.java
artemis-server/src/test/resources/ConfigurationTest-security-plugin-config.xml

https://issues.apache.org/jira/browse/ARTEMIS-2377

ARTEMIS-2377 - add password encryption to security plugins

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTPublishManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/PahoMQTTQOS2SecurityTest.java

https://issues.apache.org/jira/browse/ARTEMIS-2386

ARTEMIS-2386 - use internal session for management queues for QOS2

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreFactoryDatabase.java

https://issues.apache.org/jira/browse/ARTEMIS-2358

ARTEMIS-2358 - fixing issue with last commit

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContextTest.java

Fix test and warning condition to avoid false issues.

ARTEMIS-2385 Log header for rejecting message with too large header

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/QueueMetricNames.java
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MetricsPluginTest.java

Test is also adjusted to test for the changes made.

ARTEMIS-2429 Fix order of arguments to registerQueueGauge and two related typos

---

docs/user-manual/en/configuration-index.md
docs/user-manual/en/security.md

Add documentation for role-mapping implemented in ARTEMIS-1116

ARTEMIS-2521 add documentation for role-mapping

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/browse.js

This only changes the formatting, no functional changes. This will make it easier to review future functional changes of the file.

NO-JIRA Fix indention in browse.js

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/openmbean/OpenTypeSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/LargeMessageCompressTest.java

https://issues.apache.org/jira/browse/ARTEMIS-2554

ARTEMIS-2554 - Queue control browse broken with large messages

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingTest.java

Add a paged message to the tail, when the QueueIterateAction doesn't handle it, to avoid removing unhandled paged message. Move the refRemoved calls from the QueueIterateActions to the iterQueue to fix the queue stats.

ARTEMIS-2572 The retryMessages remove all paged messages

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile.cmd

Remove the nested quotes around the hawtio.offline value of the JAVA_ARGS line
in the generated artemis.profile.

ARTEMIS-2585 Remove nested quotes from artemis.profile

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPSessionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ConsumerTest.java

Remove server senders on remote link close.

ARTEMIS-2597 Memory Leak when closing AMQP Consumers in the context

---

pom.xml

This affects only examples and tests.

ARTEMIS-2600 Update mqtt-client version to 1.16

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/consumer/CreateSubscriptionTest.java

Some of them may throw queue already existed exception

ARTEMIS-2672 multi-thread isue with Shared Subscriptions

---

artemis-cli/src/main/java/org/apache/activemq/artemis/util/ServerUtil.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/common/SmokeTestBase.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/mqtt/MQTTLeakTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/replicationflow/ReplicationFlowControlTest.java

The examples were broken after the change on ServerUtil.

ARTEMIS-2685 Fixing Examples

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/karaf/ArtemisFeatureTest.java

Use https Maven Central URLs to fix ArtemisFeatureTest.

ARTEMIS-2744 Fix karaf mvn repositories for ArtemisFeatureTest

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/BaseBroadcastGroupControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/JGroupsChannelBroadcastGroupControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/JGroupsFileBroadcastGroupControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/BaseBroadcastGroupControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/JGroupsChannelBroadcastGroupControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/JGroupsFileBroadcastGroupControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/JGroupsChannelBroadcastGroupControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/JGroupsFileBroadcastGroupControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ManagementControlHelper.java

https://issues.apache.org/jira/browse/ARTEMIS-2749

Broadcast Group Control improvements

---

.gitignore
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/RedeployTempTest.java
tests/integration-tests/src/test/resources/RedeployTempTest-reload-temp-updated.xml
tests/integration-tests/src/test/resources/RedeployTempTest-reload-temp.xml

@michaelandrepearce  This is a test you sent me.. and I'm committing here.
There are no changes on the broker as part of this commit, I'm just adding the test you sent me to the codebase and set you as the author.
also I'm sneaking in a .gitignore change I needed.

ARTEMIS-2534 Additional testing

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/browse.js

https://issues.apache.org/jira/browse/ARTEMIS-2786

ARTEMIS-2786 - fix month in browse console

---

pom.xml

This is upgrading artemis native which has a fix to avoid a kernel bug in the fs/aio.c module

ARTEMIS-2800 / ARTEMIS-2818 Upgrade Artemis Native

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManagerTest.java

https://issues.apache.org/jira/browse/ARTEMIS-2853

ARTEMIS-2853 page-max-concurrent-io cannot be disabled

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/CompositeAddress.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQSession.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jndi/ReadOnlyContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/security/impl/SecurityStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/HierarchicalRepository.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/HierarchicalObjectRepository.java
docs/user-manual/en/security.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFullyQualifiedNameTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/SimpleJNDIClientTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/FQQNOpenWireTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/security/SecurityTest.java

Here's a handful of commits related to FQQN.

FQQN stuff

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/Wait.java
artemis-rest/pom.xml
artemis-rest/src/test/java/org/apache/activemq/artemis/rest/test/SelectorTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RefsOperation.java

this does not represent an issue as there are no semantic changes here.
I am doing this for correctness

NO-JIRA using correct queue on RefOperation::rollback and remove TODO

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivation.java

* When creating a destination it should rely on the RA configuration if
none is provided instead of relying directly on the default
configuration.
Issue: https://issues.apache.org/jira/browse/ARTEMIS-2954

[ARTEMIS-2954]: RA doesn't use the RA specified prefix when setting up a destination.

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivation.java

Avoiding double prefix with ARTEMIS-2954 fix.
Issue: ARTEMIS-2954

[ARTEMIS-2954] Fixing double preifx issue.

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/integration/FileBroker.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/ManagementContext.java

https://issues.apache.org/jira/browse/ARTEMIS-2957

ARTEMIS-2957 ManagementContext is started twice

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/LinkedListImpl.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
examples/features/broker-connection/amqp-sending-overssl/pom.xml
examples/features/broker-connection/amqp-sending-overssl/src/main/java/org/apache/activemq/artemis/jms/example/BrokerConnectionSenderSSL.java
examples/features/broker-connection/amqp-sending-overssl/src/main/resources/activemq/server0/broker.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpAnyCastDistinctQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFullyQualifiedNameTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPReplicaTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/QpidDispatchPeerTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/util/LinkedListTest.java

this PR contains changes related to broker connection

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MQTTConnnectionCleanupTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/imported/MQTTSecurityCRLTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/replicationflow/SoakPagingTest.java

I am still working on an intermittent test failure, more eyes welcome
MQTTQueueCleanTest.testQueueCleanWhenConnectionSynExeConnectAndDisconnect

ARTEMIS-2985 - don't block netty threads for mqtt protocol actions

---

pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpLargeMessageTest.java

I am also bringing a test I used to report https://issues.apache.org/jira/browse/PROTON-2297
Even though the issue here is on qpid-jms. There's no such thing as enough tests so I am keeping the test.

ARTEMIS-3006 Upgrading to Qpid Proton 0.33.8

---

artemis-jakarta-client/pom.xml
artemis-jakarta-client/src/main/resources/jms-version.properties
artemis-jakarta-ra/pom.xml
artemis-jakarta-ra/src/main/resources/jms-version.properties
artemis-jakarta-server/pom.xml
artemis-jakarta-service-extensions/pom.xml
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQConnectionMetaData.java
artemis-jms-client/src/main/resources/jms-version.properties
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRAConnectionMetaData.java
artemis-ra/src/main/resources/jms-version.properties
pom.xml
tests/compatibility-tests/pom.xml
tests/compatibility-tests/src/main/java/org/apache/activemq/artemis/tests/compatibility/GroovyRun.java
tests/compatibility-tests/src/main/resources/jakartaReplyToQueue/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToQueue/sendMessagesAddress.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToTempQueue/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToTempQueue/sendMessagesAddress.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToTempTopic/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToTempTopic/sendMessagesAddress.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToTopic/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/jakartaReplyToTopic/sendMessagesAddress.groovy
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToQueueTest.java
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToTempQueueTest.java
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToTempTopicTest.java
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/JmsReplyToTopicTest.java

* using batavia and eclipse transformer to transform JMS code to JakartaEE.
* adding a test with JakartaEE
Jira: https://issues.apache.org/jira/browse/ARTEMIS-3080

[ARTEMIS-3080]: Provide JakartaEE 9 artefacts.

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/smoke-tests/pom.xml
tests/smoke-tests/src/main/resources/servers/brokerConnectBridgeSecurityA/artemis-roles.properties
tests/smoke-tests/src/main/resources/servers/brokerConnectBridgeSecurityA/artemis-users.properties
tests/smoke-tests/src/main/resources/servers/brokerConnectBridgeSecurityA/broker.xml
tests/smoke-tests/src/main/resources/servers/brokerConnectBridgeSecurityB/artemis-roles.properties
tests/smoke-tests/src/main/resources/servers/brokerConnectBridgeSecurityB/artemis-users.properties
tests/smoke-tests/src/main/resources/servers/brokerConnectBridgeSecurityB/broker.xml
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/brokerConnection/BrokerConnectionBridgeSecurityTest.java

The local connections and sessions created internally were supposed to bypass security
just like bridges and other internal components

ARTEMIS-3150 Broker Connections with restricted security

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3196

ARTEMIS-3196 - expose journal pool files in JMX

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java

This has been introduced by https://github.com/apache/activemq-artemis/pull/3392

ARTEMIS-3045 NettyConnection should null-check Netty buffer

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/BindingsImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/CopyOnWriteBindings.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/RoutingContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RoutingContextImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-3219

ARTEMIS-3219 Improve FQQN message routing

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/diagram.js

while reading through the code for the broker diagram, I noticed 2 small inconsistencies. this PR fixes them.
note that this is based on a code review only. the fix does not seem to solve any real-world problems.

NO-JIRA fixed spelling error in code of broker diagram

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalFileImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalRecord.java
artemis-journal/src/test/java/org/apache/activemq/artemis/core/journal/impl/VerifyUpdateFactorSystemProperty.java
tests/config/logging.properties
tests/smoke-tests/pom.xml
tests/smoke-tests/src/main/resources/servers/infinite-redelivery/broker.xml
tests/smoke-tests/src/main/resources/servers/infinite-redelivery/logging.properties
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/infinite/InfiniteRedeliverySmokeTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/ReclaimerTest.java

After testing a production outage situation I still encountered issues on deciding the journal should be compacted.
This is addressing these issues.

ARTEMIS-3261 Expanding verification to journal compacting counters

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionBridge.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/cluster/MessageRedistributionTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3295

ARTEMIS-3295 - do not cluster advisories

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/queues.js

https://issues.apache.org/jira/browse/ARTEMIS-3332

ARTEMIS-3332 - fix search on consumer count in console

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQConnectionFactory.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRALogger.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRAMCFProperties.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRAManagedConnectionFactory.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRASessionFactoryImpl.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ConnectionFactoryProperties.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivationSpec.java
examples/features/sub-modules/artemis-ra-rar/pom.xml
examples/features/sub-modules/artemis-ra-rar/src/main/resources/ra.xml
pom.xml

https://issues.apache.org/jira/browse/ARTEMIS-3331

ARTEMIS-3331 - RA improvements to work well with more Servers

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFileFactory.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/AIOSequentialFileFactoryTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3354

ARTEMIS-3354 journal-max-io cannot be set to 1 with ASYNCIO journal

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-3398

ARTEMIS-3398 - fix filtering in console with filter

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/ArtemisMBeanServerGuard.java

https://issues.apache.org/jira/browse/ARTEMIS-3403

ARTEMIS-3403 - wrong debug level in ArtemisMBeanServerGuard

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PagingStoreImplTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3405

ARTEMIS-3405 Log the end of paging mode for a destination

---

tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/logging/AssertionLoggerTest.java

This would help capture issues with logging configuration on PR checks

NO-JIRA Moving AssertionLoggerHandlerTest to Unit Tests

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ReplicationBackupActivation.java

The changes fix intermittent failures of `testFailbackTimeout`:
- Server restart is now atomic with other server operations (start/stop) and won't loose any racy stop. This is just affecting tests
- Existing replication mechanism is very asynchronous by design and a live stop while backup data is not fully in sync can cause the backup to restart believing to have "good" in-sync data (because the activation sequence and NodeID are fine); this can affect both test that interrupt a syncing process mid-air AND real world. 
The latter requires more attention in a separate JIRA, because if backup crash after written the right NodeID and activation sequence (and live was stopped/crashed, before incrementing the coordinated sequence) it can still be restarted and, if the data is good, believe to …

ARTEMIS-3340 Atomic server restart and clean dirty activation: fix testFailbackTimeout

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPReplicaTest.java

2ee22912f07d4418e1f71bd496e016ad3123fede just added a test called "testDeleteQueueWithRemoveFalse" (just abvoe the context of this change). That in itself seems fine, but what was odd is the diff context for the change ended with context showing an existing test "testDoNotSendDelete" that appeared to want to test the same thing.
However it doesnt actually do that at all,  doing exactly the same thing as a third "testDoNotSendCreate" test, due to an argument not being used. This third test also doesnt do what its name suggests, with both of them instead verifying that a create command _is_ being sent.
This cleans things up so one test verifies the create is sent and the other that it isnt when configured, and renames them accordingly.
(Setting up a test server and monitoring that no …

ARTEMIS-3413: clean up mirror tests of create behaviour

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/MessagesExpiredPagingTest.java

The issue found by this test has been previously fixed as part of ARTEMIS-3234
There's no additional fixing needed. This is just to commit the test to avoid future regressions.

ARTEMIS-3234 Additional test with expiry and paging

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java

Changes that were going to be included in #3711 before it was prematurely merged. Resolves some issues as discussed and makes some simplifications to both the changes that were made and other existing code.

ARTEMIS-3449: futher fixes and simplifications

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/PacketImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/ReplicationResponseMessageV2.java

Fix a recursion and duplicate class name output from #3744 / 2481a784f3ba7648f4b4322335bd3d4061aa4b01

ARTEMIS-3475: fix a recursion and duplicate class name output 

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/ConsumerThread.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/addressSendMessage.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/sendMessage.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/services/sendMessageService.js
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AbstractControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlUsingCoreTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3493

ARTEMIS-3493 - expose User ID (JMS Message ID) in send tab of console

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js

see https://issues.apache.org/jira/browse/ARTEMIS-3571

ARTEMIS-3571 pluralization

---

docs/hacking-guide/en/tests.md

Issue link: https://issues.apache.org/jira/browse/ARTEMIS-3585
Fixed Broken link in the [tests.md](https://github.com/apache/activemq-artemis/blob/main/docs/hacking-guide/en/tests.md) file under the Writing Web Tests section.
cc @clebertsuconic @brusdev @jbertram

Fixed Broken link in tests.md

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/PrintData.java

I need to filter out some of the data when looking for issues.
Like I will not need to print every single page.
and some times I need to find the records that are not acked on Page

ARTEMIS-3595 PrintData option helping on visualization of data

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ActiveMQInvalidBufferException.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/BufferHelper.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/XidCodecSupport.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/util/XidCodecSupportTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/InvalidCoreClientTest.java

Co-authored-by: Viktor Kolomeyko <Viktor.Kolomeyko@r3.com>

ARTEMIS-3593 Defense against OME on parsing XID

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js

see https://issues.apache.org/jira/browse/ARTEMIS-3570

ARTEMIS-3570 more properties decoding in gui

---

artemis-features/src/main/resources/features.xml
pom.xml

Update to Netty 4.1.72 (and netty-tcnative to 2.0.46)

ARTEMIS-3559: update to Netty 4.1.72

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap-web-settings.txt
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/BindingDTO.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/WebServerDTO.java
artemis-dto/src/test/java/org/apache/activemq/artemis/dto/test/BindingDTOTest.java
artemis-dto/src/test/java/org/apache/activemq/artemis/dto/test/WebServerDTOTest.java
artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
artemis-web/src/test/java/org/apache/activemq/cli/test/WebServerComponentTest.java
artemis-web/src/test/resources/bootstrap_secure_web.xml
artemis-web/src/test/resources/bootstrap_web.xml
artemis-web/src/test/resources/bootstrap_web_old_config.xml
docs/user-manual/en/masking-passwords.md
docs/user-manual/en/security.md
docs/user-manual/en/using-server.md
docs/user-manual/en/web-server.md
examples/features/standard/camel/camel-broker/src/main/resources/activemq/server0/bootstrap.xml
examples/features/sub-modules/inter-broker-bridge/artemis-jms-bridge/readme.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/quorum/PluggableQuorumNettyNoGroupNameReplicatedFailoverTest.java
tests/smoke-tests/src/main/resources/containerService/bootstrap.xml

* Add BindingDTO to allow configuring multiple addresses to listen on
* Start a new ServerConnector for each binding and deploy the corresponding web-applications
* Update documentation and tests

ARTEMIS-3574 multiple bindings for embedded webserver

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/addressSendMessage.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/sendMessage.js

See https://issues.apache.org/jira/browse/ARTEMIS-3568

ARTEMIS-3568 send message screen

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientConsumerImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-3618

ARTEMIS-3618 Faster Artemis CORE client MessageListener::onMessage without SecurityManager

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/critical/MultiThreadCriticalMeasureTest.java

Avoiding intermittent failures
speed up test

NO-JIRA improvements on MultiThreadCriticalMeasureTest

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/preferences.js

see https://issues.apache.org/jira/browse/ARTEMIS-3633

ARTEMIS-3633 fixed description for password field in preferences tab

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/DivertImpl.java
docs/user-manual/en/diverts.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/divert/DivertTest.java

Similar semantics are possible with multicast queues and FQQN, but this feature is different enough and easy enough to implement that it makes sense to offer it.

ARTEMIS-3670 support diverting to multiple addresses

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/queue/StatQueue.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java

See https://issues.apache.org/jira/browse/ARTEMIS-3671 for before & after examples.

ARTEMIS-3671 fix readability of queue stat output

---

artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/SCRAMPropertiesLoginModule.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpNoHearbeatsTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/crossprotocol/ProtocolsMessageLoadBalancingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/util/CFUtil.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/bridgeTransfer/BridgeTransferingTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/logging/AuditLoggerTestBase.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/mmfactory/MMSFactoryTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/replicationflow/SoakPagingTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/transfer/TransferTest.java

Hi
I have fixed a typo error inside sources "unkown" -> "unknown"
all the best
matteo

Fixed a typo error  "unkown" -> "unknown"

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/queues.js
docs/user-manual/en/connection-ttl.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/management/OpenWireManagementTest.java

Hi
I have removed some lines with the wrong double semicolon at the end
all the best
matteo

Typo error: double semicolon at the end of line

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/AbstractSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/journal/ActiveMQJournalLogger.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingTest.java

This commit is part of a bigger task where I am improving paging.
This test is needed to validate some of the changes I am making on further commits.

ARTEMIS-3697 Adding test assertion on invalid IO on Paging

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverter.java
artemis-protocols/artemis-openwire-protocol/src/test/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverterTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/crossprotocol/OpenWireToAMQPTest.java

Avoid storing the following values as byte[] for OpenWire:
- Marshalled properties. We already store the unmarshalled properties
so this is altogether redundant.
- Producer ID.
- Message ID.
- Various destination values.
Also, eliminate the "original transaction ID" conversion code as it's
never actually set from the incoming message.

ARTEMIS-3698 avoid byte[] prop values when converting from OpenWire

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/RefCountMessage.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/MessageInternalImpl.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenwireMessage.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
examples/features/standard/opentracing/pom.xml
examples/features/standard/opentracing/readme.md
examples/features/standard/opentracing/src/main/java/org/apache/activemq/artemis/jms/example/OpenTracingPlugin.java
examples/features/standard/opentracing/src/main/java/org/apache/activemq/artemis/jms/example/OpenTracingPluginExample.java
examples/features/standard/opentracing/src/main/resources/activemq/server0/broker.xml
examples/features/standard/opentracing/src/main/resources/tracing.properties
examples/features/standard/opentracing/src/test/java/org/apache/activemq/artemis/jms/example/OpenTracingPluginTest.java
examples/features/standard/pom.xml
pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AcknowledgeTest.java

**Issue Link:** https://issues.apache.org/jira/browse/ARTEMIS-3686
hello @clebertsuconic, basing on the advise you gave me, to go back a step behind, this is what i have first produced.  
I am looking forward to seeing your comments
Thank you

ARTEMIS-3686: Adding example showing how to do telemetry support

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java

This gives a significant performance increase for my use case but I could not find a good way to demonstrate it through testing, so the added tests only focus on functionality

ARTEMIS-3771 - Rework destination handling for the OpenWire-protocol

---

examples/features/sub-modules/artemis-jakarta-ra-rar/src/main/resources/ra.xml
examples/features/sub-modules/artemis-ra-rar/src/main/resources/ra.xml

* update xml schemas
* fix ConnectionParameters
* remove TransactionManagerLocatorMethod and "The producer max rate"
* remove The max connections

ARTEMIS-3707 fix ra.xml

---

.mvn/wrapper/maven-wrapper.properties

Updates maven wrapper version to 3.8.5 to solve errors when building the project.

ARTEMIS-3797 Update maven wrapper version

---

RELEASING.md
artemis-website/pom.xml
docs/user-manual/en/README.md
docs/user-manual/en/book.json

Make the version number available to reference in the user manual, add it to the intro page

ARTEMIS-3804: make version number available to docs build

---

RELEASING.md

reflect change to CDN, and clarify some bits

NO-JIRA: update release instructions 

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/SimpleAddressManager.java

This is a test fix for AMQPClusterReplicaTest

ARTEMIS-3811 Cluster connections clashing with ANYCast addresses

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolHandler.java

This was being triggered by
org.apache.activemq.artemis.tests.integration.routing.MQTTRedirectTest.

ARTEMIS-3770 mitigate potential NPE

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/address/AddressAbstract.java

see https://issues.apache.org/jira/browse/ARTEMIS-3376

ARTEMIS-3376 fixed descriptions of option --no-anycast and option --no-multicast

---

tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/ExportImportTest.java

suppress significant teardown stacktraces after compatibility test that is a no-op...make test itself skip

NO-JIRA: suppress compatibility test stacktrace after no-op test

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/consumers.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/producers.js

see https://issues.apache.org/jira/browse/ARTEMIS-3858

ARTEMIS-3858 fix navigation from consumer/producer columns of a session to those consumers/producers

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageBrokerAccessor.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorMessageFactory.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/PagedReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/RoutingContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AckReason.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/LastValueQueue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/MessageReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RefsOperation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RoutingContextImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/RoutingContextTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/BrokerInSyncTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/MirrorControllerBasicTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/FakeQueue.java

I merged these two JIRAs into one as I was doing an overal check on Mirroring

ARTEMIS-3743 / ARTEMIS-3766 Use ACKReason on Mirror to determine target operations and fixing Delivering statistics on Mirror

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/perf/PerfClientCommand.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/CliPerfClientTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3901

ARTEMIS-3901 Fix artemis perf client --durable fails on exception

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java

and added test for primitive configuration properties
https://issues.apache.org/jira/browse/ARTEMIS-3917

ARTEMIS-3917 Fix incorrect getters/setters on Configuration API

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile.cmd
scripts/one-test.sh
tests/soak-tests/pom.xml
tests/soak-tests/src/main/resources/servers/horizontalPaging/broker.xml
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/SoakTestBase.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/TestParameters.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/client/ClientAbstract.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/client/ClientNonDivertedSoakTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/client/ClientParameters.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/client/ClientSoakTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/client/Receiver.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/paging/HorizontalPagingTest.java
tests/soak-tests/src/test/scripts/parameters-paging-short.sh
tests/soak-tests/src/test/scripts/parameters-paging.sh

Also some organization on soak test to allow this test
adding CLI operation to configure memory size of the broker

ARTEMIS-3928 Adding SoakTest for Paging with in many destinations

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/xml/XmlDataImporter.java

(Ran XmlImportExportTest with and without debug level enabled for the XmlDataImporter logger)

ARTEMIS-3950: dont prepare unused debug detail during xml data import

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java

@jbertram noticed some small issues with logging in recent changes when rebasing the logging branch

ARTEMIS-3843: fix audit logging additions

---

artemis-boot/src/main/java/org/apache/activemq/artemis/boot/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/ActionAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/ActionContext.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/InputAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/Browse.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/ConnectionAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/Consumer.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/Transfer.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/perf/PerfCommand.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/queue/StatQueue.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/RecoverMessages.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/user/AddUser.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/user/ListUser.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/user/RemoveUser.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/user/ResetUser.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/CheckTest.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCLIPlugin.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCreatePlugin.java

The ActiveMQ Artemis Maven plugin will throw system.out and log.info for a lot of stuff, This should mute some of that output.

ARTEMIS-3995 Mute Artemis Maven Plugin

---

.github/workflows/build.yml
.travis.yml
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/sasl/scram/SCRAMServerSASLFactory.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/sasl/scram/SHA256SCRAMServerSASLFactory.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/sasl/scram/SHA512SCRAMServerSASLFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/AbstractPrincipalLoginModule.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/Krb5LoginModule.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/SCRAMLoginModule.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java

ARTEMIS-4020: more logging tidyup

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressControl.java

Incorporating suggested changes by John Clifford

ARTEMIS-4033 Updating descriptions on the replay operations

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageCursorProviderImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/paging/MegaCleanerPagingTest.java

this is the second part of the fix (I missed the first part) where I am clearig midstream records as well.

ARTEMIS-4029 Avoid OME When too many pages are cleared all at once

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/EmptyList.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/LinkedList.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/LinkedListImpl.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/PriorityLinkedList.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/PriorityLinkedListImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageSubscriptionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/Page.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/list/PriorityLinkedListTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/util/LinkedListTest.java

- optimize startup time on paging (check-depage on startup)
- otpimize getNextPage() on complete pages
- optimize getFirstMessage() and paging. (avoid iterator usage)

ARTEMIS-4056 Paging Management optimizations

---

pom.xml

Update commons-text dep to 1.10.0 (transitive of commons-configuration2)

ARTEMIS-4060: update commons-text [transitive] dep to 1.10.0

---

pom.xml

https://issues.apache.org/jira/browse/ARTEMIS-4068

ARTEMIS-4068: speed up release preparation process

---

docs/user-manual/en/config-reload.md

* Fixed the `config-delete-divert` entry
* Added some formatting
* Reworded the description

Fix and rewrite the config-delete-* docs

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/RedeployTest.java
tests/integration-tests/src/test/resources/reload-divert-address-source1.xml
tests/integration-tests/src/test/resources/reload-divert-address-source2.xml
tests/integration-tests/src/test/resources/reload-divert-address-target1.xml
tests/integration-tests/src/test/resources/reload-divert-address-target2.xml
tests/integration-tests/src/test/resources/reload-divert-exclusive.xml
tests/integration-tests/src/test/resources/reload-divert-filter-none.xml
tests/integration-tests/src/test/resources/reload-divert-filter-x-eq-x.xml
tests/integration-tests/src/test/resources/reload-divert-filter-x-eq-y.xml
tests/integration-tests/src/test/resources/reload-divert-non-exclusive.xml

Reloading has been fixed for divert:
* filter
* address
* exclusive
Source address and exclusivity changes require divert redeployment.
Please review.

ARTEMIS-4078 Fix divert configuration reloading

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQDestination.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQResourceAdapter.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivation.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivationSpec.java

Fixes to expose properties in environments not recognizing is* accessors.

ARTEMIS-4093: Expose properties and support resource adapter in J2EE environments

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/ByteUtil.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/SizeFormatterUtil.java
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/status.js
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java

See https://issues.apache.org/jira/browse/ARTEMIS-3993

ARTEMIS-3993 fixed some MB style uses to use MiB; added support for MiB/GiB/etc in config

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js

see https://issues.apache.org/jira/browse/ARTEMIS-4120

ARTEMIS-4120 show description for mqtt-qos header

---

docs/user-manual/en/versions.md

Not sure if instructions for redirect setting were forgotten, but I think it is worth mentioning in versions file.

NO-JIRA Add forgotten upgrade documentation about console redirect

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPLargeMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerAggregation.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/ReferenceNodeStore.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/amqpBrokerConnectivity/AMQPMirrorBrokerConnectionElement.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/PagedReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/OperationContextImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/PostOffice.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/MessageReference.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AbstractProtocolReference.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/GroupFirstMessageReference.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/MessageReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/mirror/MirrorController.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/TransactionPropertyIndexes.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImpl.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/en/amqp-broker-connections.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReferenceDeliveryAnnotationTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPReplicaTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPSyncMirrorTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/config/impl/ConfigurationValidationTest.java

I am adding an option sync=true or false on mirror. if sync, any client blocking operation will wait a roundtrip to the mirror acting like a sync replica.

ARTEMIS-4136 Mirrored sync replica

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js

see https://issues.apache.org/jira/browse/ARTEMIS-4142

ARTEMIS-4142 explain 2 more header fields in webgui

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AutoCreateWithDefaultRoutingTypesTest.java

Adds some tests to validate that the destination prefixes if set and are used properly by the client are honored over the default address auto create routing type condiguration.

ARTEMIS-3153 Add tests for address prefixes for AMQP links

---

artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileXIncludeSchemaConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-acceptors.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-address-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-addresses.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-bridges.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-broadcast-groups.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-broker-connections.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-broker-plugins.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-cluster-connections.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-connection-routers.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-connector-services.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-connectors.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-discovery-groups.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-diverts.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-federations.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-grouping-handler.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-ha-policy.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-metrics.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-remoting-incoming-interceptors.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-remoting-outgoing-interceptors.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-resource-limit-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-security-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-store.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config.xml

Moves embedded XSD complexType definitions from XSD element definitions
to top-level types available for XML schema validation in IDEs.

ARTEMIS-3139 Anonymous types in Artemis config XSD

---

docs/user-manual/en/using-server.md

Noticed it's very difficult to navigate from docs to download page

Add link to download page

---

artemis-website/package-lock.json
artemis-website/package.json
artemis-website/pom.xml

Bump versions of NPM, Node, & HonKit. The changes to package-log.json were automatically generated.

ARTEMIS-4158 upgrade doc generation utils

---

docs/user-manual/en/amqp-broker-connections.md

Fix a few small typos in the broker connections docs

ARTEMIS-4178 Fix some minor typos in broker connections docs

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/diagram.js

see https://issues.apache.org/jira/browse/ARTEMIS-4183

ARTEMIS-4183 fix relations on refresh icw added nodes in diagram

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
pom.xml
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/ClientLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/ConnectionLeakTest.java
tests/soak-tests/pom.xml
tests/soak-tests/src/main/resources/servers/lminterrupt/management.xml
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/SoakTestBase.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/interruptlm/LargeMessageInterruptTest.java

I am now removing the negatives once the file is removed or reused

some tasks around Memory Leaks in the broker

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java

I am taking existing tests to validate this PR.

ARTEMIS-4208 OpenWire chunk receive should not issue a flush

---

pom.xml

Replacement PR for #4412 to reference JIRA.

ARTEMIS-4220: update spring to 5.3.26

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml

This is how I see these properties.
I am trying to make this easier to understand.

ARTEMIS-4236 Reorganize broker.xml around paging properties

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java
artemis-server/src/test/resources/FileConfigurationParser-addressWithNoRoutingType.xml
docs/user-manual/en/versions.md
tests/integration-tests/src/test/resources/reload-diverts-updated.xml
tests/integration-tests/src/test/resources/reload-diverts.xml

- fix syntax used for 'addresses' CLI option
- update release notes
- enforce new semantics on parsing & add test

ARTEMIS-4212 handful of updates

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ParameterisedAddress.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/uri/BeanSupport.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/uri/URISchema.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/uri/URISupport.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/util/NettyReadable.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java
examples/features/standard/interceptor-mqtt/src/main/java/org/apache/activemq/artemis/mqtt/example/SimpleMQTTInterceptor.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/util/PropertyUtil.java

avoid UnsupportedEncodingException handling

ARTEMIS-4239 use StandardCharsets.UTF_8

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/LargeMessageControllerImpl.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/core/client/impl/LargeMessageControllerImplTest.java

Say packets stopped flowing, and you are calling receive(0); The Controller should check if packets didn't arrive and throw a proper exception

ARTEMIS-3809 Fixing LargeMessageController timeout

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQSession.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AutoCreateJmsDestinationTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSFQQNConsumerTest.java

co-authored with Justin Bertram

ARTEMIS-4259 JMS consumer + FQQN + selector not working

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java

Also improves the wording of some several related statements.

ARTEMIS-4319 mitigate NPE in paging log statement

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
artemis-protocols/artemis-openwire-protocol/src/test/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumerTest.java

https://issues.apache.org/jira/browse/ARTEMIS-4095

ARTEMIS-4095: fix delivering message size accounting

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/ReferenceIDSupplier.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/ReferenceNodeStore.java

This is in relation to comments from PR #4555

ARTEMIS-4366 Some Adjustment to class names on Mirror

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/routing/caches/LocalCache.java

Address thread safety issue noticed during #4584

ARTEMIS-4406: update LocalCache to use a ConcurrentHashMap

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java

https://issues.apache.org/jira/browse/ARTEMIS-4398

ARTEMIS-4398 - support configuring database using Broker Properties

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/JMSOrderTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/PrefetchRedeliveryCountOpenwireTest.java

ARTEMIS-4410 - process delivery cancellations before removing [exclusive] consumer

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java

The insert + remove methods in AbstractJournalStorageManager that can be used by the connection router LocalCache are not thread safe. They operate on a 'parent' ConcurrentHashMap, but entries within it are regular HashMap values and so are not thread safe despite potentially being used concurrently.
Switch the sub-maps to ConcurrentHashMap accordingly and also reuse some identical insertion code to simplify.

ARTEMIS-4417: use ConcurrentHashMap for thread safety

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQMessageHandler.java

* Unsetting the transation timeout on the TransactionManager after the onMessage has been called
Issue: https://issues.apache.org/jira/browse/ARTEMIS-4427

ARTEMIS-4427 MDB reusing Thread is using wrong transactionTimeout.

---

artemis-distribution/src/main/assembly/source-assembly.xml
pom.xml

see https://issues.apache.org/jira/browse/ARTEMIS-4433

ARTEMIS-4433 fix Reproducible Builds issues

---

pom.xml

Aside from upgrading OWASP this commit also changes the configuration to aggregate the reports from all sub-modules. This makes analyzing vulnerabilities across the project much simpler.

ARTEMIS-4437 upgrade OWASP to 8.4.0

---

docs/user-manual/configuring-transports.adoc

https://issues.apache.org/jira/browse/ARTEMIS-4449

ARTEMIS-4449 Fix url parameter separator in acceptor configuration

---

docs/user-manual/metrics.adoc

see https://issues.apache.org/jira/browse/ARTEMIS-4486

ARTEMIS-4486 add missing bits from metrics documentation

---

pom.xml

Issue: https://issues.apache.org/jira/browse/ARTEMIS-4500

ARTEMIS-4500 upgrade netty to 4.1.101.Final

---

artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/config/impl/FileJMSConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/Validators.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/utils/XMLConfigurationUtil.java

No semantic changes here. Just some code gardening.

ARTEMIS-4546 modernize Validators, etc.

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js

see https://issues.apache.org/jira/browse/ARTEMIS-4547
tested in browser -> OK

ARTEMIS-4547 properly display empty message

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionCallback.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ManagementRemotingConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/CoreSessionCallback.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/protocol/SessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/HangConsumerTest.java

Full test-suite is green on this.

ARTEMIS-4530 clean up SessionCallback interface

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/deleteQueue.js

see https://issues.apache.org/jira/browse/ARTEMIS-4549

ARTEMIS-4549 fix texts for queue operations

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/Mergeable.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/HierarchicalObjectRepository.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/AddressSettingsTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/RepositoryTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/MessageExpirationTest.java

Merge multiple address setting matches on a new instance to be idempotent.

ARTEMIS-4537 Fix merge of multiple address setting matches

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/HierarchicalObjectRepository.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/RepositoryTest.java
docs/user-manual/address-settings.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AddressSettingsTest.java

This PR is a draft only because it depends on #4715

ARTEMIS-4488 Merge settings with wildcards after literal matches

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ClusterConnectionControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ClusterConnectionControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ClusterConnectionControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ClusterConnectionControlUsingCoreTest.java

https://issues.apache.org/jira/browse/ARTEMIS-4557

ARTEMIS-4557 expose producer window size in clusterconnection JMX

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/queue/QueueGroup.java

see https://issues.apache.org/jira/browse/ARTEMIS-4565

ARTEMIS-4565 fix output for 'artemis help'

---

artemis-hawtio/activemq-branding/src/main/webapp/plugin/css/activemq.css
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/diagram.js

See https://issues.apache.org/jira/browse/ARTEMIS-4574
Note that the change in file `artemis-hawtio/activemq-branding/src/main/webapp/plugin/css/activemq.css` may have to be repeated for AMQ (which uses a different branding).

ARTEMIS-4574 fix broker diagram

---

tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/utils/RealServerTestBase.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/ClusteredMirrorSoakTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/InterruptedLargeMessageTest.java

There is no semantic change on this commit.
I wrote a test to validate a scenario and this is to keep the test in the codebase.

ARTEMIS-4677 Validating AutoCreate with Mirror and Clustering

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFile.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactory.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactoryDriver.java
tests/db-tests/src/test/java/org/apache/activemq/artemis/tests/db/paging/RealServerDatabasePagingTest.java

- fixing leaks
- page.exists() would lead to a select(all) and find.

ARTEMIS-4682 Improving performance of reloading JDBC storage

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/Connection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMAcceptor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMConnection.java

Fixing a few intermittent failures

ARTEMIS-4691 Fixing LockManagerBackupSyncJournalTest

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageTest.java
tests/compatibility-tests/pom.xml
tests/compatibility-tests/src/main/java/org/apache/activemq/artemis/tests/compatibility/GroovyRun.java
tests/compatibility-tests/src/main/resources/multiVersionMirror/backupServer.groovy
tests/compatibility-tests/src/main/resources/multiVersionMirror/mainServer.groovy
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/MirroredVersionTest.java

Issue manifested during Mirror delivery and full brokers restart

ARTEMIS-4725 AMQP Delivery reencoding before getDeliverBuffer

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/Page.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationEndpoint.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/utils/cli/helper/HelperCreate.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/NettyReplicatedFailoverTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/checkTest/CheckTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/ReplicatedMirrorTargetTest.java

PagingStore is supposed to send an event to replica on every file that is closed. There are a few situation where the sendClose is being missed and that could generate leaks on the target

ARTEMIS-4776 Pages may leak as open on Replicated Target

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPLargeMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/LargeServerMessageImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/LargeServerMessageInSync.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/nullpm/NullStorageLargeServerMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicatedLargeMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationEndpoint.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/LargeServerMessage.java

This is a regressio after ARTEMIS-4784

ARTEMIS-4813 Large Message in replication / sync could lose part of the body

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicatedJournal.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/replay/ReplayManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/retention/ReplayWithReplicationTest.java

co-authored: Jean-Pascal Briquet provided the testcase

ARTEMIS-4667 ReplayManager does not work with replication

---

pom.xml

Update to latest protonj2 to gain access to new test peer APIs.

ARTEMIS-4842 Update protonj2 to v1.0.0-M20

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/predicate/ActiveMQFilterPredicate.java
docs/user-manual/core.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java

This commit also adds a couple of tests to verify the documented behavior works.

ARTEMIS-4914 clarify docs on core + client ID

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/EventHandler.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/Events.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ProtonHandler.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AMQPProtocolErrorHandlingTest.java

Handle any exceptions from the proton transport and set the error on the transport for processing in the events dispatch cycle by adding in handling of the transport error event.

ARTEMIS-4919 Handle Exception from proton transport process

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/ArtemisMBeanServerGuard.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/management/ArtemisMBeanServerGuardTest.java

Although this doesnt affect the current console it does the new so needs addressing

ARTEMIS-4950 - MBeanGuard throws an NPE

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFlowControlFailDispositionTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSecurityTest.java

When an incoming AMQP large message send is rejected the broker should delete the large message file as part of the reject handling.

ARTEMIS-4982 Cleanup AMQP large message files for rejected sends

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPMirrorConnectionTest.java

If a user for some reason force closes the local mirror connection SNF consumer or the actual connection but hasn't stopped the broker connection itself the connection should recover and rebuild. The fix ensures that if local connections are closed first then local session resources get freed.

ARTEMIS-5007 Ensure mirror connection recovers from manual closures

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientMessageBundle.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java

Two commits for two Jiras for two potential NPEs in the same method. :dizzy_face:

Mitigate NPEs in ScaleDownHandler

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/security/impl/SecurityStoreImpl.java

Existing tests should suffice to validate this change.

ARTEMIS-5052 hash authentication cache keys

---

pom.xml

Update to latest release, used in AMQP tests

ARTEMIS-5058 Update Qpid protonj2 to v1.0.0-M22

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQServerMessagePlugin.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/CorePluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MethodCalledVerifier.java

PR for https://issues.apache.org/jira/projects/ARTEMIS/issues/ARTEMIS-5063

ARTEMIS-5063 messageMoved addition in ActiveMQServerMessagePlugin

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReceiverDispositionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveInterceptorTest.java

When a bytes property is added to an AMQPMessage and it is then reencoded it will fail without first wrapping the byte array in an AMQP binary as required by the ApplicationProperties section specification defined type allowances.

ARTEMIS-5074 Fix encoding of bytes properties as Binary in AMQPMessage

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/addresses.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/connections.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/consumers.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/producers.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/queues.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/sessions.js
artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/services/toolbar.js
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/ActiveMQAbstractView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/AddressView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/ConnectionView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/ConsumerView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/ProducerView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/QueueView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/SessionView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/predicate/ActiveMQFilterPredicate.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/management/impl/view/ViewTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/management/impl/view/predicate/PredicateTest.java
docs/user-manual/management.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java

These are a few commits around the management operations used by the web console. They include usability and documentation improvements so that folks can leverage these methods in their own integrations.

Usability & Documentation improvements for management

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Completion.java
docs/user-manual/using-cli.adoc

Other projects like quarkus will do source <(./artemis completion)
This seem more standard and easier to understand.

ARTEMIS-5111 improve how auto-completion is handled in artemis

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPLargeMessageReader.java

When the final frame of a large message is being written to the file in the session thread and an IO error occurs such that that connection is torn down, the large message reader can be closed before the message is fully processed resulting in corruption. The large message file close logic needs to occur on the session thread so that the processing of the bytes can finish and the message gets added to the Queue and the close can react by not deleting the file when it runs following the read task.

ARTEMIS-5155 Race on AMQP large message read and close

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/remoting/ReconnectTest.java

I'm trying to make it faster and less likely to fail over non issues

ARTEMIS-5166 Improving ReconnectTest

---

docs/user-manual/message-expiry.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/AutoCreateExpiryResourcesTest.java

ARTEMIS-5170 Fix AutoCreateExpiryResourcesTest and document expiry of expiry

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientConsumerImpl.java

Ensure that the temproray large message content can only be read by the user associated with the process.
Iusse: https://issues.apache.org/jira/browse/ARTEMIS-5172

ARTEMIS-5172 Reduce the permissions on temp file.

---

.github/dependabot.yml

ARTEMIS-5174 Have dependabot ignore jgroups until JGRP-2794 is resolved

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPBridgeToAddressTest.java

Make a few changes to a test that is failing in CI intermittently.

ARTEMIS-5437 Tweak test to fix intermittent CI failures

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java

Prevent a deadlock when the handler method holds the a lock from the Queue but needs the local status lock which is held by scaledown or other state changing operation that needs the Queue lock.

ARTEMIS-5377 BridgeImpl deadlock fix on handle vs operation

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPConnectSaslTest.java

Previous PR was closed but issues were adressed https://github.com/apache/activemq-artemis/pull/5721

ARTEMIS-5316 XOAUTH2 SASL mechanism for broker connection

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/bridge/AMQPBridgeFromQueuePolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/bridge/AMQPBridgeToQueuePolicyManager.java

Add synchronized tags to methods in the AMQP bridge from and to queue policy managers

ARTEMIS-5651 Add missing synchronized tag to some brifge methods

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPTunneledCoreLargeMessageWriter.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPTunneledCoreLargeMessageWriterTest.java

Ensure that the read size from the delivery annotations and the core header and properties encoding buffer is calculated correctly so that when spanning multiple frames an error is not thrown from the copy.

ARTEMIS-5689 Fix tunneled core message writer encoding

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPTunneledCoreLargeMessageWriter.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPTunneledCoreLargeMessageWriterTest.java

If the connection enters flow control and there are pending bytes in the frame buffer of the tunneled core large message writer we need to move them into the sender before releasing the frame buffer to avoid losing them.

ARTEMIS-5696 Ensure that staged bytes are not lost during flow control
