artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/journal/ActiveMQJournalLogger.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/JournalImplTestUnit.java

https://issues.apache.org/jira/browse/ARTEMIS-135
This is importing a recent fix from the journal on the old version.
If a crash happened between the create file and the fill of the file the
file wouldn't be loaded and the server wouldn't start until you removed the offending file

ARTEMIS-135 - Fix on journal load

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQTransaction.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-service-extensions/src/main/java/org/apache/activemq/artemis/service/extensions/xa/recovery/ActiveMQXAResourceWrapper.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/InterruptedMessageHandlerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/SessionCloseTest.java

https://issues.apache.org/jira/browse/ARTEMIS-136
From what I researched from implementers of XA TM if you throw ERR over communication errors the transaction manager will create
an heuristic transaction to be manually dealt with.
Other XA Implementations (such as Oracle JDBC) are return FAIL over communication failures during any XA operation.

ARTEMIS-136 - XA Error fix with proper exception error

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/ProtocolHandler.java

This change is needed after upgrading netty which now has slightly different semantics around http.

change the protocol decoder to check for a FullHttpRequest instead of a DefaultFullHttpRequest.

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/ProtonProtocolManager.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AMQPConstants.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientConnectionContextFactory.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerConnectionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerConnectionContextFactory.java

https://issues.apache.org/jira/browse/ARTEMIS-143
Set the idle-timeout on the proton Transport object and also call tick so we send our own heartbeats.

ARTEMIS-143 - expose idle-timeout

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-142
This should fix CoreClientOverOneWaySSLTest
I have previously exposed this exception as some errors were being hidden
Now that I have cleared those, It's best to remove this as some errors are now happening

[ARTEMIS-142] fixing some tests

---

artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/ActiveMQSecurityManagerImpl.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/security/impl/ActiveMQSecurityManagerImplTest.java

The current Security Manager implementation was returning the username
instead of the default password when validating  the default user.
This patch returns the correct value and cleans up the validate method.

Set default password properly in security manager

---

tests/activemq5-unit-tests/pom.xml

Guys,
In addition to the packages we've discussed I added one more package because almost all the passing tests are in that one. I also excluded two tests that currently cause the tests to last forever.
Howard

Include just a few packages in activemq5-unit-tests to start with

---

pom.xml
tests/integration-tests/pom.xml

We now support MQTT v3.1 protocol name, so we can remove this snapshot dep.

Downgrade Paho SNAPSHOT dep to latest release

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/CompactJournal.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/DataAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/PrintData.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/XmlDataExporter.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/NodeManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/FileLockNodeManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/InVMNodeManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/LiveOnlyActivation.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/discovery/DiscoveryBaseTest.java

This should avoid users damaging data while the server is running (by for instance running compact while the server is running)
https://issues.apache.org/jira/browse/ARTEMIS-187

ARTEMIS-187 hold lock between live server and tools

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/SoftValueHashMap.java
etc/checkstyle-suppressions.xml
etc/checkstyle.xml
pom.xml
tests/activemq5-unit-tests/pom.xml

This PR updates maven-checkstyle-plugin to 2.16 which brings in checkstyle 6.2, and contains some related tweaks and fixes here and there.
Among the obvious things this removes one source of pain when using Eclipse to work on Artemis -- Eclipse has quite a new checkstyle installed which didn't work with the old configuration that Artemis had.

Checkstyle updates

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRAManagedConnection.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQResourceAdapter.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ConnectionFactoryProperties.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/ActiveMQClusteredTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/OutgoingConnectionTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ConnectionFactoryPropertiesTest.java

Inbound sessions are always created from the same ActiveMQConnectionFactory
which means the load-balancing policy is applied to them in the expected
manner. However, outbound sessions are created from independent, unique
ActiveMQConnectionFactory instances which means that the load-balancing
doesn't follow the expected pattern.
This commit changes this behavior by caching each unique
ActiveMQConnectionFactory instance and using it for both inbound and outbound
sessions potentially. This ensures the sessions are load-balanced as
expected.

ARTEMIS-210 outbound RA connection load-balancing

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java

In addDestination() put the security check right before
actual queue creation. That'll also fix BasicSecurityTest
regression.

Minor refactor of OpenWireProtocolManager

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/amq/TransactionContextTest.java

This leak happens with amq5.12.0. It didn't happen
with amq5.11.1. Adding connection.start() can work
around this seemingly 5.12.0 issue.

Fix thread leak in test TransactionContextTest

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis

After create a broker using main artemis script, this one needs to be created using JAVA_HOME environment correctly as well, otherwise the broker will be unable to find java_home. 
I did perform a search at the whole project and this is the only remaining place which needs to change the JAVA_HOME value at the script.

JAVA_HOME fix at artemis-cli

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/transports/netty/NettyConnectorWithHTTPUpgradeTest.java

Demonstrate that the Artemis acceptor receiving HTTP(S) upgrade connections
doesn't need any SSL configuration.

Clarify HTTP(S) upgrade config

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryInternal.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionInternal.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/DelegatingSession.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/bridge/BridgeTest.java

Netty 4.x uses pooled buffers.  These buffers can run out of memory when
transferring large amounts of data over connection.  This was causing an
OutOfMemory exception to be thrown on the CoreBridge when tranferring
large messages.  Netty provides a callback handler to notify listeners
when a Connection is writable.  This patch adds the ability to register
connection writable listeners to the Netty connection and registers the
relevant callback from the Bridge to avoid writing when the buffers are
full.

ARTEMIS-262 Fix Bridge OOM exception

---

artemis-service-extensions/src/main/java/org/apache/activemq/artemis/service/extensions/ServiceUtils.java
artemis-service-extensions/src/test/java/org/apache/activemq/artemis/service/extensions/tests/xa/ServiceUtilsTest.java
artemis-service-extensions/src/test/resources/META-INF/services/org.apache.activemq.artemis.service.extensions.xa.ActiveMQXAResourceWrapperFactory

In ServiceUtils, loads services from an AccessController.doPriviledged
block and use the ServiceUtils's own classloader instead of the TCCL
(that may be different depending on who's requesting a managed
connection factory first)
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-294

[ARTEMIS-294] Use doPriviledged block for ServiceLoader

---

artemis-commons/pom.xml
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/IPV6Util.java
artemis-jms-client/src/test/java/org/apache/activemq/artemis/uri/ConnectionFactoryURITest.java

Previously we were using a long regular expression to detect whether or not a
given host was IPv6. However, this was brittle and hard to read. Since we are
already shipping Google Guava in the distribution it made sense to use the
Guava method com.google.common.net.InetAddresses#isInetAddress rather than
the regular expression.

ARTEMIS-298 IPv6 escape broken

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMAcceptor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMAcceptorFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/remoting/Acceptor.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/AcceptorsTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/server/impl/fake/FakeAcceptorFactory.java

This is just so users will know the name of the acceptor that had the issue on logs

ARTEMIS-297 Including acceptor name on logs

---

artemis-features/pom.xml
artemis-features/src/main/resources/artemis.xml
artemis-features/src/main/resources/features.xml
artemis-features/src/main/resources/org.apache.activemq.artemis.cfg
pom.xml

Adds default configs to the feature so a broker is created automatically when the feature is installed.
This also fixes a bug in the feature file I introduced by placing the license header in the wrong position.

ARTEMIS-93 Add default config to feature

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis

I'm not sure this is the best solution, but it has the benefit of being really simple and it solves the problem outlined in ARTEMIS-318. My only other thought here would be to use a profile per command (e.g. artemis-run.profile, artemis-stop.profile, etc.).

ARTEMIS-318 use profile JAVA_ARGS only for 'run'

---

pom.xml

Although the scope is "provided" we still aim to track the licenses in
the pom.xml, to avoid mistakes going forward.

Add license comment to OSGI deps

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java

It's possible for the latch used for flow control here to get out of sync. In
other words, multiple count-downs can occur between count-ups so that the latch
always has a count > 0. When this situation arises then every single packet
sent to the replica is delayed by 5 seconds.
The solution here essentially is to eliminate the latch completely and use a
condition/wait/notify pattern.

ARTEMIS-350 fix for potential race

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java

This restores a call to ClientSessionFactory#cleanup that appears to have been
mistakenly removed by a previous change related to this JIRA.

ARTEMIS-385 clean-up factory on timeout

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/cluster/JMSFailoverListenerTest.java

ActiveMQConnection implements FailoverEventListener which executes client's
FailoverEventListeners in separated threads in background. The old implementation
does not guarantee ordering of their executions. The commit improves the
implementation to guarantee it.

ARTEMIS-538 - [Artemis Testsuite] JMSFailoverListenerTest#testManualFailover fails

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/TransportConfiguration.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/api/core/TransportConfigurationTest.java

Obfuscate truststore password in TransportConfiguration.toString() in the same way as keystore. The password will not be logged in plain text when bridge is connected.

ARTEMIS-551 Obfuscate truststore password

---

artemis-selector/src/main/javacc/HyphenatedParser.jj
artemis-selector/src/main/javacc/StrictParser.jj
artemis-selector/src/test/java/org/apache/activemq/artemis/selector/SelectorTest.java

Enforce an EOF on the expression so the selector parser keeps going and
catches the broken selector statement.

ARTEMIS-568 Catch broken JMS selector expressions

---

artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPClientSenderContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/AMQPClientSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/AbstractProtonReceiverContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/client/ProtonClientSessionContext.java
artemis-protocols/artemis-proton-plug/src/main/java/org/proton/plug/context/server/ProtonServerReceiverContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonTest.java

The sender abstraction must be able to update its sender address in the
case of dynamic senders whose target address is not set until the code
initializes the link and creates a destination for it.

ARTEMIS-585 support send on dynamic sender link

---

artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/bridge/ActiveMQJMSBridgeLogger.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/bridge/impl/JMSBridgeImpl.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/JMSBridgeReconnectionTest.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/jms/bridge/JMSBridgeClusteredTest.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/jms/bridge/JMSBridgeReconnectionTest.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/jms/bridge/JMSBridgeTest.java

In cases where there are many JMS bridges defined on a broker it should
be possible to identify any error message by a bridge name.

ARTEMIS-596 JMS Bridge messages should be identified.

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/BridgeConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ClusterConnectionConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/bridge/BridgeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java

Something bizarre happened with commit
8f52a622d0d883ca5e9f60ba7754ed51de38cc5c in April 2015. It reverted the
changes from both c1111cc156684b15938ab3f8e34df9f4b64f57c4 and
ada112a6a37dce8ddf48e2238904421b2ca8e0dc. This commit fixes that.

ARTEMIS-569 fix bridge producerWindowSize

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/reader/MessageUtil.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQMessage.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/management/impl/openmbean/JMSOpenTypeSupport.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/Stomp.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompProtocolManager.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompUtils.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/security/SecurityStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/security/impl/SecurityStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/ActiveMQJAASSecurityManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/ActiveMQSecurityManager3.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/en/configuration-index.md
docs/user-manual/en/security.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/HangConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/management/JMSQueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/security/SecurityTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/StompTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/StompTestWithSecurity.java

Implements a new feature to aid in security auditing by adding the name
of the validated user to the messages it sends.

ARTEMIS-584 add validated user to msg

---

docs/hacking-guide/en/ide.md

Adding instructions to set up test projects to work in eclipse that
depend on the unit-tests project.  This is necessary so that the
generated logger can be found.

https://issues.apache.org/jira/browse/ARTEMIS-730

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/ConcurrentUtil.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java
artemis-junit/src/main/java/org/apache/activemq/artemis/junit/ActiveMQConsumerResource.java
artemis-selector/pom.xml
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/group/impl/LocalGroupingHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AnyLiveNodeLocatorForReplication.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AnyLiveNodeLocatorForScaleDown.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/NamedLiveNodeLocatorForReplication.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/NamedLiveNodeLocatorForScaleDown.java
pom.xml
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/util/UnmodifiableLink.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cli/DestinationCommandTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/ExpireWhileLoadBalanceTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/GlobalPagingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonMaxFrameSizeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/proton/ProtonPubSubTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/rest/RestDeserializationTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/rest/RestTestBase.java

This updates error prone to 2.0.9. It is not the latest version at the moment (2.0.13 is), but later versions than that introduce new errors that are unrelated to the missing Overrides I'm doing this for, so I suggest tackling them separately sometime. The `Condition.await` WaitNotInLoop fixes are necessary, can't have a new enough error prone without them (or without dialing WaitNotInLoop back from error). Review for these appreciated.
artemis-selectors' generated code doesn't pass the missing overrides check, so for the moment this downgrades that check to warnings for the submodule. I don't know if this could be done only for the `generated-sources` dir therein.

Update error prone, flag missing @Override as error

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/message/JMSMappingOutboundTransformer.java

Removes the append of the destination annotations from the outbound JMS
transformer as the legacy client has be unsupported at Qpid for quite
some time now.

ARTEMIS-763  Remove the legacy Qpid JMS client annotations

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReceiverWithFiltersTest.java

The broker needs to return only the filters that are supported on a
receiver attach otherwise the remote is not aware that the broker is not
able to honor the requested configuration of the receiver.

ARTEMIS-776 Attach response should only list supported filters

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ServiceRegistry.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ConnectorsService.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServiceRegistryImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/config/impl/ConnectorsServiceTest.java

This adds management operations for creating and destroying connector services at run time. This feature is needed when building a messaging service where the topology changes and the broker must be disconnected from the network.
I made the ConnectorsService class thread safe in case the management operations can be called concurrently. I'd also like to hear your thoughts on the exception handling. I've tried to do the same 'ignore and log' behavior when creating the connector services at startup. For management requests, I think the errors should be propagated to the client.

ARTEMIS-824: Add management routines for connector services

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/client/AMQPClientConnectionFactory.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ProtonHandler.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/ProtonTest.java

We would like to be able to specify connection properties for outgoing connections in EnMasse.

 ARTEMIS-814: Support specifying connection properties

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/QuorumVoteServerConnect.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/SharedNothingBackupQuorum.java

remove reconnect attempt as it serves no purposes as replication has stopped anyway.
Ensure if vote fails thatthe latch is counted down to avoid delay.
If we can't detect live has failed signal failure in replicating.
https://issues.apache.org/jira/browse/ARTEMIS-866

ARTEMIS-866 - quorum fixes

---

artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/ActiveMQStompException.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/ActiveMQStompProtocolMessageBundle.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompConnection.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/v11/StompFrameHandlerV11.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/v12/StompFrameHandlerV12.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v11/StompV11Test.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v12/StompV12Test.java

https://stomp.github.io/stomp-specification-1.2.html#Value_Encoding

Treat STOMP 1.1+ undefined header escape sequences as errors

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/sasl/ServerSASLPlain.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSecurityTest.java

If the SASL plain mechanism arrives with the authzid value set the
mechanism needs to account for its presence and use the correct fields
of the exchange to get the username and password values.  Adds some
tests to validate this fix.

ARTEMIS-901 Account for the presence of authzid in sasl plan auth

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/ClientDefinedMultiConsumerTest.java

with amqp and address doesnt exist
https://issues.apache.org/jira/browse/ARTEMIS-918

ARTEMIS-918 - use requested routing type when client defined

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java

If the object received is not an expected HttpResponse, close the
ChannelHandlerContext and countdown the latch
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-931

[ARTEMIS-931] Improve HTTP Upgrade connection

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java

* Fix isEquivalent() method to take into account the activemqServerName
property when httpUpgradeEnabled is true. Two ActiveMQ server hosted on
the same app server may have the same host and port (corresponding to
the Web server HTTP port). The activemqServerName property is used to
distinguish them.
* Iron out HTTP upgrade handler so that the latch is always count down
and the channel context is closed unless the handshake was completed
successfully
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-931

[ARTEMIS-931] Fix HTTP Upgrade Connection

---

artemis-cli/src/main/resources/schema/artemis-import-export.xsd

https://issues.apache.org/jira/browse/ARTEMIS-943
queueType in the artemis-import-export schema needs to be marked with
min and max occurs attributes to specify that the element can occur more than one
time.  This is important so JAXB generates the correct bindings.

ARTEMIS-943 fix queueType in import-export schema

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/SimpleOpenWireTest.java

When a producer sends a messages to a temp destination created from
another connection, it fails. The reason behind it is that the
producer's connection didn't receive the advisory message (notification)
from broker about this temp destination, and it will throw an exception
if it doesn't know this temp destination.
The fix is send the advisory to the client so that it knows this destination.

ARTEMIS-980 Openwire can't send message to temp destination

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverter.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/SimpleOpenWireTest.java

When sending an empty ObjectMessage, broker doesn't
write a 'length' field to the message buffer. In delivery
the broker tries to read the length from the buffer, which
causes "IndexOutOfBoundsException".
To fix it, we need to check if the buffer is empty or not,
and only read it if the buffer is not empty.

ARTEMIS-981 OpenWire can't receive empty ObjectMessage

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/integration/FileBroker.java
artemis-commons/src/main/java/org/apache/activemq/artemis/core/server/ServiceComponent.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/EmbeddedServerTest.java
artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java

Due to recent changes, the web component is shutdown by the
server, but the shutdown flag is lost so the web component's
cleanup check method is not get called and the web's tmp
dir is left there after user stopped the broker (control-c).
The fix is add a suitable API to allow passing of the
flag so the web component can make sure its tmp dir gets
cleaned up properly before exiting the VM.

ARTEMIS-988 Regression: web tmp dir not cleaned up

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/ActiveMQScheduledComponentTest.java
artemis-junit/src/main/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQResource.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceWithoutAddressExceptionTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceWithoutAddressTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/ActiveMQProducerResourceTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQResourceCustomConfigurationTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQResourceFileConfigurationTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQResourceTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedJMSResourceMultipleFileConfigurationTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedJMSResourceQueueTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedJMSResourceSingleFileConfigurationTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/EmbeddedJMSResourceTopicTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/MultipleEmbeddedActiveMQResourcesTest.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/MultipleEmbeddedJMSResourcesTest.java
artemis-web/src/test/java/org/apache/activemq/cli/test/WebServerComponentTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ReceiveTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/clientcrash/PendingDeliveriesTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/FailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/util/SpawnedVMSupport.java

This commit fixes tests:
ActiveMQScheduledComponentTest.testAccumulationOwnPool
PendingDeliveriesTest.testWithtReconnect
ReceiveTest.testReceiveImmediate
ActiveMQProducerResourceTest.testSendString
EmbeddedActiveMQResourceTest.testSendString
MultipleEmbeddedActiveMQResourcesTest.testMultipleServers
MultipleEmbeddedJMSResourcesTest.testMultipleServers
ActiveMQDynamicProducerResourceWithoutAddressTest.testSendString
ActiveMQDynamicProducerResourceWithoutAddressExceptionTest.testSendBytesToDefaultAddress
ActiveMQDynamicProducerResourceTest.testSendString
ActiveMQServerControlTest.testTotalMessageCount
EmbeddedActiveMQResourceCustomConfigurationTest.testCustomConfiguration
EmbeddedJMSResourceMultipleFileConfigurationTest.testConfiguration
EmbeddedJMSResourceQueueTest.testPushObjectMessage …

ARTEMIS-995 Bulk of test fixes

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/ManagementExceptionHandlingTest.java

Artemis expose createQueue() method to management console like Jon.
If the queue to be created already exists it throws an ActiveMQException
back to the console, which will get a ClassNotFoundException when
deserializing the exception.
To fix that it should throw a common java exception like IllegalStateException.

ARTEMIS-1024 Management operation causes ClassNotFoundException

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenwireMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/PagedReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/LastValueQueue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/PostOfficeJournalLoader.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AcknowledgeTest.java

As part of my refactoring on AMQP, the broker shouldn't rely on Application properties
for any broker semantic changes on delivery.
I am removing any access to those now, so we can properly deal with this post 2.0.0.

ARTEMIS-1009 AMQP shouldn't use application properties

---

tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpAbstractResource.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpEventSink.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpReceiver.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSender.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpTransactionCoordinator.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpTransactionTest.java

Update the AMQP test client to allow for better inspection of the
delivery updates that happen during normal use.  Use those modification
to check that when the broker's sender accepts and settles a non-settled
disposition it adds a proper TransactionState disposition with the
correct outcome and txn-id in that state.

ARTEMIS-60 Validate AMQP sender applied TransactionState

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/DefaultSensitiveStringCodec.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java

(cherry picked from commit 3ceb3328664e3dfa1dbeb24bad45115e2f1970c4)
Refer to https://github.com/apache/activemq-artemis/pull/1139, for more info.

[1.x] ARTEMIS-1074 Acceptors/Connectors now start up when configured to use SSL and a password codec

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQMessage.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompUtils.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/security/SecurityTest.java

When populate-validated-user = true AMQP messages can cause exceptions.
This feature isn't particularly applicable to AMQP so this commit
eliminates the exception and leaves the AMQP messages untouched
even if populate-validated-user = true. In other words,
populate-validated-user + AMQP is not supported.

ARTEMIS-1092 Validated user + AMQP fix

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/TransportConstants.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyAcceptor.java
docs/user-manual/en/configuring-transports.md

By default Netty uses the write buffer high/low water mark to perform flow control while on the event loop.
I've added the configuration (+ default) of these values and the documentation that explain their purpose.
I've not changed too much the original default values defined by Netty to not impact the current tests and known behaviours around the Netty transport usage.

ARTEMIS-1095 Netty's WriteBufferWaterMark configuration via TransportConstants

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/Connection.java

It solve the OOM issue while under heavy load while:
- allowing the NettyConnection to perform a (configurable) weak form of backpressure on unbatched "big" messages
- allowing multiple (concurrent) clients to query the memory usage of the connection
- allowing batching without involving further copies of the data
- providing detailed memory load informations on OOM errors

ARTEMIS-1025 Improve flow control on NettyConnection

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpMessagePriorityTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveTest.java

Ensure that the header value for priority is read and returned in a form
that is scaled such that it won't cause an IndexOutOfBoundsException
from the QueueImpl priority array.  Adds some additional testing for
message priority support.

ARTEMIS-1097 Respect the message priority value in the AMQP message

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/message/AMQPMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpMessagePriorityTest.java

Fix the getUserID and getTimestamp methods in AMQPMessage to read and
return the correct values.  Adds some tests to cover these cases and
cleans up some others.

ARTEMIS-1101 Read the correct values for timestamp and user-id

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/SimpleFuture.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/SimpleFutureImpl.java
artemis-commons/src/test/java/org/apache/activemq/artemis/utils/SimpleFutureTest.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalBase.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalCompactor.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalTransaction.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/NIOJournalCompactTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/AlignedJournalImplTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/JournalAsyncTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/JournalImplTestBase.java

This is fixing an issue introduced on 4b47461f03a607b9ef517beb2a1666ffae43a2a7 (ARTEMIS-1114)
The Transactions were being looked up without the readLock and some of the controls for Read and Write lock
were broken after this.

ARTEMIS-1114 Avoid missing records after compacting

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpReceiver.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSender.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReceiverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSenderTest.java

On link attach we currently default out SenderSettleMode to MIXED which
while legal doesn't truly reflect what the client asked for. We instead
now update the link to reflect the mode requested by the client
Also add some tests to ensure that we always return the
ReceiverSettleMode as FIRST since we don't support SECOND.

ARTEMIS-1127 Match remote Sender and Receiver settle modes

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/ActiveMQChannelHandler.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/SharedEventLoopGroup.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/impl/netty/NettyConnectionTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/impl/netty/NettyConnectorTest.java

This cleans up the Netty implementation by replacing deprecated usage
and adds type parameters to raw types used.

Removes deprecated use and raw types

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/LastValueQueue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueFactoryImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQPluginRunnable.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQServerPlugin.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/HangConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/InterruptedLargeMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/client/TopicCleanupTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/amq/JmsResourceProvider.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/AmqpPluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/CorePluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MethodCalledVerifier.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MqttPluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/OpenwirePluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/StompPluginTest.java
tests/timing-tests/src/test/java/org/apache/activemq/artemis/tests/timing/core/server/impl/QueueImplTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/server/impl/QueueImplTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/server/impl/fakes/FakeQueueFactory.java

Adding a new ActiveMQServerPlugin interface to support adding custom behavior to the broker at certain events such as connection or session creation.  I know that 2.1.0 should be done soon so not sure if it is best to wait to merge this in for 2.2.0.
For now this is a good start but there will probably be additional hooks to add at some point.  There are some basic sanity tests to verify that the plugin methods are called but more in depth tests will come if we write some real plugins to ship with the broker.
Also one thing I want to spend some more time verifying is exception handling.  The plugin api has no checked exceptions so any exception that occurs in a plugin either needs to be handled by the plugin or be a runtime exception.  So I want to go through and verify that if unchecked …

ARTEMIS-898 - Adding Plugin Support

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java

Wrap the host added to the HTTP request headers with
IPV6Util.encloseHost to ensure that load balancers that reads the header
will have a valid IPv6 address.
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-1043

[1.x] [ARTEMIS-1043] Support IPv6 in NettyConnector

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ConfigurationUtils.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/ha/SharedStoreMasterPolicyConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/HAPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/SharedStoreMasterPolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ha/SharedStoreSlavePolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingBackupActivation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedStoreBackupActivation.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedStoreLiveActivation.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java
docs/user-manual/en/ha.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/SharedStoreDontWaitForActivationTest.java

Added a wait-for-activation option to shared-store master HA policies.
This option is enabled by default to ensure unchanged server startup behavior.
If this option is enabled, ActiveMQServer.start() with a shared-store master server will not return
before the server has been activated.
If this options is disabled, start() will return after a background activation thread has been started.
The caller can use waitForActivation() to wait until server is activated, or just check the current activation status.
(cherry picked from commit 6017e305d90664b4bf5b8f891e43514907df9a4b)
(cherry picked from commit 7aa50546b3dc6c012bd7d4118d82055ffd1e1226)

ARTEMIS-1112: Added wait-for-activation option to shared-store-master confg

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/SharedStoreDontWaitForActivationTest.java

There was a typo in this test that could cause it to fail.

ARTEMIS-1112: Fixed occasionally failing test

---

artemis-commons/src/main/java/org/apache/activemq/artemis/core/server/NetworkHealthCheck.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/qourum/SharedNothingBackupQuorum.java

Even if there is no address/url configured for the NetworkHealthCheck
an isolated backup will still fail-over potentially causing split-brain.

ARTEMIS-1154 isolated backup fails over

---

tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/transport/NettyTcpTransport.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/transport/NettyTransport.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/transport/NettyWSTransport.java

Need to configure the WS Handshaker in the test client's netty transport
with the same value given to the proton connection via setMaxFrameSize
so that incoming frames larger than the default 65535 over WS don't
trigger netty to fail the connection.

ARTEMIS-1160 AMQP test client should configure netty WS maxFrameSize

---

artemis-core-client-all/pom.xml
artemis-jms-client-all/pom.xml

To add ontop of the reduced-dependency.pom fix.
Clean up shaded jar
Ensure aggregated notice
Ensure correct license file,
remove noise from jgroups dependency (taken from infinispans shade config)
remove other loose ends.

ARTEMIS-1129: Fixing tests after client all

---

artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/Stomp.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompUtils.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/StompTest.java

Adds headers AMQ_SCHEDULED_DELAY and AMQ_SCHEDULED_TIME to STOMP
protocol handling to allow for delayed and scheduled time of a
message.  The AMQ_SCHEDULED_DELAY brings forward the same option
from the 5.x broker and the AMQ_SCHEDULED_TIME option adds a fixed
time of delivery alternative to match that of AMQP and others.

ARTEMIS-821 Add support for scheduled message for STOMP

---

docs/user-manual/en/configuration-index.md
docs/user-manual/en/using-AMQP.md

Update documents for new configuration toggle for 'amqp-use-core-subscription-naming '

ARTEMIS-1205: AMQP Shared Durable Subscriber - Document Update

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/ClusteredMessageCounterTest.java

Before sending of messages to server 0 begins, the test
should wait until consumer is registered at RemoteQueueBindingImpl
on server 0. Otherwise some messages may not be rebalanced
to server 1.

ARTEMIS-1250 ClusteredMessageCounterTest.testNonDurableMessageAddedWithPaging fails

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/OrderedExecutorFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/FileWrapperJournal.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/ServerSessionPacketHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQPacketHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationEndpoint.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterController.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/ExpireWhileLoadBalanceTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/FailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/reattach/MultiThreadRandomReattachTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/reattach/NettyMultiThreadRandomReattachTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/replicationflow/ReplicationFlowControlTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/JournalImplTestUnit.java

If replication blocked anything on the journal
the processing from clients would be blocked
and nothing would work.
As part of this fix I am using an executor on ServerSessionPacketHandler
which will also scale better as the reader from Netty would be feed immediately.

ARTEMIS-1269 Fixing blocked replication

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/OrderedExecutorFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/FileWrapperJournal.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/ServerSessionPacketHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQPacketHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationEndpoint.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterController.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/ExpireWhileLoadBalanceTest.java

If replication blocked anything on the journal
the processing from clients would be blocked
and nothing would work.
As part of this fix I am using an executor on ServerSessionPacketHandler
which will also scale better as the reader from Netty would be feed immediately.
(cherry picked from commit 52d49ea3a72f1d1b0f634d83b75b557c34d80e77)

1.x ARTEMIS-1269 Fixing blocked replication

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java

On completion of drain the response is not flushed and the
client can wait a few seconds before another broker task
flushes the work.  Flush the connection after updating the
linked as being drained.  Also perform the work with the
connection lock held to prevent conccurent update of proton
state.

ARTEMIS-1283 Fix delay on drained response

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/TransportConstants.java

Correct the logging id to correct matching id for level

ARTEMIS-1342: Support Netty Native KQueue on macOS - Logging fix

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRaUtils.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQResourceAdapter.java

Obtaining a BroadCastEndpointFactory instead of a JChannel to connect to JGroups to avoid issue and leak with JChannel lifecyle.

Chagning the way to interact with JGroups in the ResourceAdapter

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java

it would be good to add a removeAllMessages() JMX operation to clear all messages from the queue, to make it a little more intuitive in various JMX browsers (such as jconsole)
adding an new method to the external facing QueueControl interface, AFAIK that should not break anything.

ARTEMIS-1381 add JMX operation removeAllMessages() to the queue

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java

- account for potential to be negative due to using nanoTime derived values
- add some other edge case protections to avoid task ceasing in error

ARTEMIS-1434: update handling of tick deadline values

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQClientProtocolManagerFactory.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/ClientProtocolManagerFactory.java
artemis-protocols/artemis-hqclient-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/hornetq/client/HornetQClientProtocolManagerFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ActiveMQServerSideProtocolManagerFactory.java
artemis-service-extensions/src/main/java/org/apache/activemq/artemis/service/extensions/xa/recovery/XARecoveryConfig.java

add the adaptTransportConfiguration() method to the
ClientProtocolManagerFactory so that transport configurations used by
the ClientProtocolManager have an opportunity to adapt their transport
configuration.
This allows the HornetQClientProtocolManagerFactory to adapt the
transport configuration received by remote HornetQ broker to replace the
HornetQ-based NettyConnectorFactory by the Artemis-based one.
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-1431
PR for master branch: https://github.com/apache/activemq-artemis/pull/1546

[ARTMIS-1431] Adapt transport configuration in ClientProtocolManagerFactory

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/journal/PerfJournal.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/util/SyncCalculation.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/journal-buffer-settings.txt
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/ping-settings.txt
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/ActiveMQClient.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/AbstractSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/mapped/MappedSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/nio/NIOSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/test/java/org/apache/activemq/artemis/core/io/JournalTptBenchmark.java
artemis-journal/src/test/java/org/apache/activemq/artemis/core/io/SequentialFileTptBenchmark.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMConnector.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
docs/user-manual/en/configuration-index.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/AIOUnbuferedJournalImplTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/MappedImportExportTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/MappedJournalImplTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/MappedSequentialFileFactoryTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/MappedUnbuferedJournalImplTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/ValidateTransactionHealthTest.java

- it is now possible to disable the TimedBuffer
- this is increasing the default on libaio maxAIO to 4k
- The Auto Tuning on the journal will use asynchronous writes to simulate what would happen on faster disks

ARTEMIS-1452 Improvements to IO parameters and options

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/reader/MessageUtil.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/cluster/TopicClusterTest.java

In a cluster if a node is shut down (or crashed) when a
message is being routed to a remote binding, a internal
property may be added to the message and persisted. The
name of the property is like _AMQ_ROUTE_TOsf.my-cluster*.
if the node starts back, it will load and reroute this message
and if it goes to a local consumer, this property won't
get removed and goes to the client.
The fix is to remove this internal property before it
is sent to any client.

ARTEMIS-1227 Internal properties not removed from messages

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRALogger.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQActivationSpec.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQMessageHandler.java

* initialize ActiveMQActivationSpec#shareSubscriptions to false
* i18n of the exception thrown by ActiveMQMessageHandler if it is not
possible to create a non-shared subscriber
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-1475
PR for master branch: https://github.com/apache/activemq-artemis/pull/1603

[1.x] [ARTEMIS-1475] Fix NPE in ActiveMQMessageHandler#setup

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/Topology.java

If the current node has no connector to Live, it is better
to update it from older message than to have none.

ARTEMIS-1484 Live's topology update may be ignored

---

artemis-commons/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQScheduledComponent.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/critical/CriticalAnalyzerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java

I had moved the initialization of the thread pools for that..
I also have changed the CrticialAnalyzer to use the same pools as part of this

ARTEMIS-1447 Reuse thread pools on JDBC Locks

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/ThreadDumpUtil.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java

Improved implementation of ActiveMQTestBase.threadDump which uses ThreadMXBean
for getting information about threads including locks and deadlocks.
Sample of the thread dump
```
Complete Thread dump  - fired by MultiThreadRandomReattachTestBase::runTestMultipleThreads (AMQ119014: Timed out after waiting 30,000 ms for response when sending packet 105)
"Thread-4 (ActiveMQ-scheduled-threads)" Id=183 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2dc00c99
at sun.misc.Unsafe.park(Native Method)
-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2dc00c99
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.jav …
```

ARTEMIS-1485 ActiveMQTestBase.threadDump should print information about locks and deadlocks

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java

When the execution of code jumps out of the while cycle,
it should check whether the blocking-call-timeout expired or not.
If no, ActiveMQUnBlockedException should be thrown
instead of ActiveMQConnectionTimedOutException.

ARTEMIS-1507 ActiveMQConnectionTimedOutException is thrown even though no timeout expired

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/PrefixUtil.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/VersionedStompFrameHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ServerSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AddressInfo.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/HierarchicalRepository.java
docs/user-manual/en/protocols-interoperability.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/management/OpenWireManagementTest.java

Openwire clients create consumers to advisory topics to receive
notifications. As a result there are internal queues created
on advisory topics. Those consumer shouldn't be exposed via
management APIs which are used by the Console
To fix that the broker doesn't register any queues from
advisory addresses.

ARTEMIS-1365 Advisory consumers listed in Console

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/ClientProducer.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientProducerImpl.java

https://issues.apache.org/jira/browse/ARTEMIS-1517 Clarify SendACK versus confirmationWindowSize

ARTEMIS-1517 Clarify SendACK versus confirmationWindowSize

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java

Use Map<String, Object> to access the ApplicationProperties section
which is the spec defined type for that section.  This will prevent
breakage should proton-j be updated to reflect that in the definition of
that class.

ARTEMIS-1544 Use the proper types when accessing ApplicationProperties

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/TransportConstants.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ssl/CoreClientOverTwoWaySSLTest.java

Previously when configuring a connectionFactory by URI this property was
ignored

ARTEMIS-1538: Allow trustAll to apply from a connection URI

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverter.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSLVQTest.java

Add support for LVQ, using the same property key as core "_AMQ_LVQ_NAME"
Update current LVQ test case to correctly test OpenWire LVQ.

ARTEMIS-1550 - Support LVQ for OpenWire

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/TypedProperties.java

TypedProperties::putByteProperty contains a duplicate TypedProperties::checkCreateProperties: it needs to be removed

ARTEMIS-1615 Duplicate TypedProperties::checkCreateProperties

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQServerPlugin.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/AmqpPluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/CorePluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MethodCalledVerifier.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MqttPluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/OpenwirePluginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/StompPluginTest.java

Adds callbacks to ActiveMQServerPlugin for binding add and remove events

ARTEMIS-1647 - Add plugin support for binding creation and removal

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java

Check for null on isMaskPassword, seems this regressed in bb84f679363f62e8b2663f63bf23f04133de481d change for ARTEMIS-1600

ARTEMIS-1655 Fix TransportConfiguration encode failing

---

artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/impl/JMSServerManagerImpl.java

Jira: https://issues.apache.org/jira/browse/ARTEMIS-1670
The proposed fix will check whether the Queue is null or not when trying to delete it from it's Thread.

[ARTEMIS-1670] NPE was found in when dropping durable subscriptions from a topic

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/actors/ArtemisExecutor.java
artemis-junit/src/test/java/org/apache/activemq/artemis/junit/ActiveMQConsumerResourceTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageCursorProviderImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageSubscriptionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java

ARTEMIS-1700 Fixed deadlock in paging state

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml
artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/XMLUtil.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileXIncludeConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-xinclude-config-address-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config-addresses.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config-security-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config.xml
artemis-tools/src/test/resources/artemis-configuration.xsd
docs/user-manual/en/configuration-index.md

Support XML standard XInclude thus allowing splitting of the broker.xml
Added test cases with split out config using include.

ARTEMIS-1661 Support splitting of broker.xml

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java

Check for AMQSession being null before handling various TX state checks
in order to ensure the correct errors are thrown and TX rollback is
handled properly.

ARTEMIS-1712 Add additional null check in TX rollback handler

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/amq/ConnectionErrorSocketCloseTest.java

To prevent a socket from hanging open by a bad client the broker should
make sure to stop the transport if a connection attempt fails by an
OpenWire client

ARTEMIS-1727 - Make sure transport is stopped on failed OpenWire connection

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingLiveActivation.java
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java

This is replacing #1940 
#1940 will be closed when this one is merged.

ARTEMIS-1737 Fixing WebServer stopped

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/ServerSessionPacketHandler.java
tests/compatibility-tests/src/main/resources/oldAddressSpace/artemisServer.groovy
tests/compatibility-tests/src/main/resources/oldAddressSpace/receiveMessages.groovy
tests/compatibility-tests/src/main/resources/oldAddressSpace/sendMessagesAddress.groovy
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/OldAddressSpaceTest.java

When creting a durable topic subscription using the Artemis 1.x JMS
client library.  The client sends a QueueQuery to the server to see if
the durable subsciption queue already exists.  The broker then performs
some transformation of the queue addresses to suit the 1.x naming
scheme.  However, if the queue does not already exist the transform is
attempted on a null string causing NPE.  To fix we simply check that the
result return isExists=true.

ARTEMIS-1753 Prevent NPE on 1.x Client Topic Sub

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java

Now the logging information is not printed in the stdout.

ARTEMIS-375:When use ./artemis data exp, the xml printed to stdout with logging infomation

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java

Jira: https://issues.apache.org/jira/browse/ARTEMIS-1770

[ARTEMIS-1770] Log warning instead of stacktrace while shutdown

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/CoreNotificationType.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ManagementHelper.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQServerPlugin.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/impl/NotificationActiveMQServerPlugin.java
docs/user-manual/en/broker-plugins.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/NotificationTest.java

Adds a new plugin that will support sending new types of notifications
for broker events which will allow enhanced broker monitoring

ARTEMIS-1799 - Add a NotificationActiveMQServerPlugin

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java

The queue metrics were being decremented improperly because on iteration
over the cancelled scheduled messages because the flag for fromMessageReferences was not
set to false. Setting the flag to false skips over the metrics update
which is what we want as the scheduled messages were never added to the
message references in the first place so the metrics don't need updating

ARTEMIS-1800 - Fix metrics decrement on scheduled message cancel

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/AbstractProducerCreditsImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/AsynchronousProducerCreditsImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientProducerCreditManager.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientProducerCreditManagerImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientProducerCreditsImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientProducerFlowCallback.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQSessionContext.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/SessionContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/uri/ClusterConnectionConfigurationTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/bridge/BridgeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/ClusterConnectionConfigTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/ClusterTestBase.java

Issue: https://issues.apache.org/jira/browse/ARTEMIS-1776
Currently the flow control on the Bridge is based on back pressure only, through Netty writeable interfaces.
If the user selected a positive producerWindowSize the Queue may block while the Processing is happening. What could lead to distributed deadlocks on the Bridge.
These changes avoids that possibility.

[ARTEMIS-1776] - Implement asynchronous flow control on bridge and clustered bridge

---

README.md

Some of my colleagues suggested it would be useful to have the Travis CI build label right when accessing the project page.

Adds the Travis CI build status label on the README

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java

This is fixing org.apache.activemq.artemis.tests.integration.ssl.CoreClientOverOneWaySSLKerb5Test#testOneWaySSLWithGoodClientCipherSuite

ARTEMIS-1839 NettyConnector was ignoring sniHost

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/Message.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/utils/PrefixUtil.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompUtils.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/VersionedStompFrameHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ServerSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/StompTest.java

This is a regression caused by the fix for ARTEMIS-1794.

ARTEMIS-1834 don't alter STOMP 'destination' header when using prefix

---

artemis-tools/src/test/resources/artemis-configuration.xsd

Just correcting (reverting) an accidental doc change i had made a while back, for auto-delete-addresses, which was intended for config-delete-addresses.

NO-JIRA - XSD Doc fix

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/HAPolicyConfigurationTest.java

When database persistence and no shared store option is being used,
Artemis is choosing to use InVMNodeManager, that is not providing
the same behaviour of FileLockNodeManager.

ARTEMIS-1876 InVMNodeManager shouldn't be used if no JDBC HA is configured

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicationManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingLiveActivation.java

After sending pages, the thread will hold the storage manager write lock and send synchronization finished packet(use the parent thread pool) to the backup node. At the same time, thread pool is full bcs they are waiting for the storage manager read lock to write the page or journal, leading to replication starting failure. Here we use io executor to send replicate packet to fix thread pool starvation problem.

ARTEMIS-1891 Sending synchronization finished packet starves when thread pool is full

---

artemis-junit/src/main/java/org/apache/activemq/artemis/junit/Wait.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ProtonHandler.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpMaxFrameSizeTest.java

Fix for https://issues.apache.org/jira/browse/ARTEMIS-1934 with some tests, plus improvements for the existing max frame size tests.

ARTEMIS-1934: fix handling/accounting of sent AMQP connection data

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpLargeMessageTest.java

See https://issues.apache.org/jira/browse/ARTEMIS-1940 for details.

ARTEMIS-1940: premature release of pooled buffers during send can cause AMQP connection failures

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/journal-buffer-settings.txt

jira :- https://issues.apache.org/jira/browse/ARTEMIS-1944

[ARTEMIS-1944] Typo mistake in broker.xml at journal-buffer-timeout explanation

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

@clebertsuconic 
Here's a slight alternative option to your pr (https://github.com/apache/activemq-artemis/pull/2209) i took the fixes for the server and control, but in the queueimpl I wanted to keep away from having the redistributor in the list (reason being later where want to try make the dispatch policies more pluggable it makes it very hard)
Also interestingly applying the same change that Franz has done for CPU here, but for the redistributor fixes many of the redistributor issues, essentially it was failing because it ended up in a spin.
https://github.com/apache/activemq-artemis/pull/2203
One case in the messageredistributiontest though still fails (testRedistributionWithMessageGroups), im looking into why it might, but if you can spot please do tell.
If you need master fixed …

ARTEMIS-856 Test fixes - Alternative

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

Don't increment the pos if redistributor. causes pos to be > size thus index out of bounds when getting the consumer on next loop.

ARTEMIS-856 Fixing ScaleDownTest

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java

Fill the session's metadata in JSON properties instead of serializing it
as an opaque String.
JIRA: https://issues.apache.org/jira/browse/ARTEMIS-1947

[ARTEMIS-1947] Session metadata in session management operation

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/SimpleStringTest.java

Set the int to Integer.MAX_VALUE thus if the len check is not done before byte[] initialization the test would blow with an OOM.

ARTEMIS-1482 Enhance test to ensure len check is done before byte[] init

---

artemis-protocols/artemis-amqp-protocol/pom.xml
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContext.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContextTest.java

Fixes handling of aborted deliveries to ensure the receiver processes the delivery (and any subsequent ones) appropriately. Unit tested only since Proton-J cant send aborted deliveries, though I have also verified it with modified client (slowed down) sending from client-> Dispatch -> Artemis and back and killing the client connection mid-send.
I'd like this backported to 2.6.x also.

ARTEMIS-2027: handle aborted AMQP deliveries

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallbackTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSenderTest.java

Ensure the broker looks at local receiver credit when checking for
credit top off threshold and then do a proper top off back to the high
water mark to sync with how client receivers manage their credit.

ARTEMIS-2057 Fix runaway credit grants

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/RedeployTest.java
tests/integration-tests/src/test/resources/reload-queue-filter-updated.xml
tests/integration-tests/src/test/resources/reload-queue-filter.xml

Avoids issue with other tests that could persist same queue name, making intermittent failure.

NO-JIRA rename queue in test to avoid collision

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/SimpleString.java

Currently we get.
java.lang.IndexOutOfBoundsException: **null**
at org.apache.activemq.artemis.api.core.SimpleString.readSimpleString(SimpleString.java:183)
at org.apache.activemq.artemis.api.core.SimpleString$ByteBufSimpleStringPool.create(SimpleString.java:584)
....
Should be
java.lang.IndexOutOfBoundsException: **Error reading in simpleString, length=YYY is greater than readableBytes=XXX**
at org.apache.activemq.artemis.api.core.SimpleString.readSimpleString(SimpleString.java:183)
at org.apache.activemq.artemis.api.core.SimpleString$ByteBufSimpleStringPool.create(SimpleString.java:584)
...

NO-JIRA - Update SimpleString to give a more useful error message

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpExpiredMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSTransactedRedeliveryBugTest.java

Once a re-encode of the message is done the buffer is not being marked
as valid and so subsequent checks on the buffer are all assuming the
message data is not valid and re-encoding over and over.  This can lead
to poor performance in some cases and corrupted data in others.

ARTEMIS-2082 Reset buffer valid flag after re-encoding the message

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/ScaleDownTest.java

Empty space removed that produced a checkstyle error.
(cherry picked from commit 536edc05c435e31f095a283c44fe476846ef68cb)

NO-JIRA: ScaleDownTest checkstyle error fix

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/impl/netty/NettyConnectorTest.java

Given that NettyConnector::createConnection isn't happening on the
channel's event loop, it could race with a channel close event, that
would clean the whole channel pipeline, leading to a NPE while
trying to use a configured channel handler of the pipeline.

ARTEMIS-2093 NPE thrown by NettyConnector::createConnection

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/TypedProperties.java
artemis-commons/src/test/java/org/apache/activemq/artemis/utils/TypedPropertiesConcurrencyTest.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQJMSProducer.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQMapMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/jms/ServerJMSMapMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java

Add Concurrency Test to expose concurrency errors seen in logs.
Add Fix to ensure TypedProperties to ensure threadsafety
Add forEach and forEachKey to allow for provide a thread safe way of iterating through keys and values, without needing to duplicate the collection.
Add getMapNames method to remove code duplication and to ensure thread safe

ARTEMIS-2095 - Typed Properties ThreadSafety

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/runnables/AtomicRunnable.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContext.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallbackTest.java

GlobalDiskFullTest was broken before this fix.
Basically when using multiple addresses over a session you would miss flow credits on all your producers except to the first one
that ran out of credit.

ARTEMIS-1898 Proper fix on AtomicRunnables and avoiding leaks

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java

A synchronization block was missed during the AMQP refactoring.
This could impact use-cases involving diverts, cluster bridges, and
multiple concurrent consumers.

ARTEMIS-2136 synchronize copy constructor

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/SequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/mapped/MappedSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/mapped/TimedSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/nio/NIOSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/AbstractJournalUpdateTask.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/fakes/FakeSequentialFileFactory.java

Compaction is now reusing direct ByteBuffers on both
reading and writing with explicit and deterministic
release to avoid high peak of native memory utilisation
after compaction.

ARTEMIS-1996 MappedSequentialFileFactory may cause DirectByteBuffer off-heap memory leaks

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/PagedReferenceImpl.java

Transaction id of the non transactional paged message is -1. When we acknowledge the message, we judge transactionID < 0 and get paged message. The page where message resides  maybe retrieved causing performance degradation. So we only need to get paged message if transactionID < -1 instead of 0.
jstack shows:
"Thread-42 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@55b0dcab)" #108 prio=5 os_prio=0 tid=0x00007f1b741c5000 nid=0xa9b03 waiting for monitor entry [0x00
007f1c3c5f7000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.apache.activemq.artemis.core.paging.cursor.impl.PageCursorProviderImpl.getPageCache(PageCursorProviderImpl.java:136)
- waiting to lock <0x00000003c6c65e18> (a org.apache.activemq.artemis.utils.SoftValueHashMap)
at …

ARTEMIS-2158 don't get pagedMessage if it's nontransactional

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/DBOption.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingManagerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/BindingsImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/QueueConfig.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/PostOfficeJournalLoader.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ScaleDownHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/files/FileMoveManagerTest.java
tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/region/policy/DestinationProxy.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/GlobalPagingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/replication/ReplicationTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/BindingsImplTest.java

This is an alternative version of https://github.com/apache/activemq-artemis/pull/2401 that:
- disable paging on management addresses
- take care to avoid NPE on any uses of a management address `PagingStore`
- management messages are not counted on `PagingManager::getGlobalSize` (given that no `PagingStore` exists for a management address)
- take care to adjust addresses metrics on a management address

ARTEMIS-1710 Allow management msgs to exceed global-max-size limit

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/transaction/ProtonTransactionHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/protocol/SessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMXManagementTest.java

With AMQP protocol when some messages are received in a transaction,
calling JMX QueueControl.listDeliveringMessages() returns empty list
before the transaction is committed.

ARTEMIS-1850 QueueControl.listDeliveringMessages returns empty result

---

pom.xml

With the current Maven config, the maven-source-plugin is executed twice, this results in the sources-jars being attached twice which leads the deploy goal in trying to upload the same sources jars twice to the repository. This slows down the build process and also fails on repositories that disallow updating of existing artifacts. 
Additionally the "jar" goal is now replaced with "jar-no-fork" which prevents the maven life cycle being executed twice too.

NO-JIRA Prevent maven-source-plugin being executed twice

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java

Potential race condition. This assignment to writableBuffer is visible to other threads before the subsequent statements are executed.

NO-JIRA fix writableBuffer so that its only visible after sub statements

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolManager.java

Prevent a NullPointerException if no connection by the given clientId is found on the cache of stored sessions

ARTEMIS-1952 NPE logged at warn if MQTT subscriber disconnects abruptly

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFullyQualifiedNameTest.java

this was reverted previously on commit f4436a9f72afeb8117ecd6e377df8198eeec9aa3.
It seems it is ok after further changes into FQQN, so this is being reapplied

ARTEMIS-2229 turns out a valid bug. So restore the fix commit.

---

tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/server/impl/QueueImplTest.java

This test fails occasionally because the queue's delivering thread
may interference with the consumer's iterator during consumers adding.
The result is that the first of the 2 consumers may get iterated
twice and therefore the messages received by the 2 consumers are
not even.
Tha change puts the message add after the consumer add so that
the delivering thread only kicks off after consumers are all added
and messages should be evenly distributed to both consumers.

NO-JIRA Fix QueueImplTest#testRoundRobinWithQueueing

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/DelayInterceptor.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/FailoverTest.java

The test may fail if the live crashes too soon and the
message is directly sent to backup and the expected
blocking send will never happen.
To fix that a wait is added to ensure the message
is sent to the live (and intercepted) before
crashing the live.

NO-JIRA Fix FailoverTest#testForceBlockingReturn

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java

This is fixing these tests:
- org.apache.activemq.artemis.tests.integration.paging.PagingOrderTest#testPagingOverCreatedDestinationQueues
- org.apache.activemq.artemis.tests.integration.paging.PagingOrderTest#testPagingOverCreatedDestinationTopics
No additional tests are needed as this change is covereted by the current testsuite

ARTEMIS-2329 AddressSettings inconsistence on decoding

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/Connection.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImplTest.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/impl/invm/InVMConnection.java

When connection is dead, the StompSession may deliver a message and if AUTO-ACK it would ack and lose the message

ARTEMIS-2333 Applying proper fix on Stomp delivery

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

OpenWireGroupingTest::testGrouping is fixed after this change as it was intermittently failing

ARTEMIS-2335 Fixing delivery logic for message group on negative attemps

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionBridge.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/DivertImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpBridgeClusterRedistributionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/bridge/BridgeTest.java

ARTEMIS-2361 Bridge should make a copy of messages

---

artemis-hawtio/artemis-console/pom.xml
pom.xml

CVE-2018-10237 guava: Unbounded memory allocation in AtomicDoubleArray
and CompoundOrdering classes allow remote attackers to cause a denial
of service.

ARTEMIS-2359 Upgrade to Guava 24.1

---

artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/NoFilesBehind.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/divert/DivertTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/server/JMSServerStartStopTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/JournalFileSizeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/SuppliedThreadPoolTest.java
tests/integration-tests/src/test/resources/broker-logging-plugin-wrong.xml
tests/integration-tests/src/test/resources/broker-logging-plugin.xml
tests/integration-tests/src/test/resources/broker-plugins-config.xml
tests/integration-tests/src/test/resources/reload-queue-filter-updated.xml
tests/integration-tests/src/test/resources/reload-queue-filter.xml
tests/integration-tests/src/test/resources/reload-queue-routingtype-updated.xml
tests/integration-tests/src/test/resources/reload-queue-routingtype.xml
tests/integration-tests/src/test/resources/server-start-stop-config1.xml

We had to fix a few cases where data folder was being created outside of the ./target output.
This is just to avoid re-ocurrence of that.

ARTEMIS-2367 Adding rule to avoid files leaking on the main folder

---

pom.xml

Guava 24.1.1 is the correct version to fix https://github.com/apache/activemq-artemis/pull/2687.

ARTEMIS-2383 Upgrade to Guava 24.1.1

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/Page.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PagingStoreImplTest.java

The last page file might be incomplete if broker crashes or the disk is damaged. After broker is up, we keep writing this incomplete page file. If the cache of the file is evicted, we read this file to deliver messages which we would lose messages written after broker up.

ARTEMIS-2425 Message loss due to writing incomplete page file

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageCursorProviderImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/Page.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingTest.java

When live page cache is cleared by gc, partially written page cache would be returned causing subsequent written messages lost.

ARTEMIS-2430 Avoid data loss when live page cache evicted

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/NodeManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/FileLockNodeManager.java

Certain devices or file systems won't support record level locking.
For that reason I am changing FileLockNodeManager to use separate files (one for each position) instead of using tryLock(position);
A good example for this would be cephFS where channel.tryLock or channel.tryLock works but it fails at a record level.

ARTEMIS-2441 Separate Lock Files

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/SimpleOpenWireTest.java

When an openwire client closes the session, the broker doesn't
clean up its server consumer references even though the core
consumers are closed. This results a leak when sessions within
a connection are created and closed when the connection keeps open.

ARTEMIS-2493 OpenWire session close doesn't cleanup consumer refs

---

artemis-distribution/pom.xml
artemis-distribution/src/main/assembly/dep.xml
pom.xml

This is needed to aid some lift and shift migration from activemq5 where non-java clients have support for older openwire protocols.

ARTEMIS-2509 Add some basic support for legacy openwire

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingManagerImpl.java

The LocalMonitor tick log is very useful to establish a "heartbeat" log
statement. It is moved into its own logger from PagingManager logger,
which is too verbose to leave activated indefinitely in production.

ARTEMIS-2512 Move the LocalMonitor tick log

---

artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/LDAPLoginModule.java
docs/user-manual/en/security.md

Active Directory servers are unable to handle referrals automatically. This causes a PartialResultException to be thrown if a referral is encountered beneath the base search DN, even if `Context.REFERRAL` is set to `ignore`. This PR adds an option to ignore these exceptions, allowing login to proceed with the query results received before the exception was encountered.
This is the same solution used by Spring. See https://github.com/spring-projects/spring-ldap/blob/master/core/src/main/java/org/springframework/ldap/core/LdapTemplate.java#L379-L387
Issue: https://issues.apache.org/jira/browse/ARTEMIS-2535

ARTEMIS-2535 Add ignorePartialResultException option to LDAPLoginModule

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/page-sync-settings.txt
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/DefaultsFileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/en/configuration-index.md
docs/user-manual/en/paging.md

Add the config parameter `page-sync-timeout` to set a customized value,
because if the broker is configured to use ASYNCIO journal, the timeout
has the same value of NIO default journal buffer timeout ie 3333333.

ARTEMIS-2466 PageSyncTimer::timeSync isn't configurable using ASYNCIO

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSMessageConsumerTest.java

Add unit test
Add fix to clear clientids when server is stopped.

ARTEMIS-2547 fix AMQP Client reconnect fails on broker stop start

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/ConnectionView.java

Reduce number of calls to server.getSessions(connection.getID().toString()) when rendering connections list.

ARTEMIS-2570 Improve performance of ConnectionView

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/ThreadLeakCheckRule.java

Add the thread with name `MemoryMXBean` as expected on IBM JDK.

ARTEMIS-2577 Thread leak test failure with IBM JRE

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/ThreadLeakCheckRule.java

Add an exception for the thread with name `MemoryMXBean`.

ARTEMIS-2593 Thread leak test failure with OpenJ9 JVM

---

artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/NoProcessFilesBehind.java

This is to make it possible to identify what test is leaking files whenever that is happening.
That is because future tests will report the leaks, and it's difficult to identify where it happened.
Also i'm changing NoProcessFilesBehind to show the getOpenFD propertly

NO-JIRA Adding test name into temporary folder name directory

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java

This happened when JournalStorageManager.startReplication and PageStore.cleanup were called between multiple threads.

ARTEMIS-2603 Deadlock between pageStore.getCurrentID and page.cleanup

---

artemis-distribution/pom.xml
artemis-distribution/src/main/assembly/dep.xml
pom.xml

Add required dependency org.apache.geronimo.specs:geronimo-jaspic_1.0_spec.

ARTEMIS-2601 Update jetty version to 9.4.26.v20200117

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/FederationStreamConnectMessage.java

This fixes the following compiler warning that is reported in Travis builds:
```java
/home/travis/build/apache/activemq-artemis/artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/FederationStreamConnectMessage.java:151: warning: non-varargs call of varargs method with inexact argument type for last parameter;
return (FederationPolicy) Class.forName(clazz).getConstructor(null).newInstance();
cast to Class<?> for a varargs call
cast to Class<?>[] for a non-varargs call and to suppress this warning
```

NO-JIRA Fix compiler warning in FederationStreamConnectMessage

---

artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java

Fixes compiler warning "Unnecessary cast from String to String".

NO-JIRA Fix compiler warning in FileConfigurationParserTest

---

artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java

Fixes Javadoc warnings "Javadoc: Exception Exception is not declared" and "Javadoc: Exception InterruptedException is not declared"

NO-JIRA Fix Javadoc warning in ActiveMQTestBase

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQServerConsumerPlugin.java

Fixes Javadoc warning "Javadoc: Missing closing brace for inline tag"

NO-JIRA Fix Javadoc @link syntax in ActiveMQServerConsumerPlugin

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/PostgresLargeObjectManager.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/PostgresSequentialSequentialFileDriver.java
artemis-jdbc-store/src/test/java/org/apache/activemq/artemis/jdbc/store/file/JDBCSequentialFileFactoryTest.java
artemis-jdbc-store/src/test/java/org/apache/activemq/artemis/jdbc/store/file/PostgresLargeObjectManagerTest.java

Issue: 
The BLOB manipulation is done using PostgreSQL internal classes starting from PGConnection. This leads to ClasCastExceptions if the connection is wrapped in a pool or if the driver is in a different classloader (WildFly).
Fix: 
unwrap the connection and if the PostgreSQL classes are not directly available uses reflection to manipulate the BLOBs.
Jira: https://issues.apache.org/jira/browse/ARTEMIS-2626
Supersedes https://github.com/apache/activemq-artemis/pull/2948

[ARTEMIS-2626]: Postgresql Journal implementation requires the jdbc driver to be in the same classloader

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagedMessage.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageSubscriptionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/Page.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagedMessageImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/wireformat/ReplicationPageWriteMessage.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageReaderTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/paging/AmqpPageReaderTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/paging/AmqpPagingTest.java

There is no guarantee that the encodeSize size is the same in AMQP right after read.
As the protocol may add additional bytes right after decoded such as header, extra properties.. etc.

ARTEMIS-2662 Using previously stored encodeSize on page record offset

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpDeliveryAnnotationsTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReceiverPriorityTest.java

Fixes another couple races within the tests leading to sporafic failures:
The JMX checks of the queue count need a Wait to repeat where needed, as they aren't necessarily visible by the time the send returns.
The AMQP test clients recieveNoWait is a simple poll of a local queue, so there is no guarantee a message would have arrived at a consumer just because its producer send completed, a timed receive attempt should be used.

ARTEMIS-2659: address some more sporadic test failures

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ActiveMQBuffer.java
artemis-commons/src/main/java/org/apache/activemq/artemis/core/buffers/impl/ChannelBufferWrapper.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/ByteUtil.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientConsumerImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/CompressedLargeMessageControllerImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/LargeMessageControllerImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java

Netty's `UnreleasableByteBuf::readBytes(int length)` allocates a direct `ByteBuf` without `Cleaner` that can leak and cause OOM on `ChannelBufferWrapper::readBytes(final int length)`

ARTEMIS-2785 io.netty.util.internal.OutOfDirectMemoryError during uncompress

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/codec/PersistentQueueBindingEncoding.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/PostOffice.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/RedeployTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/resources/reload-empty.xml
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/server/impl/fakes/FakePostOffice.java

Queue settings are reset to their default values upon broker.xml reload ONLY.
Regular calls to PostOfficeImpl#updateQueue are no longer affected.

ARTEMIS-2797 Fixing redeploy mechanism

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/TransientQueueManagerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/TransientQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/jms2client/SharedConsumerTest.java

I couldn't reproduce this with a test, but static code analysis led me
to this solution which is similar to the fix done for ARTEMIS-2592 via
e397a177967bcf431b9fa82463a61b152ba82fb0.

ARTEMIS-2881 deadlock when destroying q and depaging

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/remoting/ReconnectTest.java

While handling a re-establish connection on failover it can happen that the client can connect to the broker and re-establish a connection, but while reattaching all sessions to the new connection another connection loss can happen and there the failover fails without any possibility to recover on its own.

ARTEMIS-2875 - Failed to handle re-establish connection failover

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpAnonymousRelayTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSMessageProducerTest.java

Inspects messages sent via anonymous-producers for routing type details to use in auto-creation of the appropriate type of address/queues, instead of just the address name (similar to the additional terminus detail that can be considered when fixed-destination senders are in used). Adds or enhances various tests around auto-creation and anonymous producers.
More detail at https://issues.apache.org/jira/browse/ARTEMIS-2910

ARTEMIS-2910: consider routing type annotations during auto-creation

---

artemis-distribution/src/main/assembly/dep.xml
artemis-features/src/main/resources/features.xml
artemis-jdbc-store/pom.xml
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/JDBCConnectionProvider.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/storage/DatabaseStorageConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JDBCJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jdbc/store/journal/JDBCJournalTest.java

It add additional required fixes:
- Fixed uncommitted deleted tx records
- Fixed JDBC authorization on test
- Using property-based version for commons-dbcp2
- stopping thread pool after activation to allow JDBC lease locks to release the lock
- centralize JDBC network timeout configuration and save repeating it
- adding dbcp2 as the default pooled DataSource to be used

ARTEMIS-2823 Use datasource with JDBC store db connections fixes

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/AbstractJDBCDriver.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/JDBCConnectionProvider.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/storage/DatabaseStorageConfiguration.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java

This commit is fixing:
- a missing commit that can make leak a connection
- restricting default specific commons-dbcp2 to the default data source
- setting poolPreparedStatements true by default
- configured embedded Derby to be in-memory to speedup tests

ARTEMIS-2955 commons-dbcp2 performance issue with Derby Embedded DBMS

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/logger/ActiveMQAMQPProtocolLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-tools/src/test/resources/artemis-configuration.xsd
docs/user-manual/en/amqp-broker-connections.md
examples/features/broker-connection/amqp-receiving-messages/src/main/resources/activemq/server0/broker.xml
examples/features/broker-connection/amqp-sending-messages/src/main/resources/activemq/server0/broker.xml
examples/features/broker-connection/amqp-sending-overssl/src/main/resources/activemq/server0/broker.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/QpidDispatchPeerTest.java
tests/integration-tests/src/test/resources/QpidRouterPeerTest-qpidr.conf

- Adding a paragraph about addressing and distinct queue names
- Renaming match on peers, senders and receivers as "address-match"

ARTEMIS-2937 Documentation improvements

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/LargeMessageTest.java

This is to avoid shutting down the server on a critical failure in case the message is a few bytes shy
from beyond the max buffer size.
This will prevent the issue.

ARTEMIS-3007 Checking if a message becomes large during copy

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageTest.java

Initialize the JMS expiration with the value calculated during the scan
of the AMQP message to avoid a different value for each conversion based
on System.currentTimeMillis() and ttl.

ARTEMIS-3118 Fix the expiration on converting from AMQP to core

---

.github/workflows/build.yml

- Builds the examples using the release profile on JDK8, as the Travis job does.
- Build the examples on JDK11+ using the -Pexamples,noRun profiles for equivalent build (release profile requires JDK8), which the Travis build doesnt do.
- Adds a workflow_dispatch trigger, allowing manual start of a new test runs (on any branch), without overwriting all the previous run logs like using the 'rerun all jobs' button within a particular run result.

NO-JIRA: GHA workflow improvements

---

artemis-protocols/artemis-mqtt-protocol/pom.xml

This repo is no longer operative. See
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
for more info. All dependencies are in Maven Central.

ARTEMIS-3182 remove defunct repo

---

pom.xml

According to the [postgresql documentation](https://jdbc.postgresql.org/documentation/faq.html#42-is-not), the 42.x.x releases are not a rewrite of the driver, are not using a new architecture, nor are using something special, they are the continuation of the same driver following a better versioning policy.

ARTEMIS-3199 Upgrade postgresql to 42.2.19

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
docs/user-manual/en/address-model.md
docs/user-manual/en/config-reload.md
docs/user-manual/en/configuration-index.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/divert/DivertTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java

This is 2 commits, the first is a bug around persisting diverts the second an enhancement to configure deleting when removed the configuration similar to how config-delete-queue/addresses works.

Divert fix

---

artemis-hawtio/activemq-branding/src/main/webapp/plugin/css/activemq.css

In the broker diagram, the icons for InternalAddress and InternalQueue are the same, as they each have the default style.
This PR explicitly assigns the same border colour as Address/Queue, but still leaves the fill colour white/transparent.
the new result:
as produced by the code from this branch (and configuring a cluster so that there are actually internal objects)
previously both were same colour:
See also https://issues.apache.org/jira/browse/ARTEMIS-3256

ARTEMIS-3256 internalqueue and internaladdress get their own color in the broker diagram

---

.github/workflows/build.yml
.travis.yml
artemis-cdi-client/pom.xml
artemis-distribution/pom.xml
pom.xml
tests/compatibility-tests/pom.xml
tests/integration-tests/pom.xml

These initial changes get things building on Java 16 (and 17EA+21)
Updates the parent pom and various plugins or deps, tidies up some elements of the poms and consolidates to inherit plugin versions from the parent where possible.

ARTEMIS-3296: get things building on Java 16 (and 17EA+21)

---

artemis-distribution/pom.xml

The gnu tar format causes some issues on some platforms because of some
restrictions instead the posix format is the most flexible format.

NO-JIRA Update the tar format for long files to posix

---

artemis-distribution/src/main/assembly/dep.xml

Fixes some of the warnings while creating an assembly, make it easier to see actual issues in future.
- Fixes 27 warnings about not including the project arifact (i.e pom file) while building the assemblies.
- Fixes 3 warnings about not triggering inclusion filter for a jar as it isnt included in the assembly anymore (from 2.17.0)

ARTEMIS-3314: fix some warnigns while creating assembly

---

artemis-distribution/pom.xml
artemis-distribution/src/main/assembly/bin.xml
artemis-distribution/src/main/assembly/dep.xml
artemis-distribution/src/main/assembly/dir.xml
artemis-distribution/src/main/assembly/source-assembly.xml

Carrying on after #3593, these changes fix all the remaining warnings emitted while building the assemblies, simplifying picking up on any future warnings issued.

ARTEMIS-3314: fix remaining warnings during assembly build

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/RecoverMessages.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/journal/DecodeJournal.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalImpl.java
artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalRecord.java
artemis-jdbc-store/src/test/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalLoaderCallbackTest.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/Journal.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/RecordInfo.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/AbstractJournalUpdateTask.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/FileWrapperJournal.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalBase.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalCompactor.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalRecordProvider.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalTransaction.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/DescribeJournal.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicatedJournal.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/replication/ReplicationTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/infinite/InfiniteRedeliverySmokeTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/JournalImplTestBase.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/journal/impl/JournalImplTestUnit.java

We known it's a replaceable record as part of the logic, no need to lookup the record type unless it's a reload from the system.

ARTEMIS-3261 Remove need to lookup replaceableRecords on the hot path

---

docs/user-manual/en/clusters.md

The documentation suggests to place the jgroups configuration file in the "resource-path".
It is unclear what the resource-path is, or how it can be changed to support a custom directory.
The `etc` directory of a broker instance is already in the resource-path and is therefore a natural choice.
The PR updates the documentation so that the suggestion is to place the jgroups confile file in the `etc` directory.

ARTEMIS-3334 suggest to use the etc directory for jgroups config, which is already in the classpath and also has all other config files

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQSessionContext.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/SessionContext.java

Previously, when during reconnect one session couldn't be transferred
to the new connection, we instantly returned and didn't execute failover
for the other sessions. This produced the issue that for sessions
where no failover was executed, their channels were still present on the
old connection. When the old connection was then destroyed, these channels
were closed although the reconnect was still ongoing, which lead to
"dead" sessions.
Now, we always execute failover for every session so that the channels
are guaranteed to be removed from the old connection before it is destroyed.

ARTEMIS-3337: Correctly handle multiple connection failures

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQSession.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/SecureConfigurationTest.java
tests/integration-tests/src/test/resources/multicast_topic.xml

A couple of tests were explicitly written to delete the
configuration-managed queue. Since this is no longer allowed these
tests had to change.

ARTEMIS-3374 & ARTEMIS-3381

---

artemis-commons/src/test/java/org/apache/activemq/artemis/utils/network/NetUtil.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/NetworkFailureFailoverTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/dnsswitch/DNSSwitchTest.java

Make DNSSwitchTest consistent on Java8 and 11+. Splits the OS check out to allow running separately, updates test to do that first, avoiding followup notes/checks about sudo and etc-hosts where it doesnt make sense. Changes the 'failIfNotSudo' to 'skipIfNotSudo' and runs this earlier for the Java 11+ cases, making DNSSwitchTest consistently skip if needed and print out details on why.
Change also stops NetworkFailureFailoverTest failing for similar reasons, instead making it skip and print details. Updated its intro text accordingly.

ARTEMIS-3409: consistently skip if preconditions aren't satisfied

---

pom.xml
tests/integration-tests/pom.xml

Enables some integration tests in the PR build, to help catch issues for important areas such as TLS and security handling without needing the full 3hr+ build. I tried it out with some reverts to ensure this would have meant PRs would have caught both the JDK15+ SSL runtime breakage (throwing UOE for previously deprecated-for-removal method), and the OpenSSL related issue with the changes made to remove use of those deprecated methods. It would also have caught the karaf tests not working on JDK 11.

ARTEMIS-3302: enable some integration tests in the fast-tests profile

---

pom.xml

The use of errorprone compiler plugin is opt-in on JDK8 and JDK16 already (due to the very slow compiler forking needed there) but is on by default in JDK11 etc with no easy way to disable it (still adds 2 minutes of build overhead running on Java 11 without forking). It would be good to make it consistently opt-in, making it easier to see the core build detail locally without it present (it emits a lot of added output) and not incurring the build overhead unless actually requested.
It will still always be run in CI as that always sets -Derrorprone when running.

NO-JIRA: make errorprone consistently opt-in on all JDKs

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/PrintData.java

* Adding public static void printData(File bindingsDirectory, File messagesDirectory, File pagingDirectory, PrintStream out, boolean secret) throws Exception
Issue: https://issues.apache.org/jira/browse/ARTEMIS-3431

[ARTEMIS-3431]: PrintData is missing a retro-compatible method.

---

.github/workflows/build.yml
.travis.yml
pom.xml

https://issues.apache.org/jira/browse/ARTEMIS-3440
The JIRA changes are in the first commit.
The PR also includes a second commit building on the first, to improve the GHA job config so various checks are run independently, ensuring the actual test suite finishes quicker, happens even if the checks fail (and more typically, vice versa), and the checks start and finish sooner. All together aiming to getting earlier and more complete feedback on the changes, with the overall runs sometimes ~10 minutes faster than before.
(This first run wont be as fast as it will most of the time, as the cache fixups will mean it has it to repopulate - though comparing, this scenario still looks to be ~15 minutes faster than it was before the changes, as the main branch cache happened to repopulate this …

ARTEMIS-3440: separate effect of -Pdev from test profiles, make them independent

---

artemis-quorum-ri/pom.xml
pom.xml

https://issues.apache.org/jira/browse/ARTEMIS-3453
Didnt test this at all yet other than seeing its effect on the main build. Seems the way to go though so raising for a PR run and any input from others.
In particular, by excluding sl4fj-log4j and log4j across the board, it may be necessary to add other dependencies to some modules (examples?) if they lack a another means of output such as another slf4j bridge.

ARTEMIS-3453: exclude log4j transitive dep from zookeeper

---

tests/integration-tests/pom.xml
tests/pom.xml
tests/smoke-tests/pom.xml
tests/unit-tests/pom.xml

Commit 97e84bb0d12cd2ce51571032ec3a946a97e6589d added in some explicit uses of the maven-resources plugin, and specifically configured use of version 2.6 for these. The build is otherwise already using version 3.1.0 of the resources-plugin, via pluginManagement from the apache parent pom. Its not clear the specific older version was needed, so this would remove it and keep the version config consistent and consolidated in the parents.
@brusdev ^
(Original change should probably have a JIRA that this could have gone against also)

NO-JIRA: undo addition of module-specific resources-plugin version

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverter.java
artemis-protocols/artemis-openwire-protocol/src/test/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverterTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java

While converting a core message to an OpenWire message there may be an
error processing a property value. Currently this results in an
exception and the message is not dispatched to the client. The broker
eventually attempts to redeliver this message resulting in the same
error. Instead of throwing an exception the broker should simply log a
WARN message and skip the property. This will allow clients to receive
the message without the problematic property and the broker will not
have to attempt to redeliver the message again.

ARTEMIS-3457 log WARN for OpenWire property conversion problem

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/BufferSplitter.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/persistence/impl/journal/BufferSplitterTest.java

https://issues.apache.org/jira/browse/ARTEMIS-3465

ARTEMIS-3465 BufferSplitter::split shouldn't consume input buffer

---

artemis-distribution/pom.xml
artemis-distribution/src/main/assembly/dep.xml
artemis-distribution/src/test/scripts/run-examples.sh
artemis-distribution/src/test/scripts/run-standard-examples.sh
artemis-jakarta-client-all/pom.xml
artemis-maven-plugin/pom.xml
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCLIPlugin.java
docs/user-manual/en/architecture.md
docs/user-manual/en/filter-expressions.md
docs/user-manual/en/messaging-concepts.md
docs/user-manual/en/protocols-interoperability.md
docs/user-manual/en/using-jms.md
docs/user-manual/en/versions.md
examples/features/standard/pom.xml
examples/features/standard/queue-jakarta/pom.xml
examples/features/standard/queue-jakarta/readme.md
examples/features/standard/queue-jakarta/src/main/java/org/apache/activemq/artemis/jms/example/QueueExample.java
examples/features/standard/queue-jakarta/src/main/resources/jndi.properties
examples/features/sub-modules/artemis-jakarta-ra-rar/pom.xml
examples/features/sub-modules/artemis-jakarta-ra-rar/src/main/resources/ra.xml
examples/features/sub-modules/pom.xml
pom.xml
tests/smoke-tests/pom.xml

Back in version 2.17.0 we began to provide Maven artifacts for Jakarta
Messaging client resources. This commit expands that support in the
following ways:
- Distribute a Jakarta Messaging 3.0 client with the broker (in the
'lib/client' directory alongside the JMS client.
- Update documentation.
- Add example using the Jakarta Messaging client.
- Update Artemis CLI to use core instead of JMS as it was causing
conflicts with the new Jarkarta Messaging client.
- Add example to build Jarkarta Messaging version of the JCA RA for
deployment into Jakarta EE 9 application servers.

ARTEMIS-3484 flesh out Jakarta Messaging support

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/JsonUtil.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/api/core/JsonUtilTest.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AMQPMessageSupport.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageTest.java

ARTEMIS-3461: add some tests and resolve various issues spotted with the prior changes
- Avoid blowing up on string bodies of any size if the valueSizeLimit bits are configured to disable limit.
- Dont NPE if amqp-value + binary body is sent without a content-type, as it always should be.
- Include expected prefix when adding delivery delay and ingress time annotations.
- Use the actual name for ingress time annotation, as with all other annotations.
- Use correct object type when testing equality with content-type value.
- Use consistent case for 'groupId' in different properties.

ARTEMIS-3461: add some tests and resolve various issues spotted

---

examples/features/standard/xa-heuristic/src/main/java/org/apache/activemq/artemis/jms/example/DummyXid.java
examples/features/standard/xa-receive/src/main/java/org/apache/activemq/artemis/jms/example/DummyXid.java
examples/features/standard/xa-send/src/main/java/org/apache/activemq/artemis/jms/example/DummyXid.java
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/jms/xa/JMSXDeliveryCountTest.java

- Checkstyle verification fails on JMSXDeliveryCountTest
because of empty line with trailing spaces
```
[INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ extra-tests ---
[INFO] Starting audit...
[ERROR] /home/buildadm/workspace/upstream-test-suite/validate-install-tests/validate-install-tests-upstream/artemis-src/tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/jms/xa/JMSXDeliveryCountTest.java:681: Line has trailing spaces. [RegexpSingleline]
Audit done.
[INFO] There is 1 error reported by Checkstyle 8.43 with /home/buildadm/workspace/upstream-test-suite/validate-install-tests/validate-install-tests-upstream/artemis-src/tests/extra-tests/../../etc/checkstyle.xml ruleset.
[ERROR] src/test/java/org/apache/activemq/artemis/tests/extras/jms/xa/JMSXDeliveryCoun …
```

ARTEMIS-3538 fix extra-tests formatting and examples compilation

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/JMSServerManager.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/impl/JMSServerManagerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/messagecounter/impl/MessageCounterHelper.java

The HTML output methods are hold-overs from way back when the code-base
started off as JBoss Messaging 2 and the broker mainly ran in JBoss AS 4
and 5 which leveraged an HTML-based JMX console where these methods
would be executed and spit out nicely formatted data. That stuff has all
long since been retired so this commit deprecates the HTML-based
management methods so they can be removed completely in a future release.
JSON is a better structured output format for this and most of the
deprecated methods have JSON alternatives.

ARTEMIS-649 deprecate the HTML based JMX reports

---

.github/workflows/build.yml
.travis.yml
artemis-dto/pom.xml
pom.xml
tests/activemq5-unit-tests/pom.xml
tests/smoke-tests/pom.xml

https://issues.apache.org/jira/browse/ARTEMIS-3420
I have been extracting and dropping related isolated changes onto main for a while already that have just released with 2.18.0, since they improved various Java 11+ related issues without actually requiring it. These are my remaining changes to actually require and target Java 11, resolve new issues that creates, and clean up some bits that become stale as a result.

ARTEMIS-3420: Target Java 11

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/BrokerBalancerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/BrokerBalancerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagingManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagingStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingManagerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/balancing/BrokerBalancer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/balancing/targets/TargetKeyResolver.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/embedded/EmbeddedActiveMQ.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
docs/user-manual/en/address-model.md
docs/user-manual/en/management.md
docs/user-manual/en/slow-consumers.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFlowControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/balancing/ElasticQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/MessageCounterTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/SlowConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlUsingCoreTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/BrokerBalancerControlTest.java
tests/performance-tests/src/test/java/org/apache/activemq/artemis/tests/performance/storage/PersistMultiThreadTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PagingStoreImplTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/util/FakePagingManager.java

scenario - avoid paging, if address is full chain another broker and produce to the head, consume from the tail using producer and consumer roles to partition connections. When tail is drained, drop it.
- adds a option to treat an idle consumer as slow
- adds basic support for credit based address blocking ARTEMIS-2097
- adds some more visiblity to address memory usage and balancer attribute modifier operations

elastic queue use case test based on ARTEMIS-3365 and ARTEMIS-3569

---

pom.xml

The netty-transport-native-epoll transitive dependency version of zookeeper
doesn't match the netty version defined and causes a distribution issue.

ARTEMIS-3559 Exclude netty-transport-native-epoll from zookeeper

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/ssl/OpenSSLContextFactoryProvider.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/ssl/SSLContextFactoryProvider.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/bridge/impl/JMSBridgeImpl.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/recovery/RecoveryManager.java

This resolves an issue i was seeing when running artemis in karaf where if the artemis-server-osgi bundle got reloaded during the resolution process I would see this error prevent artemis from starting.
org.apache.activemq.artemis.spi.core.remoting.ssl.SSLContextFactory: org.apache.activemq.artemis.core.remoting.impl.ssl.DefaultSSLContextFactory not a subtype

ARTEMIS-3596 Pass class loader to ServiceLoader.load to fix OSGi issues

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap-web-settings.txt
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/BindingDTO.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/WebServerDTO.java
artemis-dto/src/test/java/org/apache/activemq/artemis/dto/test/BindingDTOTest.java
artemis-dto/src/test/java/org/apache/activemq/artemis/dto/test/WebServerDTOTest.java
artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
artemis-web/src/test/java/org/apache/activemq/cli/test/WebServerComponentTest.java
artemis-web/src/test/resources/bootstrap_secure_web.xml
artemis-web/src/test/resources/bootstrap_web.xml
artemis-web/src/test/resources/bootstrap_web_old_config.xml
docs/user-manual/en/masking-passwords.md
docs/user-manual/en/security.md
docs/user-manual/en/using-server.md
docs/user-manual/en/web-server.md
examples/features/standard/camel/camel-broker/src/main/resources/activemq/server0/bootstrap.xml
examples/features/sub-modules/inter-broker-bridge/artemis-jms-bridge/readme.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/quorum/PluggableQuorumNettyNoGroupNameReplicatedFailoverTest.java
tests/smoke-tests/src/main/resources/containerService/bootstrap.xml

* Add BindingDTO to allow configuring multiple addresses to listen on
* Start a new ServerConnector for each binding and deploy the corresponding web-applications
* Update documentation and tests
* Add tests to verify old and new configuration style produce equal results

Fix: ARTEMIS-3574 multiple bindings for embedded webserver

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/JsonUtil.java

JsonUtil.addToObject
* When the added Object is of type JsonValue, don't call the toString
method on it.
Issue: https://issues.apache.org/jira/browse/ARTEMIS-3607

[ARTEMIS-3607]: Supporting JsonValues in JsonUtil.addToArray and

---

artemis-hawtio/artemis-console/pom.xml
artemis-hawtio/pom.xml

Move to the latest release of Hawtio 2.14.x.
Also, remove the Log4j archives from the web console application. It's
not necessary to include Log4j archives because Hawtio itself uses SLF4J
and the logging implementation will be provided by the broker runtime.
We already do this for SLF4J.
While not strictly necessary, removing Log4j will ease concerns about
security issues such as the recently announced CVE-2021-44228.

ARTEMIS-3612 update Hawtio and strip Log4j from console web app

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageTest.java

See https://issues.apache.org/jira/browse/ARTEMIS-3623
@clebertsuconic this is a modification on 'your' code. did I overlook a reason why the extraProperties must always be strings?

ARTEMIS-3623 preserve type of numeric extraProperties

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java

* deployBridge now returns a boolean to know if the deployment succeeded or not.
Issue: https://issues.apache.org/jira/browse/ARTEMIS-3682

[ARTEMIS-3682]: No way of knowing if a bridge was successfully deployed or not.

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingTest.java

Execute org.apache.activemq.artemis.tests.integration.paging.PagingTest.testInabilityToCreateDirectoryDuringPaging[storeType=DATABASE, mapped=false] to reproduce this issue.

ARTEMIS-3697 Skipping testInabilityToCreateDirectoryDuringPaging for db

---

artemis-distribution/src/main/assembly/dep.xml
artemis-hawtio/activemq-branding/pom.xml
artemis-hawtio/artemis-console/pom.xml
artemis-hawtio/artemis-plugin/pom.xml
artemis-hawtio/pom.xml
artemis-rest/pom.xml
artemis-web/pom.xml
examples/features/sub-modules/tomcat/pom.xml
pom.xml
tests/integration-tests/pom.xml

Use specific jetty deps instead of uber jar, rationalise the servlet api deps.
Partially reverts https://github.com/apache/activemq-artemis/commit/c5f94f340d721600c4b67dc003eace023b046211 as it was useful after all.
This passes all the tests, and the console seems to work fine. It doesnt seem that any of the many more things jetty-all brought in [1] are actually needed, but maybe someone more familiar with these bits would know more.
[1] https://repo1.maven.org/maven2/org/eclipse/jetty/aggregate/jetty-all/9.4.44.v20210927/jetty-all-9.4.44.v20210927.pom

ARTEMIS-3695: use specific jetty deps instead of uber jar

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/SequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFile.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/aio/AIOSequentialFileFactory.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalFileImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalFilesRepository.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/test/java/org/apache/activemq/artemis/core/io/aio/FileIOUtilTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/AsyncOpenCloseTest.java

I am adding a test showing it is safe to not wait pending callbacks before closing a file.
With this I can just close the file and let the kernel to deal with sending the completions.

ARTEMIS-3701 Do no block libaio on compacting or closing

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
tests/unit-tests/pom.xml
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PagingStoreImplTest.java

Stop paging checkMemory task executing twice in some cases.

ARTEMIS-3591: stop paging checkMemory task executing twice

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolHandler.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTPublishManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSession.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSubscriptionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTVersion.java
docs/user-manual/en/mqtt.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MQTTSecurityTest.java

The commit includes the following changes:
- Don't drop the connection on subscribe or publish authorization
failures for 3.1 clients.
- Don't drop the connection on subscribe authorization failures for
3.1.1 clients.
- Add configuration parameter to control behavior on publish
authorization failures for 3.1.1 clients (either disconnect or not).

ARTEMIS-3702 auth failures don't adhere to MQTT spec

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java

This kind of exception can be common in cloud environments and should be
ignored for logging just like ConnectException.

ARTEMIS-3676 ignore NoRouteToHostException

---

tests/pom.xml
tests/smoke-tests/pom.xml
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/jms/ManifestTest.java

This PR contains a fix to the jms jar manifest test:
As the test needs the generated jms jars to be verified I moved it from unit-tests to smoke-tests.
Updated the test to look for the correct jars as the originally specified does not exist.
Update the test to assert against Implementation-Version instead of ActiveMQ-Version in the manifest file as the ActiveMQ-Version property does not exist.

NO-JIRA - fix ManifestTest

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolHandler.java

This bug is causing tests in o.a.a.a.t.i.m.s.c.ConnectTestsWithSecurity
to fail.
This commit fixes the problem by setting the session's version earlier
in the logic handling the CONNECT packet so that the proper CONNACK
return code can be supplied to the remote client in case of
authentication failure.

ARTEMIS-3764 wrong CONNACK return code for MQTT5

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/queues.js

This is a follow-up from ARTEMIS-3397. This commit removes the last
traces of the "rate" queue metric from the web console.

ARTEMIS-3773 remove defunct rate references from web console

---

artemis-commons/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQScheduledComponent.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingTest.java

Instead of holding a thread and an iterator, we should instead keep moving to next references
without holding any threads. Just with callbacks.

ARTEMIS-3778 Streamline Expiration Reaping

---

artemis-jakarta-client-all/pom.xml
artemis-jakarta-client/pom.xml
artemis-jakarta-ra/pom.xml
artemis-jakarta-server/pom.xml
artemis-jakarta-service-extensions/pom.xml
pom.xml

Group the alternative versions into a related property, easily found at the root near the base version property, and perform the overrides using that. Remove superfluous version entrys from dependency uses, its already covered by the version properties and dependencyManagement.

ARTEMIS-3783: rationalise config for alternate jakarta spec versions

---

artemis-commons/src/main/java/org/apache/activemq/artemis/core/server/NetworkHealthCheck.java

* Changing the default ping command for Windows.
Jira: https://issues.apache.org/jira/browse/ARTEMIS-3799

[ARTEMIS-3799]: Ping command is wrong on Windows.

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/NetworkHealthCheckTest.java

The NetworkHealthCheck hasn't to execute the default command if a custom
command is defined.

ARTEMIS-3803 Fix first NetworkHealthCheck execution

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/Redistributor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/crossprotocol/ProtocolsMessageLoadBalancingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/MessageRedistributionTest.java

The control existing in Redistributor is not needed as the Queue::deliver will already have a control on re-scheduling the loop and avoid holding references for too long.

ARTEMIS-3807 Simplify Redistributor and fix ProtocolMessageLoadBalancingTest

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/MirrorAddressFilter.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/MirrorAddressFilterTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/amqpBrokerConnectivity/AMQPMirrorBrokerConnectionElement.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/en/amqp-broker-connections.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPReplicaTest.java

Allow replication only certain addresses with mirror controller.
The configuration is similar to cluster address configuration.

ARTEMIS-3759 Add mirror controller address filter support

---

pom.xml

Upgrade jboss-logging 3.4.3.Final dependency due to false-positive vulnerability reports
Minor upgrade for jboss-logging from 3.4.3 to 3.5.0
Patch upgrade for jboss-logging-annotations from 2.2.0.Final to 2.2.1.Final
Patch upgrade for jboss-logging-processor from 2.2.0.Final to 2.2.1.Final

ARTEMIS-3806 Upgrade jboss-logging dependencies

---

artemis-jakarta-client/src/main/resources/jms-version.properties
artemis-jakarta-ra/src/main/resources/jms-version.properties
pom.xml

* Upgrading the API to Jakarta Messaging 3.1.0
* Updating the metadata to 3.1.0
Jira: https://issues.apache.org/jira/browse/ARTEMIS-3700

[ARTEMIS-3700]: Provinding a JakartaEE 10 implementation.

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/actors/HandlerBase.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagingStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/nullpm/NullStorageManager.java
pom.xml
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/byteman/RaceOnCursorIteratorTest.java
tests/jms-tests/src/test/java/org/apache/activemq/artemis/jms/tests/JMSTestCase.java
tests/performance-tests/src/test/java/org/apache/activemq/artemis/tests/performance/storage/PersistMultiThreadTest.java
tests/stress-tests/src/test/java/org/apache/activemq/artemis/tests/stress/paging/PageCursorStressTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PagingManagerImplTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PagingStoreImplTest.java

This is caused by too many entires on the HashMap for ThreadLocals.
Also: I'm reviewing some readlock usage on the StorageManager to simplify things a little bit.

ARTEMIS-3848 High CPU usage on ReadWriteLocks

---

artemis-selector/pom.xml

see https://issues.apache.org/jira/browse/ARTEMIS-3842

ARTEMIS-3842 removed reference to JDK8 by retiring a whole mvn profile

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSubscriptionManager.java
docs/user-manual/en/versions.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MQTTQueueCleanTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/PahoMQTTQOS2SecurityTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/MQTT5Test.java

MQTT 3.1 and 3.1.1 clients using a clean session should have a
*non-durable* subscription queue. If the broker restarts the queue
should be removed. This is due to [MQTT-3.1.2-6] which states that the
session (and any state) must last only as long as the network
connection.

ARTEMIS-3851 MQTT sub q exists after restart despite CleanSession=1

---

artemis-distribution/pom.xml
tests/e2e-tests/pom.xml
tests/smoke-tests/pom.xml

Mark the -all client deps optional in distribution pom to avoid passing on their clashing/duplicate deps to users of it. Clean up some existing uses in the build itself hitting the issue.

ARTEMIS-3870: mark -all client deps optional in distribution pom

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationBrokerConnectionEncryptedTest.java
artemis-server/src/test/resources/ConfigurationTest-broker-connection-encrypted-config.xml

Adds support for ENC(...) attribute values for user and password on
amqp-connection.

ARTEMIS-3873 AMQP Broker Conn Encrypted Attrs

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalCompactor.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/JournalCompactSplitTest.java

The condition fixed on this commit should not really happen in production
as the compacting counts should always be ordered (records that were compacted earelier will always be at the top of the journal).
However it highlights an improvement that could be done on the journal compacting.

ARTEMIS-3868 Journal compactor split improvement

---

.github/workflows/build.yml
artemis-website/pom.xml
artemis-website/src/main/resources/examples/index.html
artemis-website/src/main/resources/hacking-guide/index.html
artemis-website/src/main/resources/index.html
artemis-website/src/placeholder/javadoc/overview.html
artemis-website/src/placeholder/javadoc/placeholder/Placeholder.java
artemis-website/src/placeholder/javadoc/placeholder/package-info.java

Move site javadoc generation into release profile, knock ~1min off a regular build, add simple placeholder (as all the other module content has) to satisfy rest of build. Fix some issues in other related placeholder content. Tweak the CI job to more obviously/specifically check the release profile build for these bits.

ARTEMIS-3877: move site javadoc generation into release profile

---

.github/workflows/build.yml

Updates OS from Ubuntu 18 to Ubuntu 20
Updates github actions cache, checkout and setup-java to v3
Needs a test run to see if there are any visible time improvements

NO-JIRA: Update github actions

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlUsingCoreTest.java

AddressControl has 2 methods to get same metric. Both
getNumberOfMessages() and getMessageCount() return the same metric
albeit in different ways.
Also, getNumberOfMessages() inspects both "local" and "remote" queue
bindings which is wrong.
This commit fixes these issues via the following changes:
- Deprecate getNumberOfMessages().
- Change getNumberOfMessages() to invoke getMessageCount().
- Add a test to ensure getNumberOfMessages() does not count remote
queue bindings.
- Simplify getMessageCount(DurabilityType).

ARTEMIS-1964 fix and deprecate getNumberOfMessages() on AddressControl

---

artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
artemis-web/src/test/java/org/apache/activemq/cli/test/WebServerComponentTest.java
docs/user-manual/en/management-console.md

Currently the broker detects the presence of the web console by looking
for the name of a file (i.e. console.war). This is fragile because if
the file is renamed for any reason then the broker won't print the
status of the web console when it starts.
This commit improves web console detection by inspecting the
<display-name> tag in the war file's WEB-INF/web.xml. By default it
looks for "hawtio", but this can be customized using the system property
"org.apache.activemq.artemis.webConsoleDisplayName".

ARTEMIS-3888 make web console detection more robust

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/ActiveMQServerMessagePlugin.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/impl/LoggingActiveMQServerPlugin.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/plugin/impl/LoggingActiveMQServerPluginLogger.java

Both audit logging and logging from the LoggingActiveMQServerPlugin are
unclear as they relate to transactional sends and acks. Both essentially
ignore the transaction which makes it appear that an operation has taken
place when, in fact, it hasn't (e.g. a transactional ack is rolled back
but the log indicates the ack went through).
This commit fix this with the following changes:
- Log details when a send or ack is added to a transaction.
- Log details when the transaction is committed.
- Log when the transaction is rolled back.
- Include transaction details in the relevant DEBUG logs.
- Simplify INFO level logging for sends & acks in
LoggingActiveMQServerPlugin. Ensure details are in the DEBUG logs.
Other changes:
- Make capitalization more consistent in a handful of audit logs.

ARTEMIS-3896 clarify logging for transactional ops

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/RoutingContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RoutingContextImpl.java

We were lucky that processReferences was pretty much a static operation, hence I am moving it away from RoutingContext both for clarity and avoiding state being needed on that method.
If state was needed as part of processReferences you would had a pretty nasty bug as the IOCallback could introduce a race where a send would change the state while the IO was pending.

ARTEMIS-3909 Move RoutingContext::processReferences as a static method in PostOffice

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/BindingsImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/distribution/MessageRedistributionTest.java

When a message is sent to an anycast queue via FQQN on one node of a
cluster and then a consumer is created on that same anycast queue via
FQQN on another node in the cluster the message is not redistributed to
the node with the consumer.
This commit fixes this use-case primarily by including the FQQN info in
the notification messages sent to other nodes in the cluster.

ARTEMIS-3918 support FQQN + anycast + redistribution

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java

RoleSet.class.getMethods() returns the same methods on both OpenJDK 11 and
OpenJ9 JDK 11 but the order is different. OpenJDK 11 returns
`public void org.apache.activemq.artemis.core.config.impl.RoleSet.add` before
`public boolean java.util.HashSet.add` while OpenJ9 JDK 11 returns
`public boolean java.util.HashSet.add` before
`public void org.apache.activemq.artemis.core.config.impl.RoleSet.add`

ARTEMIS-3963 Fix setting security roles via properties on OpenJ9 JDK 11

---

artemis-commons/src/main/java/org/apache/activemq/artemis/core/server/NetworkHealthCheck.java

The ping command on Windows uses -w timeout in milliseconds.

ARTEMIS-3964 Fix default ping commands timeout for Windows

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/util/NettyReadable.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/util/NettyReadableTest.java

Ensures that when reading a string the readable buffer consumes the bytes by advancing the read index as defined in the interface API docs.

ARTEMIS-3990 Ensure that readable buffer string read consumes the bytes

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageCursorProviderImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/paging/MegaCleanerPagingTest.java

The issue is that depage should not put pages on the used pages as they were not actually intended to read. instead I should create a newPageObject and not use the RefCounts caching.

ARTEMIS-4029 Avoid OME When too many pages are cleared all at once

---

tests/integration-tests/pom.xml

ResourceLoadingSslContext depends on jakarta.annotation-api

NO-JIRA Add direct jakarta.annotation-api dependency to integration-tests

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis.cmd

Tested on Windows10 with the path `C:\Program Files\apache-artemis-2.26.0-instance1`

ARTEMIS-4057 Fix backup last OOME heap dump on Windows

---

.github/workflows/build.yml
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/handler/ExecutorNettyAdapter.java
artemis-unit-test-support/src/main/java/org/apache/activemq/artemis/utils/ThreadLeakCheckRule.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/AllClassesTest.java

Fixes a couple of issues causing test failures or hangs, and adds a Java 19 job to the CI runs on push/PR.

ARTEMIS-4076: add JDK 19 run to CI jobs

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/MetricsManager.java
pom.xml

In order to improve trouble-shooting for the MetricsManager there should be additional logging and exceptions. In all, this commit contains the following changes:
- Additional logging
- Throw an exception when registering meters if meters already exist
- Rename a few variables & methods to more clearly identify what they are used for
- Upgrade Micrometer to 1.9.5
- Simplify/clarify a few blocks of code
- No longer pass the ManagementServiceImpl when registering the metrics, but instead pass the Object the meter is observing (e.g. broker, address, or queue)

ARTEMIS-4064 Harden MetricsManager

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/ConnectionAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/queue/StatQueue.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java

CLI commands which only use a JMS connection (e.g. producer and consumer) will retry successfully when omitting or specifying the incorrect user and/or password. However, commands which use the core API directly will not.

ARTEMIS-4079 CLI retry doesn't work sometimes

---

artemis-boot/src/main/java/org/apache/activemq/artemis/boot/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Action.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/ActionAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/HelpAction.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/address/HelpAddress.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/check/HelpCheck.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/queue/HelpQueue.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/HelpData.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/user/HelpUser.java
artemis-cli/src/test/java/org/apache/activemq/artemis/cli/commands/messages/ConnectionAbstractTest.java
artemis-cli/src/test/java/org/apache/activemq/artemis/cli/commands/messages/TransferTest.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/CheckTest.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/OptionsValidationTest.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCLIPlugin.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCreatePlugin.java
tests/smoke-tests/pom.xml
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/custometc/CustomETCTest.java

This is fixing an issue introduced by the logging changes where a custome ETC would not work correctly.

ARTEMIS-4020 Fixing Management DTO Parsing with custom ETC

---

artemis-web/src/main/java/org/apache/activemq/artemis/component/AuthenticationFilter.java

The HTTP redirection messages (300 – 399) must be ignored they don't mean an authentication failure.

ARTEMIS-4071 Fix erroneus audit log messages due to console logouts

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/LinkedListImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/RefsOperation.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/client/ClientCrashMassiveRollbackTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/util/LinkedListTest.java

when cancelling a large number of messages, the addSorted could be holding a lock for too long causing the server to crash under CriticalAnalyzer

ARTEMIS-4084 Fixing addSorted with large transactions

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedStoreLiveActivation.java

DefaultCriticalErrorListener stops the server while SharedStoreLiveActivation is initializing it.

ARTEMIS-4030 Fix SharedStoreLiveActivation race condition

---

artemis-server-osgi/pom.xml
artemis-server/pom.xml
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/KubernetesLoginModule.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/PropertiesLoader.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/ServiceAccountPrincipal.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/client/KubernetesClient.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/client/KubernetesClientImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/model/TokenReview.java
artemis-server/src/test/java/org/apache/activemq/artemis/spi/core/security/jaas/KubernetesLoginModuleTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/TokenCallbackHandler.java
artemis-server/src/test/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/client/KubernetesClientImplTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/model/ServiceAccountPrincipalTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/spi/core/security/jaas/kubernetes/model/TokenReviewTest.java
artemis-server/src/test/resources/client_token
artemis-server/src/test/resources/k8s-roles.properties
docs/user-manual/en/security.md
pom.xml

Implement a Kubernetes LoginModule for ServiceAccounts using the TokenReview API
It is based on the PropertiesLoginModule and does not have any additional runtime dependency.
This is my first contribution to this repository so please, let me know if anything is out of place or does not comply with your best practices.
Signed-off-by: ruromero <rromerom@redhat.com>

[ARTEMIS-3168] Implement Kubernetes JaaS LoginModule

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/nio/NIOSequentialFileFactory.java

This is just to make releaseBuffer to have the same semantic when no pool is used.
This has no effect on how the broker behaves as we always have it pooled.

NO-JIRA releaseBufferMemory just in case

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/TransportConstants.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/impl/netty/NettyConnectorTest.java

Adds support for standard Java TLS and ActiveMQ Artemis-specific override
encrypted system property values for the key store and trust store
passwords

ARTEMIS-3794 System Property Encryption Support

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQRAManagedConnection.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/ActiveMQMessageHandlerXATest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/ActiveMQRATestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/DummyTransactionSynchronizationRegistry.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/IgnoreJTATest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/JMSContextTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/OutgoingConnectionJTATest.java

A handful of tests started to fail after the original fix was committed. This commit fixes those failures mainly by using a mock `TransactionSynchronizationRegistry`.
I changed `o.a.a.a.r.ActiveMQRAManagedConnection#checkTransactionActive` slightly because `getTransactionStatus` will never return `null` unlike `getTransaction` would. The semantics should still be the same, though.

ARTEMIS-3707 fixing tests

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AutoDeleteJmsDestinationTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/TemporaryQueueTest.java

When the last non-durable subscriber on a JMS topic disconnects the corresponding queue representing the subscription is deleted as expected. However, the queue's address will also be deleted no matter what, which is *not* expected.

ARTEMIS-4125 address can be removed inadvertently

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSMessageConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSLVQTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSMessageConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSMessageGroupsTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSMessageTypesTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSNonDestructiveTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSSelectorTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSSharedConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSSharedDurableConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSXPathSelectorTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/MultiprotocolJMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/package-info.java

Over time org.apache.activemq.artemis.tests.integration.amqp has become home to many multi-protocol JMS tests even though the package is really for AMQP-specific tests. This commit splits those tests out into their own package.
This is a preliminary step to clarify these tests before I add another one for a different issue.

ARTEMIS-4127 refactor multiprotocol JMS tests in AMQP package

---

artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQConnectionFactory.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/DefaultConnectionProperties.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/JMSSecurityTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ConnectionFactoryPropertiesTest.java

Adds standard username and password value unmasking for JMS ActiveMQConnection instances and its subclasses

ARTEMIS-3790 Support masked JMS credentials

---

artemis-hawtio/artemis-plugin/src/main/webapp/plugin/js/components/browse.js

See https://issues.apache.org/jira/browse/ARTEMIS-3819
fields 'validateduser' and 'original queue' may not have a value.
this PR just makes sure that the JS code does not care

ARTEMIS-3819 do not trip on empty values in web-console

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AutoCreateWithDefaultRoutingTypesTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/BrokerDefinedAnycastConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/ClientDefinedAnycastConsumerTest.java

When an AMQP client subscribes to a new address (non-existing) with a receiver link, the address is created with routing type ANYCAST regardles of the default address creation configuration of the broker, and ignores even the broker wide default of MULTICAST.

ARTEMIS-4132 AMQP Receiver default to ANYCAST when creating an address

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/routing/ConnectionRouter.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/routing/ConnectionRouterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/routing/pools/DiscoveryGroupService.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/routing/targets/LocalTarget.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/routing/ConnectionRouterManagerTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/routing/ConnectionRouterTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/routing/KeyTypeTest.java

The nodeID on backup brokers is available only after they become live.

ARTEMIS-4113 Fix NPE for backup brokers with connection routers

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/settings/impl/PageFullMessagePolicy.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/Validators.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/PagingStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/PageCursorProvider.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageCursorProviderImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageSubscriptionCounterImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
docs/user-manual/en/paging.md
examples/features/standard/paging/src/main/java/org/apache/activemq/artemis/jms/example/PagingExample.java
examples/features/standard/paging/src/main/resources/activemq/server0/broker.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingLimitTest.java
tests/performance-tests/src/test/java/org/apache/activemq/artemis/tests/performance/storage/PersistMultiThreadTest.java

I am adding three attributes to Address-settings:
* page-limit-bytes: Number of bytes. We will convert this metric into max number of pages internally by dividing max-bytes / page-size. It will allow a max based on an estimate.
* page-limit-messages: Number of messages
* page-full-message-policy: fail or drop
We will now allow paging, until these max values and then fail or drop messages.
Once these values are retracted, the address will remain full until a period where cleanup is kicked in by paging. So these values may have a certain delay on being applied, but they should always be cleared once cleanup happened.

ARTEMIS-3178 Page Limitting (max messages and max bytes)

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpPipelinedConnectTest.java

For pipelined open cases the events processing should ignore additional begin and attach events if the open event handler closes the connection to avoid the processing throwing additional exceptions and replacing the error condition in the connection with an unrelated error about NPE from the additional events.

ARTEMIS-2431 Stop processing Begin and Attach frames if open fails

---

docs/hacking-guide/en/code.md
docs/hacking-guide/en/history.md
docs/hacking-guide/en/ide.md
docs/hacking-guide/en/maintainers.md
docs/hacking-guide/en/tests.md

Updates the hacking guide docs to correct the branch names as "main"

NO-JIRA - Hacking Guide Branch Name Updates

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java

o.a.a.a.c.p.o.a.AMQConsumer#init will *always* try to create a core queue when creating a consumer for a JMS queue. However, this is already done in o.a.a.a.c.p.o.a.AMQSession#createConsumer.

ARTEMIS-4170 remove redundant queue creation for OpenWire

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/jolokia-access.xml
artemis-cli/src/test/java/org/apache/activemq/artemis/cli/commands/CreateTest.java

The hostname gets put into an xml comment in the jolokia-access.xml file.  If the hostname has invalid char sequences for an xml comment, jolokia will fail at load time because the xml file is invalid.
Signed-off-by: David Lanouette <David.Lanouette@RedHat.com>

ARTEMIS-4160 Handle hostnames with invalid char sequences.

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/AddressManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/SimpleAddressManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AddressInfo.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueManagerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeTestAccessor.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config-address-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-address-settings.xml
artemis-unit-test-support/src/main/java/org/apache/activemq/artemis/utils/Wait.java
docs/user-manual/en/address-settings.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AutoDeleteAddressTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/AutoDeleteQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/MQTT5Test.java

There are certain use-cases where addresses will be auto-created and never have a direct binding created on them. Because of this they will never be auto-deleted. If a large number of these addresses build up they will consume a problematic amount of heap space.
One specific example of this use-case is an MQTT subscriber with a wild-card subscription and a large number of MQTT producers sending one or two messages a large number of different MQTT topics covered by the wild-card. Since no bindings are ever created on any of these individual addresses (e.g. from a subscription queue) they will never be auto-deleted, but they will eventually consume a large amount of heap. The only way to deal with these addresses is to manually delete them.
There are also situations  where queues may be …

ARTEMIS-4162 support deleting addresses & queues w/o usage check

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/management.xml
docs/user-manual/en/versions.md
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/upgradeTest/CompareUpgradeTest.java

This is a preventative measure to limit what users can do with any MBean other than those in the hawtio or org.apache.activemq.artemis domains.

ARTEMIS-4151 tighten default MBean access

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AddressInfo.java

I have seen a werid intermittent failure in the testsuite caused by some race where the EMPTY_SET ends up Not Empty! Causing weird failures that were really difficult to be investigated

ARTEMIS-4162 Remove EMPTY_ROUTING_TYPES from AddressInfo

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpLargeMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/LargeMessageAvoidLargeMessagesTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/LargeMessageCompressTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/LargeMessageTest.java
tests/soak-tests/pom.xml
tests/soak-tests/src/main/resources/servers/dual-federation1/broker.xml
tests/soak-tests/src/main/resources/servers/dual-federation2/broker.xml
tests/soak-tests/src/main/resources/servers/lmbroker1/broker.xml
tests/soak-tests/src/main/resources/servers/lmbroker1/management.xml
tests/soak-tests/src/main/resources/servers/lmbroker2/broker.xml
tests/soak-tests/src/main/resources/servers/lmbroker2/management.xml
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/interruptlm/ClusteredLargeMessageInterruptTest.java

This is just adding a new test, similar to how an user was testling large message redistribution and large messages it basically sends and receives messages like crazy... asserting that no messages are left in the folder.
It would be difficult to assert the counting of messages because of possible failures. (not knowing if the failure was before of after the message is recorded on disk).

ARTEMIS-4206 Unreferenced AMQP Large Messages not removed right away, requiring a reboot

---

artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
tests/integration-tests/pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/HeuristicXATest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/federation/FederatedTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/MultiprotocolJMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/BridgeControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/BridgeControlUsingCoreTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ClusterConnectionControl2Test.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ClusterConnectionControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ConnectionRouterControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ManagementTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/OpenWireTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/routing/ElasticQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/xa/BasicXaRecoveryTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/util/JMSClusteredTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/util/JMSTestBase.java

Basically I started the testsuite and attached check leak with "java -jar check-leak.jar --pid <pid> --report testsuite-report --sleep 1000" and saw the allocations of this were pretty high.

NO-JIRA Cleanup MBeanServer usage in the testsuite as it is leaking

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/LargeServerMessageImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/ServerSessionPacketHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/Redistributor.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/interruptlm/ClusteredLargeMessageInterruptTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/interruptlm/LargeMessageInterruptTest.java

- redistribute received the handle call, it then copies the message
- the routing table changes
- the message is left behind
With the new version of the server these messages will be removed. But we should remove these right away

ARTEMIS-4207 Redistribution could leave messages stranded in the folder

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/federation/FederatedQueueConsumerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/federation/FederatedTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/federation/NettyFederatedQueueTest.java

The federated queue consumer has to generate a new id for the messages received from the upstream broker because they have an id generated by the store manager of the upstream broker.
@clebertsuconic thanks for your help

ARTEMIS-4211 Fix record message id for federated queue consumers

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/MQTT5Test.java
tests/soak-tests/pom.xml
tests/soak-tests/src/main/resources/servers/mqtt/broker.xml
tests/soak-tests/src/main/resources/servers/mqtt/management.xml
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/mqtt/MQTT5SoakTest.java

MQTT5Test::testMaxMessageSize is spiking the memory on the integration testsuite all the way up to 1.5G what makes this test more like a soak test.
The test is now converted to use a real server like other Soak Tests.

NO-JIRA Moving MQTT5Test::testMaxMessageSize into a soak-test

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/log4j2.properties
artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ManagementRemotingConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java
docs/user-manual/en/logging.md

This commit fixes the following things:
- Moves connection audit logging to the resource audit logger instead of using a dedicated logger as that would adversely impact upgrading users, and arguably didn't make sense in the first place.
- Mitigates an potential NPE w.r.t. connection ID.
- Updates the "dummy" management connection to return a valid connection ID.

ARTEMIS-4210 refactor connection audit logging

---

artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/ClientIDCallback.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/security/jaas/JaasCallbackHandler.java
artemis-server/src/test/java/org/apache/activemq/artemis/spi/core/security/jaas/JaasCallbackHandlerTest.java

Currently there is no way to get client ID in custom login module. Its required for some MQTT cases when username is not used.

introduce ClientIDCallback to allow JAAS login module to retrieve Client ID

---

artemis-junit/artemis-junit-4/src/test/java/org/apache/activemq/artemis/junit/ActiveMQConsumerResourceTest.java
artemis-junit/artemis-junit-4/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceTest.java
artemis-junit/artemis-junit-4/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceWithoutAddressExceptionTest.java
artemis-junit/artemis-junit-4/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceWithoutAddressTest.java
artemis-junit/artemis-junit-4/src/test/java/org/apache/activemq/artemis/junit/ActiveMQProducerResourceTest.java
artemis-junit/artemis-junit-4/src/test/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQResourceTest.java
artemis-junit/artemis-junit-5/src/test/java/org/apache/activemq/artemis/junit/ActiveMQConsumerResourceTest.java
artemis-junit/artemis-junit-5/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceTest.java
artemis-junit/artemis-junit-5/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceWithoutAddressExceptionTest.java
artemis-junit/artemis-junit-5/src/test/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerResourceWithoutAddressTest.java
artemis-junit/artemis-junit-5/src/test/java/org/apache/activemq/artemis/junit/ActiveMQProducerResourceTest.java
artemis-junit/artemis-junit-5/src/test/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQResourceTest.java
artemis-junit/artemis-junit-commons/src/main/java/org/apache/activemq/artemis/junit/ActiveMQDynamicProducerDelegate.java
artemis-junit/artemis-junit-commons/src/main/java/org/apache/activemq/artemis/junit/ActiveMQProducerDelegate.java
artemis-junit/artemis-junit-commons/src/main/java/org/apache/activemq/artemis/junit/EmbeddedActiveMQDelegate.java

The JUnit resource has a couple bugs in both the send and receive path that result in only one message being received if the receive method is called repeatedly and some send drop the provided properties. Cleaned up some tests to the point of showing the errors and ensuring that at least basic functionality is tested.

ARTEMIS-4234 Fix some issue with Embedded Resource send and receive

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java

Some of these tests don't make sense when using the Core protocol due to noise introduced

ARTEMIS-4253 disabling a few ActiveMQServerControlUsingCoreTest tests

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Upgrade.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap-web-settings.txt
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/AppDTO.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/BindingDTO.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/WebServerDTO.java
artemis-dto/src/test/java/org/apache/activemq/artemis/dto/test/WebServerDTOTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
docs/user-manual/en/web-server.md
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/web/WebServerDTOConfigTest.java

It is possible to use system properties to add or update web configuration items.
If you define a system property starting with "webconfig." it will be parsed at the startup
to update the web configuration.
To enable the client authentication for an existing binding with the name `artemis`,
set the system property `webconfig.bindings.artemis.clientAuth` to `true`, i.e.
```
java -Dwebconfig.bindings.artemis.clientAuth=true
```
To add a new binding or app set the new binding or app attributes using their new names, i.e.
```
java -Dwebconfig.bindings.my-binding.uri=http://localhost:8162
java -Dwebconfig.bindings.my-binding.apps.my-app.uri=my-app
java -Dwebconfig.bindings.my-binding.apps.my-app.war=my-app.war
```
To update a binding without a name use its uri and to update an app without a …

ARTEMIS-4244 Set web config using system properties

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java

During redistribution, we should not copy all message annotations.
In particular we should not copy any of the x-opt-ORIG annotations used on DLQ and other copies.
this was broken after f632e8104bbdae1fbf3658fec47e180784e957da (ARTEMIS-3833 Preserve JMSCorrelationID of distributed AMQP large messages)
The change preserved too much, and as a result of that AmqpLargeMessageRedistributionTest::testSendMessageToBroker0GetFromBroker2 is intermittently failing.
There is no test in this commit as this is fixing AmqpLargeMessageRedistributionTest

ARTEMIS-4268 AMQPMessage copy constructor shouldn't copy all message annotations

---

pom.xml

Changes:
https://netty.io/news/2023/04/25/4-1-92-Final.html 
https://netty.io/news/2023/04/03/4-1-91-Final.html
https://netty.io/news/2023/03/14/4-1-90-Final.html
https://netty.io/news/2023/02/13/4-1-89-Final.html
https://netty.io/news/2023/02/12/4-1-88-Final.html
https://netty.io/news/2023/01/12/4-1-87-Final.html
Issue: [ARTEMIS-4269](https://issues.apache.org/jira/browse/ARTEMIS-4269)

ARTEMIS-4269: Update Netty from 4.1.86 to 4.1.92

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientMessageBundle.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ServerLocatorConnectTest.java

ServerLocatorImpl waits for topology after connecting a new session factory. It should interrupt waiting for topology when it is closed to fail fast.

ARTEMIS-4283 Fail fast CORE client connect on closing

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-image/README.md
artemis-image/TODO.md
artemis-image/examples/README.md
artemis-image/examples/amqp_sasl_scram_test__etc/amqp_sasl_scram.properties
artemis-image/examples/amqp_sasl_scram_test__etc/login.config
artemis-image/examples/amqp_sasl_scram_test__etc/role
artemis-image/examples/byoc__etc/broker.xml
artemis-image/examples/pom.xml
artemis-image/pom.xml
artemis-image/src/main/jib/config/acceptor.properties
artemis-image/src/main/resources/log4j2.properties
artemis-image/src/test/java/org/apache/activemq/artemis/ActiveMQImageExamplesTest.java
artemis-jms-server/src/main/java/org/apache/activemq/artemis/jms/server/embedded/EmbeddedJMS.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/embedded/EmbeddedActiveMQ.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/embedded/Main.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/embedded/MainTest.java
pom.xml

This module builds an OCI image tar, based around a broker Main class, that can be configured with property files and/or xml. 
The intent is to be a simple as possible but still be useful. See the README.md for details.

ARTEMIS-3042 simple properties based, extensible broker image

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/MetricsManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/NettyMetricsTest.java

ARTEMIS-4291 Add the "broker" tag in a consistent manner to all exported metrics.
Some scrapers, e.g. prometheus, add an "instance" tag. This value may not be the same as
the broker name, which results in these metrics becoming more difficult to match up with
the corresponding broker.

ARTEMIS-4291 Add the "broker" tag in a consistent manner

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis-service.xml

When installing artemis on windows as a service, if your chosen installation path contained a space, then an extra escape character (%) was being inserted in the generated
artemis-service.xml, causing the service to fail to start. This fix changes the value of ARTEMIS_INSTANCE_ETC_URI in that file from "artemis.instance.etc.uri.windows" to "artemis.instance.etc.uri" to get rid of that unnecessary escape character.

ARTEMIS-4303 Fix windows service

---

artemis-distribution/pom.xml

This commit also updates the artifact used to generate the HTML from the MarkDown as the existing artifact is now defunct.

ARTEMIS-4316 fix example doc formatting

---

artemis-server/src/test/java/org/apache/activemq/artemis/core/server/embedded/MainTest.java

`org.apache.activemq.artemis.core.server.embedded.MainTest` expects the broker to throw a `java.io.IOException` when it is started due to its inability to find the file app/data/server.lock. However, if that files just happens to exist then the test will simply hang indefinitely. This commit adds a timeout to avoid hanging.

ARTEMIS-4328 add timeout to test which can hang

---

artemis-commons/pom.xml
artemis-core-client/pom.xml
artemis-jms-client/pom.xml
artemis-jms-server/pom.xml
artemis-server/pom.xml
artemis-website/pom.xml

Currently JavaDoc is generated for many classes that don't need it. JavaDoc should be reserved for user-facing classes (e.g. those used by client application developers and developers embedding a broker into their application). This commit narrows down the configuration to just the classes that are needed. This will save time during release builds, and save disk space wherever these files are stored (e.g. Apache website).

ARTEMIS-4341 refactor JavaDoc generation

---

artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/util/ThreadLocalByteBufferPool.java
artemis-journal/src/test/java/org/apache/activemq/artemis/core/io/util/ThreadLocalByteBufferPoolTest.java

The report for ARTEMIS-4340 was raised about ByteUtil.uncheckedZeros throwing IndexOutOfBoundsException. Though some of ByteUtil's behaviour can perhaps be questioned around its consistency with different buffer types, in this case the problem ultimately starts earlier in the call tree with org.apache.activemq.artemis.core.io.util.ThreadLocalByteBufferPool.borrow(int, boolean) passing it invalid arguments. It passes in a buffer for zeroing, with its limit still set below the requested size to be zero'd, leading to the IndexOutOfBoundsException in this case when tryign to write beyond the limit. The reason this seemingly long-standing bug has perhaps not been hit so far is that it occurs in a less typical case where the buffer either isnt direct and able to be updated with Unsafe, or also …

ARTEMIS-4340: fix ThreadLocalByteBufferPool.borrow zeroing

---

artemis-server/pom.xml
pom.xml

Version 2.9.0 of commons-configuration2 now includes commons-text 1.10.0 so the dependencies can be simplified.

ARTEMIS-4358 upgrade commons-configuration2

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/OperationContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/OperationContextImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ServerSession.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/persistence/impl/journal/OperationContextUnitTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java

ARTEMIS-4332 Add management method to close stuck server sessions 
In rare cases a store operation could silently fails or starves, blocking the related server session and all delivering messages. Those server sessions can be closed adding a management method that cleans their operation context before closing them.
This PR also includes an optional commit to track store operations that would help to analyze heap dumps with stuck server sessions: ARTEMIS-4332 Add store operation trackers

ARTEMIS-4332 Add management method to close stuck server sessions

---

artemis-docker/Dockerfile-alpine-17

This new Dockerfile uses Alpine Linux as base image, so the resulting image is smaller. Also, it makes use of Java 17.
It's not multi-stage. It's basically a copy of Dockerfile-ubuntu-11, but with Alpine-specific commands.

ARTEMIS-4310 Add Alpine/Java17 based Docker image

---

artemis-service-extensions/src/main/java/org/apache/activemq/artemis/service/extensions/xa/recovery/ActiveMQXAResourceWrapper.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ActiveMQXAResourceWrapperTest.java

ARTEMIS-4354 Allow the recovery XAResource to be osing and reconnceting

---

artemis-docker/Dockerfile-alpine-11-jre
artemis-docker/prepare-docker.sh
artemis-docker/readme.md

The goal for this file is to be used in conjunction with the existing Dockerfile-ubuntu-11-jre when pushing images to
https://hub.docker.com/r/apache/activemq-artemis.
I also updated the documentation.

ARTEMIS-4376 add Dockerfile for Alpine + JRE 11

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/AddressSettingsTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config-address-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-address-settings.xml
docs/user-manual/address-settings.adoc
docs/user-manual/configuration-index.adoc
docs/user-manual/duplicate-detection.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/DuplicateDetectionTest.java

This pull request introduces support for configuring a specific id-cache-size per address - [ARTEMIS-4159](https://issues.apache.org/jira/browse/ARTEMIS-4159). The changes include modifications to various files:
* artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
* artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
* artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
* artemis-server/src/main/resources/schema/artemis-configuration.xsd
* artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java
* artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
* …

[ARTEMIS-4159] Support duplicate cache size configuration per address

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/NotificationTest.java

Repeated creation and disposal of queue consumers with empty string (`""`) filters could cause these strings to build up within a `QueueInfo` instance belonging to that queue.

ARTEMIS-4387 Fix empty consumer filter string leak

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpFlowControlFailTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/TopicDurableTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/OpenWireFlowControlFailTest.java

The corrections were made to address typographical errors found in both logging messages and certain test cases.
Jira link - https://issues.apache.org/jira/browse/ARTEMIS-4389

ARTEMIS-4389 The word "mesage" should be corrected to "message"

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/InstallAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Upgrade.java
tests/smoke-tests/pom.xml

The test cannot work on Windows unless I can make the `upgrade` CLI command respect my choice to upgrade a Linux distribution. This commit therefore adds a new `--linux` option for the `upgrade` command, and leverages it in the `upgrade-linux` smoke test.
* The `--cygwin` option has been preserved for backwards compatibility.
* The `IS_CYGWIN` attribute has been renamed to `IS_NIX` to reflect the change.
* The OS "recognition" method (in `InstallAbstract::run`) has been updated to reflect the need for enforcing *nix behavior, which is now the default if all other methods fail.

ARTEMIS-4390 Fix upgrade-linux smoke test on Windows

---

artemis-docker/prepare-docker.sh
artemis-docker/readme.md

Tree utility is not present by default in a lot of smaller Linux installations, like for example CentOS or Rocky Linux minimal image. As it serves almost no purpose other than visual, I suggest removing this dependency from Docker build requirements.
Alternatively, I can prepare a PR with `ls -la` alternative if you think it is still needed to list those files.

NO-JIRA Remove dependency on tree utility

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingManagerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/files/FileStoreMonitor.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/files/FileStoreMonitorTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config-wrong-address.xml
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/paging.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/GlobalDiskFullTest.java

This is a follow-up to #3812 with the following changes:
- Resolved conflicts.
- Eliminated a lot of code duplication.
- Simplified `org.apache.activemq.artemis.core.server.files.FileStoreMonitor.Callback` and its support for multiple settings.
- I didn't bother with deprecating anything since these are internal classes.
- Added documentation.

ARTEMIS-3057 Add min-disk-free feature

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressConsumer.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java

When updating or adding the hops value the AMQP message needs a re-encode to carry that value forward when the message is sent to the next broker.

ARTEMIS-4431 Re-encode the AMQP message annotations if hops are updates

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/MessageHandler.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientConsumerImpl.java
artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/JMSMessageListenerWrapper.java
artemis-ra/src/main/java/org/apache/activemq/artemis/ra/inflow/ActiveMQMessageHandler.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/client/SlowLargeMessageConsumerTest.java

Fixes https://issues.apache.org/jira/browse/ARTEMIS-4141
When big messages are produced if a consumer receives an expired message, the credits are not updated, so if the consumer is too slow and an expiry delay has been set, we can end up with a situation where there are no more credits which prevents the consumer from receiving any more messages.
* Updates the credits even in case of an expired message to avoid running out of credits
* Add a test simulating the use case of the ticket

ARTEMIS-4141 Update credits even for expired messages

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPConnectionCallback.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPConnectionCallbackTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/logging/AuditLoggerResourceTest.java

Ensure the eligibility check done can succeed with the audit logging enabled, allowing non-SASL connections if broker config allows (rather than erroneously failing and indicating SASL is required when it shouldnt be).

ARTEMIS-4451: fix non-SASL AMQP connection + resource audit logging

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTLogger.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTPublishManager.java

In accordance with the QoS2 protocol outlined in the MQTT specification(s), once the broker receives a PUBLISH then any other PUBLISH it receives on that same session with the same packet ID must be ignored until the QoS2 protocol for that ID is completed.
The broker does this, but it doesn't log anything so it's not clear when this is actually happening.

ARTEMIS-4459 log when rejecting dupe MQTT QoS2 pub

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/RemotingConnectionImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/ActiveMQChannelHandler.java

* Since the constructors in RemotingConnectionImpl can be used from the server and the client. If the server calling code is in a different classloader then the constructor can't be called.
* same for the 'active' boolean property of ActiveMQChannelHandler
Issue: https://issues.apache.org/jira/browse/ARTEMIS-4467

ARTEMIS-4467 Core client code visibility change required.

---

artemis-commons/pom.xml

Possible alternative to fix the issue raised in #4657. Partially restores the exclusion filter that was previously removed, narrowing it to drop the services file.

ARTEMIS-4477: remove incorrect services file

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQResourceAdapter.java

Fixing the creation of the recovery connection factory so that useTopologyForLoadBalancing is properly set.
Issue: https://issues.apache.org/jira/browse/ARTEMIS-4508

ARTEMIS-4508 the recovery connection factory ignores useTopologyForLoadBalancing.

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/bean/MetaBean.java
artemis-commons/src/test/java/org/apache/activemq/artemis/utils/bean/MetaBeanTest.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressSettingsInfo.java
artemis-core-client/src/test/java/org/apache/activemq/artemis/api/core/management/AddressSettingsInfoTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/config/AbstractPersistedAddressSetting.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/config/PersistedAddressSettingJSON.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/DescribeJournal.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalRecordIds.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/nullpm/NullStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/AddressSettingsTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/impl/AddressSettingsRandomTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImplTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/SendAckFailTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/RedeployTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/journal/DuplicateRecordIdTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/paging/PagingOrderTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/AddressSettingsConfigurationStorageTest.java

As I worked through implementing a more generic JSON marshaller, I tried using reflection through BeanUtils and other ways however the endresult was always worse as there were a few caveats that were not as easy to accomplish.
For that reason I went to a declarative appraoch where I define a meta-data object on AddressSettings and AddressSettingsInfo and reuse the metadata in a few other places.

ARTEMIS-3932 Deprecate and replace addAddressSettings with json version

---

artemis-cli/src/main/java/org/apache/activemq/artemis/util/ServerUtil.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerTarget.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/amqpBrokerConnectivity/AMQPMirrorBrokerConnectionElement.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/nullpm/NullStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/ManagementService.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/Transaction.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/group/impl/ClusteredResetMockTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImplTest.java
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/utils/cli/helper/HelperBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPReplicaTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPSyncMirrorTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/BrokerInSyncTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/MirrorControllerBasicTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/PagedMirrorTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/SendAckFailTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/IdempotentACKTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/InterruptedLargeMessageTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/MirroredTopicSoakTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/sender/SenderSoakTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/BindingsImplTest.java

Mirror acks should be performed atomically with the storage of the source ACK. Both the send of the ack and the recording of the ack should be part of the same transaction (in case of transactional).
We are also adding support on transactions for an afterWired callback for the proper plug of OperationContext sync.

ARTEMIS-4558 Idempotent Mirrored ACKs

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/CoreProtocolManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java

There is a race condition between ConnectionEntry.ttl and FailureCheckAndFlushThread whereby an in-vm connection may get closed inadvertently due to a TTL timeout. This is because ConnectionEntry.ttl is initialized to 60000 and then later set to -1 upon the initial Ping. If this update happens at *just* the right time in FailureCheckAndFlushThread then the connection will be closed.
The fix ensures that the ConnectionEntry.ttl is set to -1 for in-vm connections from the start. It also eliminates the possibility of the race in FailureCheckAndFlushThread.
This fix is based on static analysis of the code. The timing window is just too small to contruct a reliable test. The failure has only been seen in the wild a handful of times.

ARTEMIS-4571 race condition w/TTL impacting in-vm connections

---

artemis-protocols/artemis-jakarta-openwire-protocol/pom.xml
artemis-protocols/pom.xml
pom.xml
tests/compatibility-tests/pom.xml
tests/compatibility-tests/src/main/resources/openWireJakarta/artemisJakartaServer.groovy
tests/compatibility-tests/src/main/resources/openWireJakarta/sendReceiveOW.groovy
tests/compatibility-tests/src/test/java/org/apache/activemq/artemis/tests/compatibility/OpenWireJakartaTest.java

If the broker is embedded into a Jakarta environment then the existing artemis-openwire-protocol module won't work because it uses javax classes.
This commit adds a new Jakarta-specific module that can be used to support OpenWire clients in Jakarta environments (e.g. Spring Boot 3). Users will simply need to include this version on their classpath to enable support.

ARTEMIS-4567 support OpenWire clients for broker embedded in Jakarta environment

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/ActiveMQClientLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ServerLocatorInternal.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/Topology.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/TopologyManager.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQClientProtocolManager.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/RemotingConnectionImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/spi/core/remoting/TopologyResponseHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/warnings/ClusterCleanNodeShutdownTest.java

When we know that a node leaves a clustercleanly we shouldn't log WARN messages about it.
Issue: https://issues.apache.org/jira/browse/ARTEMIS-4436

ARTEMIS-4436 Artemis is logging warnings during clean shutdown of server in cluster.

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java

Change from forcing a session start cycle on each consumer add event and start only those consumers that were added which will trigger a prompt delivery action on each. The session should be marked started on create to account for the remove of the start on each consumer add event.

ARTEMIS-4575 Only start the consumers that were added

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/JGroupsBroadcastEndpoint.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/discovery/DiscoveryTest.java

If both scale-down and cluster-connection are using the same JGroups discovery-group then when the cluster-connection stops it  will close the underlying org.jgroups.JChannel and when the scale-down process tries to use it to find a server it will fail.
This commit ensures that the JGroupsBroadcastEndpoint implementation of BroadcastEndpoint#openClient initializes the channel if it has been closed.

ARTEMIS-3831 scale-down w/jgroups fails if using same dg as cluster-connection

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientConsumerImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientProducerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/LargeMessageCompressTest.java

I made this revision because I encountered an issue with the previous fix.
It's a bit tricky to write a test for, since it is actually already fixed in the most recent broker version for other reasons but I felt there might be some other scenario out there that can still get affected by the current implementation of "ARTEMIS-4185".
In short, broker versions after "ARTEMIS-4185" and before "ARTEMIS-4382" would not be able to export and then import compressed messages without them breaking. It's because the COMPRESSED-header is set to false by the producer without a consumer having decompressed the message first.
This revision sets the COMPRESSED-header to true at the producer (where compression happens) and to false at the consumer (where decompression happens). I feel this makes more …

ARTEMIS-4185 - Revision on sending already compressed messages

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTLogger.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTProtocolManagerFactory.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionState.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTStateManager.java
artemis-protocols/artemis-mqtt-protocol/src/test/java/org/apache/activemq/artemis/core/protocol/mqtt/StateSerDeTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config.xml
docs/user-manual/mqtt.adoc

This commit:
- Eliminates MQTT session storage on every successful connection. Instead data is only written when subsriptions are created or destroyed.
- Adds a configuration property for the storage timeout.
- Updates the documentation with relevant information.
- Refactors a few bits of code to eliminate unnecessary variables, etc.

ARTEMIS-4542 improve MQTT state storage

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTPublishManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTRetainMessageManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionState.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSubscriptionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTUtil.java
artemis-protocols/artemis-mqtt-protocol/src/test/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTUtilTest.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/util/OpenWireUtil.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/WildcardConfiguration.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/WildcardConfigurationTest.java
docs/user-manual/mqtt.adoc
docs/user-manual/versions.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MQTTTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MQTTTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MqttWildCardSubAutoCreateTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/PahoMQTTQOS2SecurityTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/MQTT5Test.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/MQTT5TestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/ControlPacketFormatTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/MessageReceiptTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/QoSTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/controlpackets/ConnectTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/controlpackets/PublishTests.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/controlpackets/PublishTestsWithSecurity.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/spec/controlpackets/SubscribeTestsWithSecurity.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/ssl/CertificateAuthenticationSslTests.java

Currently when an MQTT topic filter contains characters from the configured wildcard syntax the conversion to/from this syntax breaks.
For example, when using the default wildcard syntax if an MQTT topic filter contains a . the conversion from the MQTT wildcard syntax to the core wildcard syntax and back will result in the `.` being replaced with a `/.`.
This commit fixes that plus a few other things...
- Implements proper conversions to/from one WildcardConfiguration to another.
- Refactors the MQTT code which invokes these conversion methods. This includes simplifying a lot of test code.
- Adds lots of tests for everything.
- Clarifies some variable naming to better distinguish between core and MQTT.

ARTEMIS-4532 MQTT-to-core wildcard conversion is broken

---

artemis-boot/src/main/java/org/apache/activemq/artemis/boot/Artemis.java
artemis-cli/pom.xml
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Shell.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/AutoCompletion.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/ArtemisTest.java
artemis-maven-plugin/pom.xml
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCLIPlugin.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisCreatePlugin.java
artemis-maven-plugin/src/main/java/org/apache/activemq/artemis/maven/ArtemisUpgradePlugin.java
pom.xml
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/utils/cli/helper/HelperCreate.java

I had to remove the indirect dependency between the maven plugin and jline to avoid the maven plugin to parse some classes in jline that require experimental features on the JDK even when they are not in use.

ARTEMIS-4617 upgrade JLine to 3.25.1

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationAddressEntry.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationQueueEntry.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationQueuePolicyManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

Implement idempotent tracking for tracking demand at start while also tracking demand as consumer or bindings are added and removed.

ARTEMIS-4626 Improve demand tracking for federation consumers

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis-service

In rare cases the status is returning 'running' to a process that is not Artemis. It was create a extra level of verification by validating if the running process working directory is the
same of ${ARTEMIS_INSTANCE}.

ARTEMIS-4630 Validate if the pid is really from Artemis

---

docs/hacking-guide/_building.adoc
pom.xml

Move os-maven-plugin extension, added to aid 'offline' maven usage, into a profile to use on request...its default presence breaks reproducibility of the `artemis-commons` module.

ARTEMIS-4640: move os-maven-plugin extension into a profile

---

tests/config/log4j2-tests-config.properties

I have to keep looking how to do this every time I need it. I just wanted to proposed a commented out section for next time I need this again.

NO-JIRA proposed log4j commented out log configuration for testing

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederation.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationBaseSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConstants.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationEventDispatcher.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationEventProcessor.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationEventSupport.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueueSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/FederationReceiveFromQueuePolicy.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationAddressEntry.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationQueueEntry.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationQueuePolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/logger/ActiveMQAMQPProtocolMessageBundle.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPSessionContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerSenderContext.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/SenderController.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConfigurationReloadTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

When an AMQP federation instance attempts to federate an address or queue it can fail if the remote address or queue is not present or cannot be created based on broker policy. A federation link can also closed if the federated resource is removed from the remote broker by management etc. In those cases the remote broker should note the resources that were targets of federation and send alerts to the source federation broker to notify it that these resources become available for federation and the source should attempt again to create federation links if demand still exists. This allows an AMQP federation instance to heal itself based on updates from the remote.

ARTEMIS-4641 Support events for add of missing federation resources

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/LargeMessageControllerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/federation/FederatedQueueTest.java

Large message support was added to
o.a.a.a.c.s.f.FederatedQueueConsumerImpl#onMessage via cf85d35 for ARTEMIS-3308. The problem with that change is that when onMessage returns o.a.a.a.c.c.i.ClientConsumerImpl#callOnMessage will eventually call o.a.a.a.c.c.i.ClientLargeMessageImpl#discardBody which eventually ends up in o.a.a.a.c.c.i.LargeMessageControllerImpl#popPacket waiting 30 seconds (i.e. the default readTimeout) for more packets to arrive (which never do). This happens because the FederatedQueueConsumer short-cuts the "normal" process by using LargeMessageControllerImpl#take.
This commit fixes that by tracking the number of bytes "taken" and then looking at that value later when discarding the body effectively skipping the 30 second wait.

ARTEMIS-4588 30 second pause for large msgs + federation

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationBrokerPliuginTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConfigurationReloadTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPMirrorConnectionTest.java

Use the test name to create unique names for broker connections in the tests and the associated test logs

ARTEMIS-4645 Update broker connection tests to use unique broker names

---

artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/ActiveMQStompProtocolMessageBundle.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompConnection.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompSession.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompUtils.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/VersionedStompFrameHandler.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/v12/StompFrameHandlerV12.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/StompTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/StompTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v11/StompV11Test.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/stomp/v12/StompV12Test.java

Use combined consumer and message ID as STOMP message ID.

ARTEMIS-4649 Use unique STOMP message ID per subscription

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionState.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt/MQTTTest.java

Generate MQTT message IDs from full allowed range of 1-65535 and skip currently used values. Do not use atomic integer for current ID, because all accesses and modifications are performed in synchronized context.

ARTEMIS-4646 Reuse only acknowledged MQTT IDs

---

tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/utils/RealServerTestBase.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/logging/AuditLoggerAMQPMutualSSLTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/logging/AuditLoggerResourceTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/logging/AuditLoggerTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/logging/AuditLoggerTestBase.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/nettynative/NettyNativeTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/clusterNotificationsContinuity/ClusterNotificationsContinuityTest.java

These tests are using an asynchronous feature. the check on Log has to use the Wait.assertEquals
I had to make a few changes to the methods to allow the use of Wait

NO-JIRA Improving AuditLoggerTest::testAuditHotLog* tests

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressConsumer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationPolicySupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpInboundConnectionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java

When federation is configured in two directions between nodes for an address the message can reflect from one node to another if max hops is not set or not set correctly and in some federation topologies the max hops value can't solve the issue and still result in a working configuration. This reflection should be prevented at the federation consumer level for address consumers.

ARTEMIS-4658 Prevent reflections when using dual address federation

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java

Tests need to ensure federation links are up before sending to and address or the sent message can get discarded before the federation consumer is there to receive it.

ARTEMIS-4665 Add additional state checks to fix test failures in CI

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

Fix intermittent test failures in pull consumer test by asserting that there are the expected number of message on the queue before running the JMS consume cycle to consume credit and trigger federation credit to flow.

ARTEMIS-4665 Fix AMQP federation pull consumer test failures

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/MetricsConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/MetricsManager.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/DefaultsFileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-metrics.xml
artemis-server/src/test/resources/metrics.xml
docs/user-manual/metrics.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/LoggingMetricsTest.java

It may be useful to configure alerts for ERROR or WARN events in the log which may go unnoticed otherwise.

ARTEMIS-4655 report logging metrics

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ScheduledDeliveryHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/MessageReferenceLeakTest.java

Alerting on issues with messages not being received properly for a period of time is an uneasy task. We use the `getFirstMessageAge()` command to trigger alerts in Zabbix, and it works as long as there are no consumers.
But this approach fails when there are consumers repeatedly failing to receive a message. That message is getting scheduled for redelivery over and over, and even though there still is an old message in the queue to be reported, it's no longer visible via `getFirstMessage*()` API.
The goal here is to add a set of functions working with messages scheduled for delivery:
```java
getFirstScheduledMessageAsJSON()
getFirstScheduledMessageTimestamp()
getFirstScheduledMessageAge()
```
It may be not the most effective approach but it's quite a convenient one, especially when …

ARTEMIS-4579 Add the *FirstMessage* API for scheduled messages

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionImpl.java

This fix was based on static analysis of the code and inspection of the XA specification. There is no test associated with it due to the difficult nature in reproducing the failure. This code has been essentially the same for a decade and only now have there been any reports of it actually sending back the wrong XA code.

ARTEMIS-4652 rollback of XAResource impl shouldn't return XA_RETRY

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/QueueFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/LastValueQueue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/PostOfficeJournalLoader.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueFactoryImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/tests/unit/core/server/impl/fakes/FakeQueueFactory.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/HangConsumerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/InterruptedLargeMessageTest.java

Whenever we create a queue with a filter we're instantiating 3 different `org.apache.activemq.artemis.core.filter.impl.FilterImpl` objects. This is wasteful and entirely avoidable.

ARTEMIS-4686 reduce number of FilterImpl instances

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/reader/MessageUtil.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AMQPMessageIdHelper.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/CoreAmqpConverter.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/converter/message/AMQPMessageIdHelperTest.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverter.java
artemis-protocols/artemis-openwire-protocol/src/test/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireMessageConverterTest.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSCorrelationIDTest.java

This is a prelude to implementing the correlation ID support for https://issues.apache.org/jira/browse/ARTEMIS-4264 (i.e. interop between MQTT 5 & JMS clients).

ARTEMIS-4657 support byte[] correlation ID compat b/w core & AMQP JMS

---

artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/journal/JDBCJournalImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/Journal.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/FileWrapperJournal.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/impl/JournalImpl.java
artemis-journal/src/main/java/org/apache/activemq/artemis/journal/ActiveMQJournalLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/JournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/replication/ReplicatedJournal.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/Redistributor.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/crossprotocol/LargeHeadersClusterTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/replication/ReplicationTest.java

Redistribution would add data to the record which would then in turn make the record too large to redistribute.
The Redistributor and Bridges should not be removed.
Also a warning should be added to warn users about the situation.

ARTEMIS-4694 Redistribution issues with Almost Large Header

---

artemis-core-client/pom.xml
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/ssl/SSLSupport.java
artemis-pom/pom.xml

The latest version already uses bcprov-jdk18on

ARTEMIS-4710 Keep pem-keystore dependencies as is; make it really optional

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/federation/FederationQueueMatchXMLConfigParsingTest.java
tests/integration-tests/src/test/resources/core-federated-queue-match-server1.xml
tests/integration-tests/src/test/resources/core-federated-queue-match-server2.xml

Correct the XML parser for core federation queue match policy loading to call the setQueueMatch instead of setAddressMatch when reating the queue match element.

ARTEMIS-4666 Correctly set queue match when parsing XML confing

---

artemis-lockmanager/artemis-lockmanager-ri/pom.xml
artemis-pom/pom.xml

The lib folder includes netty-tcnative-boringssl-static artifacts non-aligned with the netty-tcnative-version in pom.xml. Those artifacts are included because of zookeeper-server.

ARTEMIS-4722 Exclude netty-tcnative-boringssl-static artifacts

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/actors/HandlerBase.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/AbstractLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/ClientLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/ConnectionDroppedLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/ConnectionLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/CoreClientLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/HandlerBaseLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/JournalLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/LinkedListMemoryTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/MemoryAssertions.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/MessageReferenceLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/ProducerBlockedLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/RedistributorLeakTest.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/RefCountMessageLeakTest.java

ARTEMIS-4723 Avoid objects left on ThreadLocal from OrderedExecutorFactory

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/actors/HandlerBase.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/retention/LargeMessageRetentionTest.java

No need to create a new instance every time the processor starts executing. The instance of counter can be reused and stored in the Thread.

ARTEMIS-4723 Optimization on HandlerBase

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederation.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationCommandDispatcher.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConstants.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationEventDispatcher.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPConnectionContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/Match.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/impl/MatchTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java

When creating internal temporary queues for the federation control links and the events link we should use a structured naming convention to ease in configuring security for the federation user where all internal names fall under a root prefix which can be used to grant read and write access for the federation user. This change allows security on the wildcarded address "$ACTIVEMQ_ARTEMIS_FEDERATION.#". This change also includes some further restrictions added to federation resources and adds support for wildcarding '$' prefixed addresses.

ARTEMIS-4754 Structure the names used for federation internal queues

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/nullpm/NullStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/DuplicateIDCache.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/InMemoryDuplicateIDCache.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/NoOpDuplicateIDCache.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PersistentDuplicateIDCache.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImplTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/SendAckFailTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/ResizeDuplicateCacheTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/SingleMirrorSoakTest.java

in this commit I'm storing a binding record with the address-settings for the correct size this is also validating eventual merges of the AddressSettings in the same namespace.

ARTEMIS-4765 DuplicateIDCache on Mirror Target is using 20K elements instead of amqpCredits

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/queue/StatQueue.java

Notice that I'm keeping the old argument here as hidden As I keep using this myself, my brain always go to ./artemis queue stat --sleep
So, I think people would feel more comfortable if the parameter was renamed.

ARTEMIS-4743 Renaming --loop-sleep as just --sleep

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java

There is no need to use our own AddressSettings extension here. This is just simplifying the test.

NO-JIRA Improve a specific QueueControlTest

---

docs/user-manual/configuring-transports.adoc
docs/user-manual/connection-ttl.adoc
docs/user-manual/core.adoc

[`ServerLocator`](https://github.com/apache/activemq-artemis/blob/ae5d98337f00d5a123d95994b8437cdca1d319c4/artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/ServerLocator.java#L41) interface doesn't have `createClientSessionFactory` method -> should be `createSessionFactory`

NO-JIRA: fix docs locator.createClientSessionFactory should be locator.createSessionFactory

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTConnectionManager.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSession.java

This commit fixes the deadlock described on ARTEMIS-3622 by moving the synchronization "up" a level from the MQTTSession to the MQTTConnectionManager. It also eliminates the synchronization on the MQTTSessionState in the MQTTConnectionManager because it's no longer needed. This change should not only eliminate the deadlock, but improve performance relatively as well.
There is no test associated with this commit as I wasn't able to reproduce the deadlock with any kind of straight-forward test. There was a test linked on the Jira, but it involved intrusive and fragile scaffolding and wasn't ultimately tenable. That said, I did test this fix with that test and it was successful. In any case, I think static analysis should be sufficient here as the changes are pretty straight-forward.

ARTEMIS-3622 MQTT can deadlock on client cxn/discxn

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/PagedReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/MessageReference.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/GroupFirstMessageReference.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/MessageReferenceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/scheduling/ScheduledMessageTest.java

The original commit (1ee3e884b707a659d924188048c2960a3b22df35) for this issue wasn't completely correct. This commit fixes those issues so that both the messageCount and scheduledMessageCount are accurate now when a scheduled message is removed by its ID.

ARTEMIS-4726 fix original commit

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

Add a couple optional flags for performatives that might arrive based on the timing of connection close or remote detach etc.

NO-JIRA Fix a few cases of federation test fails on unexpected frames

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/MetricsConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/security/SecurityStore.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/security/impl/SecurityStoreImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/BrokerMetricNames.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/MetricsManager.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/DefaultsFileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-metrics.xml
artemis-server/src/test/resources/metrics.xml
docs/user-manual/metrics.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/CacheMetricsTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/MetricsPluginTest.java

This commit includes the following changes:
- Management operations to get sucess & failure counts for authn and authz along with the corresponding audit logging.
- Export the aforementioned authn & authz metrics.
- Export metrics for the underlying authn & authz caches including the ability to enable/disable them.
- Update metrics tests to validate tags in addition to keys and values.
- Update documentation to explain new functionality and clarify existing metric tags.

ARTEMIS-4306 add authn/z cache metrics

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConsumerConfiguration.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueuePolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/internal/FederationQueuePolicyManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java

Race on consumer create and broker shutdown could lead to a deadlocak trying to access configuration from the policy manager while the federation instance is trying to shutdown the policy manager.

ARTEMIS-4788 Fix a rare race on broker shutdown in AMQP federation

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingManagerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PagingStoreImpl.java

this is fixing PagingTest::testPagingStoreDestroyed(db=derby) (or any other DB).
This could eventually also fail on journal.
The cleanup could act on a destroyed folder, and issue an IOException stopping the server with this race.
You would need the server active cleaning messages while the queue is being removed.

ARTEMIS-4789 Page.destroy race with cleanup

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPMirrorConnectionTest.java

Test should add an optional expect close as it is very occasionally able to hit the wire and the test peer will fail if not expecting it might be.

NO-JIRA Fix test failed due to missing expectation

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpSendReceiveTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java

When caching address query results the remote session can be blocked forever from creating links on an address if the "does not exist" value is cached since it is never updated again and will always report "does not exist" even if the address is added manually via management later. The cache state can cause other issues for long running sessions as well and should be removed to avoid attach failures for cases where the current broker state could allow the attach to succeed but the cached entry won't allow it.

ARTEMIS-4801 Fix issue with caching address query results

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/logger/ActiveMQAMQPProtocolMessageBundle.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPBrokerConnectionReceiverTest.java

The receiver attach in broker connection does not wait for the remote attach to arrive before creating the broker side receiver plumbing which leads to the broker treating the remote sender as an anonymous relay when it is not and should not be. Await the remote attach in response to the attach sent by the broker connection to finish the link setup but use the locally defined target address vs the remote to route the incoming messages.

ARTEMIS-4799 Fix broker connection receiver attach handling

---

artemis-docker/docker-run.sh

The artemis-docker/docker-run.sh contains an echo of the startup arguments containing the admin credentials. 
For troubleshooting the output of our pods are fed to kibana. People analyzing these logs should not have the ability to see these credentials hence the proposal to remove this echo.

ARTEMIS-4816: Docker image echo's admin credentials during startup

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressPolicyManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java

When checking if address federation can be done the manager needs to look at the policy level settings before looking at federation or connector level settings for amqp credits.

ARTEMIS-4817 Check policy credits before checking parent credits

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpExpiredMessageTest.java

When setting expiration on the AMQPMessage the AMQP header TTL value should be read as an unsigned integer and as such should use the longValue API of UnsignedInteger to get the right value to set expiration.

ARTEMIS-4820 Read Header TTL as unsigned integer to set expiration

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/SimpleAddressManager.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/WildcardAddressManagerUnitTest.java

Currently, with 500K+ queues, the cleanup step of `TempQueueCleanerUpper` requires invoking `SimpleAddressManager#getDirectBindings`, which is O(k) in the number of queues `k`.
From method profiling, this can consume up to 95% of our CPU time when needing to clean up many of these.
Add a new map to keep track of the direct bindings, and add a test assertion that fails if we don't properly remove it.

ARTEMIS-4814 Make direct binding lookup time constant

---

pom.xml

Always use surefure default behaviour by default: fail module build when a test fails.
Anyone wanting to ignore failures so as to run all modules, can use the standard surefire prop to request that, e.g:
mvn test -Dmaven.test.failure.ignore

ARTEMIS-4831: use surefire default behaviour around test failure

---

.github/workflows/build.yml
pom.xml

Direct test output to file, make results more visible.
Archives test logs upon GHA CI job failure to allow inspection.

ARTEMIS-4832: direct test output to file, make results more visible

---

docs/user-manual/federation-address.adoc
docs/user-manual/federation-queue.adoc

The downstream connection setup is not in correct XSD order and fails on start of a broker if cut and pasted into broker configuration.

ARTEMIS-4902 Put example XML for core federation in correct order

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/BridgeConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQMessageBundle.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/ClusterManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/BridgeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/BridgeConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-bridges.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/bridge/BridgeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/BridgeConfigurationStorageTest.java

When a bridge is stopped it doesn't wait for pending send acknowledgements to arrive. However, when a bridge is paused it does wait. The behavior should be consistent and more importantly configurable. This commit implements these improvements and generally refactors BridgeImpl to clarify and simplify the code. In total, this commit includes the follow changes:
- Removes the hard-coded 60-second timeout for pending acks when pausing the bridge and adds a new config parameter (i.e. "pending-ack-timeout").
- Applies the new pending-ack-timeout when the bridge is stopped.
- Updates existing and adds new logging messages for clarity.
- De-duplicates code for sending bridge-related notifications.
- Avoids converting bridge name to/from SimpleString.
- Removes unnecessary comments.
- Renames …

ARTEMIS-4794 configure pending ack behavior for bridge

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/config/DivertConfiguration.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/DivertConfigurationEncodingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/DivertConfigurationStorageTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/StorageManagerTestBase.java

This commit fixes 4 distinct issues with divert configuration encoding:
- The encoding size was calculated incorrectly in three ways:
- Using 0 instead of `DataConstants.SIZE_NULL` when no transformer is defined resulting in a calculated size discrepancy of -1.
- Using `DataConstants.INT` instead of `DataConstants.SIZE_INT` for the number of transformer properties resulting in a calculated size discrepancy of +2 when using a configuration with a transformer.
- Using `BufferHelper.sizeOfNullableBoolean` instead of `DataConstants.SIZE_BOOLEAN` for the `exclusive` property resulting in a calculated discrepancy of +1.
- Encoding was using `writeString` instead of `writeNullableString` for the name of the transformer class resulting in an actual buffer size discrepancy of -1.

ARTEMIS-4910 fix divert config encoding

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedPagedFailoverTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/ReplicatedBothNodesMirrorTest.java

Small change but say there's ever a leak on the journal. Removing the clause from paging would allow to also capture other leaks.
This is currently not an issue and the test should still pass.

ARTEMIS-4925 Making assertion to also consider journal and other files from the broker

---

tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cluster/failover/ReplicatedFailoverTest.java

Removing redundant verification that was just spending time and not being verified.

NO-JIRA Speeding up test

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ConfirmationWindowTest.java

If, for whatever reason, the response for a packet sent with blocking semantics is never returned it's possible that an async response received in the interventing time will be interpreted as the current response. This is because ChannelImpl does not verify the correlation ID set on the response packet when it is received.

ARTEMIS-4936 verify response correlationId when using Core client

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImplTest.java

The `ManagementService` is used by the broker to register and unregister components for management as well as send notifications. When the broker is busy dealing with new sessions and auto-creating queues, addresses, etc. there is a lot of contention.
To reduce synchronization and improve the service overall this commit does the following:
- Remove `synchronized` from most methods. In most cases it's completely unnecessary because the methods are already using a thread-safe data-structure (e.g. `ConcurrentHashMap`) or more specific synchronization is already in place (e.g. on `mbeanServer`).
- Adds new & clarifies existing logging.
- Synchronizes `start` & `stop` methods and adds gates via `started`.
- Simplifies the `sendNotification` method by synchronizing once rather than twice and …

ARTEMIS-4923 reduce synchronization in ManagementServiceImpl

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMXManagementTest.java

When counting messages with provided filters and grouping use the API getObjectPropertyForFilter which translates values from AMQP message annotations that are otherwise missed by the filters.

ARTEMIS-4952 Use getObjectPropertyForFilter when applying filters

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQSession.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/BasicSecurityTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/openwire/SecurityOpenWireTest.java

Check that an attaching Openwire producer has SEND permission on the target destination and reject it if it does not instead of delaying checks until the actual send. For anonymous producers check early in the send process to reduce overhead in the JVM handling messages that are going to fail to send.

ARTEMIS-4963 Check send auth on openwire producer create

---

scripts/cherry-pick-report.sh

A shebang only has an effect when it appears as the first line in a script.

NO-JIRA  Remove first empty line from cherry-pick-report.sh

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonServerReceiverContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpTargetedFQQNSecurityTest.java

When using targeted FQQN permissions the AMQP sender needs to check that it can access not only the address but also the queue if sent an FQQN so that the security can validate if the sender has been granted directed access to the FQQN as a whole.

ARTEMIS-4969 Ensure AMQP senders can target FQQN if authorized

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java

see https://issues.apache.org/jira/browse/ARTEMIS-4909

ARTEMIS-4909 use names that match original xml tags

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/InstallAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Upgrade.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis.cmd
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis-utility.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis-utility.profile.cmd
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/log4j2-utility.properties
artemis-cli/src/test/java/org/apache/activemq/cli/test/StreamClassPathTest.java
docs/migration-guide/_configuration.adoc
docs/user-manual/logging.adoc
docs/user-manual/perf-tools.adoc
docs/user-manual/upgrading.adoc
docs/user-manual/versions.adoc
tests/smoke-tests/pom.xml
tests/smoke-tests/src/main/filtered-resources/servers/linuxUpgradeETC/artemis.profile
tests/smoke-tests/src/main/filtered-resources/servers/windowsUpgrade/bin/artemis-service.xml
tests/smoke-tests/src/main/filtered-resources/servers/windowsUpgradeETC/artemis.profile.cmd
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/upgradeTest/CompareUpgradeTest.java

The run command uses the artemis.profile and log4j2.properties files while all other CLI commands use the artemis-utility.profile and log4j2-default.properties files.

ARTEMIS-4785 ARTEMIS-4702 Add profile and log4j2 files for non-run CLI commands

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/Channel.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/PacketImpl.java

Fixups from review on #5145. Note I have used the original Jira reference as it seems like a respin is on the way before 2.37.0, so makes sense to be on the same Jira if so. If a new Jira is instead needed, shout.

ARTEMIS-4986: fixups for prior PR feedback

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationBaseSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueueSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationSource.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

The federation sender links can react incorrectly when the source broker closes a receiver because the demand is gone and they can result in the remote broker closing its side of the connection causing the whole federation to need to be rebuilt. Handle the closure events correctly to prevent an unexpected close and rebuild.

ARTEMIS-4998 Fix Federation link close wrongly closing the connection

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationBaseSenderController.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java

When an address consumer explicitly closes or is closed we should remove the address binding for that consumer right away instead of waiting for possible configured auto delete as the demand is gone and we don't need to binding to stick around any longer.

ARTEMIS-5004 Clean up federation address consumer bindings proactively

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/Consumer.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/ConsumerThread.java
artemis-cli/src/test/java/org/apache/activemq/cli/test/CliConsumerTest.java

The test here is just a sanity check to ensure an input of `-1` is parsed correctly. There's no real way to functionally test that the consumer will wait forever.
I'm open to ideas about improving the test so please give feedback.

ARTEMIS-4834 support consuming messages forever with CLI

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/io/OperationConsistencyLevel.java
artemis-journal/src/main/java/org/apache/activemq/artemis/core/journal/collections/JournalHashMap.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AckManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/MirrorTransaction.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonAbstractReceiver.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/OperationContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/StorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/DummyOperationContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/OperationContextImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/nullpm/NullStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/persistence/impl/journal/OperationContextUnitTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImplTest.java
tests/db-tests/src/test/java/org/apache/activemq/artemis/tests/db/paging/PagingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/SendAckFailTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/DuplicateCacheTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/brokerConnection/MirrorInfiniteRetryReplicaTest.java

…rror send operations.
Send operations should ignore replication, while the ack of the message should wait a round trip in replication. That will allow us to ack the message faster and still have consistency with its replica.

ARTEMIS-5001 Relax consistency requirement on OperationContext for Mirror send operations.

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/group/impl/LocalGroupingHandler.java

The start() method should use a lock to access the expectedBindings variable to ensure thread safety, since other methods use the lock and interact with expectedBindings at the same time.
Using the lock in the start() method ensures that access to the expectedBindings variable is safe in a multi-threaded environment, preventing potential thread contention issues.
[ARTEMIS-4972](https://issues.apache.org/jira/browse/ARTEMIS-4972)

ARTEMIS-4972 Use Lock in start() for Binding Variables

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/NettyConnector.java

… on command line
same behaviour as server library
https://github.com/apache/activemq-artemis/commit/127ce3a84a99f4fcf95320de064e98d91e776e4c

ARTEMIS-5013 do not override Netty leak detection

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AckManager.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/ReplicatedBothNodesMirrorTest.java

AckManager.flush would hold a lock on ackManager, There was a possible deadlock with MirrorTarget:
Thread 1:
at org.apache.activemq.artemis.protocol.amqp.connect.mirror.AckManager.addRetry(AckManager.java:393)
- waiting to lock <0x00000007990a13e8> (a org.apache.activemq.artemis.protocol.amqp.connect.mirror.AckManager)
at org.apache.activemq.artemis.protocol.amqp.connect.mirror.AckManager.ack(AckManager.java:418)
at org.apache.activemq.artemis.protocol.amqp.connect.mirror.AMQPMirrorControllerTarget.performAck(AMQPMirrorControllerTarget.java:479)
at org.apache.activemq.artemis.protocol.amqp.connect.mirror.AMQPMirrorControllerTarget.postAcknowledge(AMQPMirrorControllerTarget.java:461)
at org.apache.activemq.artemis.protocol.amqp.connect.mirror.AMQPMirrorControllerTarget.actualDelivery(AMQPMi …

ARTEMIS-5010 Addressing deadlock on AckManager

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPLargeMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPStandardMessage.java
artemis-protocols/artemis-amqp-protocol/src/test/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPPersisterTest.java
tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/AmqpSender.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpMessagePriorityTest.java

Ensure that on server restart the original priority value assigned to an AMQP message is used when dispatching durable messages from the store. The AMQP Header section is scanned if present and the priority value is recovered in an efficient manner.

ARTEMIS-5032 Ensure AMQP message priority is honored after restart

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPMessage.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpReplayFromRetentionTest.java

When using the replay functionality the application of filters to the replayed messages fails to match against AMQP messages due to the message not getting scanned when some message values are accessed.

ARTEMIS-4978 Fix AMQP messages not matching selector on replay

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java

Avoid a NullPointerException that can occur on openwire reconnections.
Seen stack trace :
```
Errors occurred during the buffering operation : java.lang.NullPointerException
at org.apache.activemq.artemis.core.protocol.openwire.OpenWireConnection$CommandProcessor.processAddSession(OpenWireConnection.java:1491)
at org.apache.activemq.command.SessionInfo.visit(SessionInfo.java:66)
at org.apache.activemq.artemis.core.protocol.openwire.OpenWireConnection.act(OpenWireConnection.java:366)
at org.apache.activemq.artemis.core.protocol.openwire.OpenWireConnection.bufferReceived(OpenWireConnection.java:309)
at org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl$DelegatingBufferHandler.bufferReceived(RemotingServiceImpl.java:723)
at …
```

Avoid NPE on method processAddSession in OpenWireConnection

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/ServerSessionPacketHandler.java
artemis-unit-test-support/src/main/java/org/apache/activemq/artemis/utils/Wait.java
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/tests/util/ActiveMQTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/largemessages/AmqpEmbeddedLargeCoreMessageClusterTest.java

When an AMQP message is sent over a cluster bridge it is embedded into a Core message. If the size of the AMQP message is barely beneath the minLargeMessageSize then the Core message in which the AMQP message is embedded will become a large message. The on the bridge target when the embedded AMQP message is extracted from the large Core message it will not be considered "large." In this situation the file for the large Core message will leak.
Thanks to Erwin Dondorp for the test. I renamed and refactored it a bit, but the fundamentals came from Erwin.

ARTEMIS-4781 Clustering not-large AMQP message can leak Core large message file

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/FileUtil.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/EmptyList.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/LinkedListImpl.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/NodeStore.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/PriorityLinkedList.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/PriorityLinkedListImpl.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/ReferenceNodeStore.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/logger/ActiveMQAMQPProtocolLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageSubscriptionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/list/PriorityLinkedListTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/RoutingContextTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/fakes/FakeQueue.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/AccumulatedInPageSoakTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/LogAssert.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/server/impl/QueueImplTest.java

PriorityLinkedList has multiple sub-lists, before this commit PriorityLinkedList::setNodeStore would set the same node store between all the lists.
When a removeWithID was called for an item on list[0] the remove from list[4] would always succeed first. This operation would work correctly most of the time except
when tail and head is being used. Many NullPointerExceptions would be seen while iterating on the list for remove operations, and the navigation would be completely broken.
A test was added to PriorityLinkedListTest to make sure the correct lists were used however I was not able to reproduce the NPE condition in that test.
AccumulatedInPageSoakTest reproduced the exact condition for the NPE when significant load is used.

 ARTEMIS-5038 Mirrored ACKs are broken if using multiple priorities on producers

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java

Throwing an exception when clearing the bindings when a cluster-connection is closed short-circuits the clearing (and closing) process. This commit fixes that by simply logging the failure to clear and continues on.
No new tests are added with this commit. It relies on existing tests.

ARTEMIS-5042 don't throw Exception when clearing cluster-connection bindings

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/config/ActiveMQDefaultConfiguration.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AckManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/logger/ActiveMQAMQPProtocolLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/Configuration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AckManagerTest.java

I am adding an option to configuration to log warns when messages are unbacked. By default the system will still no log.warn.

ARTEMIS-4971 Warning on Unacked messages through mirror AckManager

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/xml/XmlDataExporter.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/xml/XmlDataImporter.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ManagementHelper.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/codec/PersistentQueueBindingEncoding.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/persistence/XmlImportExportTest.java

This will allow users eventually undoing mistakes after removing a queue by accident.

ARTEMIS-5097 Allow export and import data of undefined queues

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/TransportConstants.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/ProtocolHandler.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/protocol/websocket/WebSocketServerHandler.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/protocol/websocket/WebSocketServerHandlerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpWebSocketConnectionTest.java

Adds support for WebSocket compression using the netty server handler to enable per message compression and decompression as a transparent layer of the netty pipeine.

ARTEMIS-2748 Support WebSocket compression in the transport pipeline

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Mask.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/log4j2-utility.properties
artemis-commons/src/main/java/org/apache/activemq/artemis/logs/ActiveMQUtilLogger.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/DefaultSensitiveStringCodec.java
artemis-commons/src/main/java/org/apache/activemq/artemis/utils/PasswordMaskingUtil.java
artemis-commons/src/test/java/org/apache/activemq/artemis/utils/DefaultSensitiveStringCodecTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationParserTest.java
docs/user-manual/masking-passwords.adoc
docs/user-manual/versions.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ra/ResourceAdapterTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/ssl/CoreClientOverOneWaySSLTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/remoting/impl/netty/NettyConnectorTest.java

Throughout the years, the standard mechanism for storing passwords has evolved. In the beginning, passwords were stored in plaintext. Developers are now encouraged to leverage adaptive one-way functions to store a password. Using a two-way function by default for storing passwords without a warning could lead users to a false sense of security.

ARTEMIS-5101 Deprecate default codec two-way algorithm

---

artemis-distribution/src/main/assembly/dep.xml
docs/user-manual/versions.adoc

This particular change will be moot when we integrate the new console, but we should do something similar at that point.

ARTEMIS-5096 exclude unnecessary jars from console war

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/plugin/BeforeSendPluginTest.java

If an exception is thrown in the AMQP send path and there is an active transaction we should mark that as rollback only so the client will see an error when it tries to commit a transaction that had a failed send.

ARTEMIS-5106 Mark any AMQP TXN as rollback on send exceptions

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressConsumer.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

Prevents unintended link stealing scenarios when link names match for a new link whose name is in use by another link still awaiting a detach response.

ARTEMIS-5135 Use a sequence ID on address federation link names

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java

When you start the broker without configuring HAPolicy, if clients call this management api it'll get NPE because it doesn't check if the HAPolicyConfiguration is null.

ARTEMIS-5150: ActiveMQServerControlImpl.getHAPolicy() gets NPE

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/AMQPSessionCallback.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationCommandDispatcher.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationEventDispatcher.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java

In order to better indicate their nature as broker feature specific queues we can mark the temporary queues created for AMQP federation events and control link messages as internal.

ARTEMIS-5153 Mark federation events and control queues as internal

---

artemis-log-annotation-processor/src/main/java/org/apache/activemq/artemis/logs/annotation/processor/LogAnnotationProcessor.java
artemis-log-annotation-processor/tests/pom.xml
artemis-log-annotation-processor/tests/src/test/java/org/apache/activemq/artemis/logs/annotation/processor/LogAnnotationProcessorTest.java
artemis-log-annotation-processor/tests/src/test/resources/org/apache/activemq/artemis/logs/annotation/processor/cases/LAPTCase1_InvalidIDForRegex.java
artemis-log-annotation-processor/tests/src/test/resources/org/apache/activemq/artemis/logs/annotation/processor/cases/LAPTCase2_InvalidIDReused.java
artemis-log-annotation-processor/tests/src/test/resources/org/apache/activemq/artemis/logs/annotation/processor/cases/LAPTCase3_InvalidIDRetired.java
artemis-log-annotation-processor/tests/src/test/resources/org/apache/activemq/artemis/logs/annotation/processor/cases/LAPTCase4_InvalidIDRetiredWithGap.java
artemis-log-annotation-processor/tests/src/test/resources/org/apache/activemq/artemis/logs/annotation/processor/cases/LAPTCase5_InvalidRetiredID.java
artemis-log-annotation-processor/tests/src/test/resources/org/apache/activemq/artemis/logs/annotation/processor/cases/LAPTCase6_UnsortedRetiredID.java
artemis-pom/pom.xml
pom.xml

Add testing of various validations/suggestions introduced in previous changes for the Jira. Also improves an error message to report the LogBundle class like others do.

ARTEMIS-5110: tests for ID validations in log annotation processor

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/QueueControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/QueueControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/RoutingContextTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/impl/ScheduledDeliveryHandlerTest.java
tests/artemis-test-support/src/main/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/fakes/FakeQueue.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ManagementWithPagingServerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/QueueControlUsingCoreTest.java

This exposes a copyMessage method that simply copies a message to a different queue so the new console can add a copy button

ARTEMIS-5131 Add A Copy message button to console

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Shell.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Connect.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Disconnect.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/messages/ConnectionConfigurationAbtract.java

This PR adds back connect + disconnect to shell
Changes prompt to reflect if connected to a broker (and which one)
It also captures "Ctrl + D" to return to shell if issued when connected to a broker (instead of exiting). If not connected it exits as usual.

ARTEMIS-5168 Improve remoting to brokers from Artemis shell

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/security/impl/SecurityStoreImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/security/impl/SecurityStoreImplTest.java

When the ArtemisRbacMBeanServerBuilder class is used for the RBAC management, a clash of authentication cache keys between clients failing authentication and web console authenticated users can cause web console authenticated users to receive authorization errors, blank screens and similar issues after successful login to the console.

ARTEMIS-5187 Fix management authorization checks after authentication failures

---

.github/dependabot.yml
.github/workflows/build.yml
artemis-cdi-client/pom.xml
artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/SimpleString.java
artemis-features/pom.xml
artemis-log-annotation-processor/src/main/java/org/apache/activemq/artemis/logs/annotation/processor/LogAnnotationProcessor.java
artemis-website/pom.xml
docs/user-manual/versions.adoc
pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/JMSClientTestSupport.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/RedeliveryConsumerTest.java

This commit drops support for Java 11. All code changes were related to output from ErrorProne that prevented the build from completing.

ARTEMIS-5202 require Java 17+ (i.e drop support for Java 11)

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientConsumerImpl.java

*  Ensure that the temproray large message content can only be read by the user associated with the process.
* Fixing initial ARTEMIS-5172 PR which wasn't removing rw permissions.
Issue: https://issues.apache.org/jira/browse/ARTEMIS-5172

ARTEMIS-5172: Reduce the permissions on temp file.

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressSettingsInfo.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/deployers/impl/FileConfigurationParser.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/AddressSettings.java
artemis-server/src/main/resources/schema/artemis-configuration.xsd
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImplTest.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/settings/AddressSettingsTest.java
artemis-server/src/test/resources/ConfigurationTest-full-config.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-config-address-settings.xml
artemis-server/src/test/resources/ConfigurationTest-xinclude-schema-config-address-settings.xml
docs/user-manual/address-settings.adoc
docs/user-manual/message-expiry.adoc
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSMessageExpiryTest.java

@gemmellr, take a look at this as a potential replacement for #5334. I feel like this is much simpler and more intuitive.

ARTEMIS-5142 support never expiring incoming messages

---

artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java

When the broker is started on Windows Jetty logs an exception at DEBUG level regarding a malformed URL which is set via the setBaseResourceAsString method on either
org.eclipse.jetty.server.handler.ResourceHandler or org.eclipse.jetty.server.handler.ContextHandler.
This commit fixes that by using setBaseResourceAsPath instead. It also removes 2 instances of setBaseResourceAsString on the ResourceHandler. These are not necessary because the value set on the ContextHandler will suffice.

ARTEMIS-5226 Jetty choking on bad URI

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java

The `transportConnection` variable will always be `null` so there's no use in checking it.

ARTEMIS-5147 eliminate unnecessary check

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java

The `server` variable is used liberally through this `Queue` implementation. It makes sense to require it to be non-null.

ARTEMIS-5094 potential null dereference in QueueImpl

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/protocol/websocket/WebSocketServerHandler.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/protocol/websocket/WebSocketServerHandlerTest.java

The broker should simply receive WebSocket pong frames and not respond according to section 5.5.3 of RFC 6455 (i.e. the WebSocket Protocol specification).

ARTEMIS-5249 support WebSocket pong frames

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ChannelImpl.java

The `connection` variable is used liberally throughout `ChannelImpl` and it is never set to `null`. Therefore, it should never be `null` and we can dispense with unnecessary checks for `null`.

ARTEMIS-5115 remove needless null checks in ChannelImpl

---

docs/hacking-guide/_tests.adoc
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/console/ConsoleTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/console/LoginTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/console/QueuesTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/console/RootTest.java
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/console/TabsTest.java

Support the system property `webdriver.browsers` to customize the list of browsers to execute the console smoke tests.

ARTEMIS-5258 Customize browsers to execute console smoke tests

---

artemis-docker/Dockerfile-alpine-21
artemis-docker/Dockerfile-alpine-21-jre
artemis-docker/Dockerfile-ubuntu-21
artemis-docker/Dockerfile-ubuntu-21-jre

Port 9404 is exposed in all the Docker files. This port is for the Prometheus JMX Exporter which we have never used. We recommend folks use the Prometheus metrics plugin instead which is available on the normal HTTP port (i.e. 8161).

ARTEMIS-5259 don't expose port 9404 in Docker

---

artemis-docker/Dockerfile-alpine-21
artemis-docker/Dockerfile-alpine-21-jre
artemis-docker/Dockerfile-ubuntu-21
artemis-docker/Dockerfile-ubuntu-21-jre

JMX Exporter is long gone and pipes are not used in the scripts anymore. Plus, some other minor adjustments.
P.S. Next bash could probably also be removed from Alpine images to keep them small as the whole point of Alpine images are small size. I didn't do tests at the moment, but quickly looking at docker-run.sh and prepare-docker.sh didn't find anything requiring bash.

ARTEMIS-5263 Remove unused Docker directive

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueueConsumer.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java

When a pull mode federation consumer is stopped due to demand being removed and the credit tup-up handler is also awaiting the Queue backlog to clear in order to grant a new batch of credit it might exit that cycle an leave the in-progress flag set to true. Currently this likely won't trigger a stuck consumer but if the code was to be altered to hold open a link for some period of time before fully closing in order to avoid needless attach / detach cycles then it would be possible for the credit replenishment to get stuck because the previous attempt left the in-progress flag set to true.

ARTEMIS-5215 Credit handler reset in progress flag when stopped

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ObjectNameBuilder.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/RemoteBrokerConnectionControl.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ResourceNames.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPBrokerConnectionConstants.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/AMQPRemoteBrokerConnection.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederation.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConfiguration.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConstants.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationManagementSupport.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationPolicySupport.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationTargetControlType.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/FederationReceiveFromAddressPolicy.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/federation/FederationReceiveFromQueuePolicy.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPSessionContext.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/RemoteBrokerConnectionControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/BrokerConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/RemoteBrokerConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/ManagementService.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/management/impl/ManagementServiceImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/server/group/impl/ClusteredResetMockTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationManagementTest.java

Provide remote broker connections management beans that mirror the management objects added on the local broker when AMQP federation is configured and the connection is active.

ARTEMIS-5279 Add remote federation views to management services

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/test/java/org/apache/activemq/artemis/cli/commands/CreateTestIndividualSettings.java

I struggled to decide the name of the input, ultimately settling on `--aio-journal-max-io` to clarify that it only applies to `journal-max-io` when using aio.

ARTEMIS-5100 support journal-max-io on 'create' CLI command

---

artemis-commons/src/main/java/org/apache/activemq/artemis/utils/collections/TypedProperties.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/message/impl/CoreMessage.java

Back in 8e40b2d4f4f242271d3dfcda4f9b96d3f94cee1b thread safety was added to TypedProperties by synchronizing all relevant methods. This was simple and effective but suffers from performance issues in read-heavy use-cases.
This commit improves the performance by using a read/write locking mechanism so reads can execute concurrently.
No new tests were added since the original commit added tests to verify thread safety.

ARTEMIS-5139 improve locking on TypedProperties

---

artemis-bom/pom.xml
artemis-cdi-client/src/main/java/org/apache/artemis/client/cdi/extension/ArtemisClientConfigBean.java
artemis-cdi-client/src/main/java/org/apache/artemis/client/cdi/extension/ArtemisEmbeddedServerConfigBean.java
artemis-jakarta-cdi-client/pom.xml
artemis-jakarta-cdi-client/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
artemis-pom/pom.xml
pom.xml

This PR introduces `artemis-jakarta-cdi-client`, a Jakarta (i.e. Jakarta EE 9+) equivalent of `artemis-cdi-client`. The new module is based on `artemis-cdi-client` with all necessary changes to make it jakarta-compatible. No other changes were made. You can review the individual steps in the commit history.
I will also post about this on the dev mailing list  and would appreciate any feedback.

ARTEMIS-5292 introduce jakarta version of artemis-cdi-client

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/QueueConfiguration.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/ClientSession.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/client/TopologyMember.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/config/TransformerConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/BridgeConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/DivertConfiguration.java
pom.xml

There are number of warnings related to JavaDoc during the build. This commit adjusts a handful of specifica JavaDoc comments to eliminate warnings about empty `<p>` tags. It also modifies the configuration of the Maven JavaDoc plugin to categorically prevent warnings about "missing" JavaDoc comments on public methods, etc.

ARTEMIS-5312 reduce build-time warnings for JavaDoc

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/PrintData.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/xml/XmlDataExporter.java
artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/QueueConfiguration.java
artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/SimpleString.java
artemis-commons/src/test/java/org/apache/activemq/artemis/utils/SimpleStringTest.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/core/server/QueueQueryResult.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/QueueBindingInfo.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/AbstractJournalStorageManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/persistence/impl/journal/codec/PersistentQueueBindingEncoding.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/PostOfficeJournalLoader.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueConfigurationUtils.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/persistence/impl/journal/QueueBindingEncodingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/QueueQueryTest.java

There are several places across the code-base that repeat all the configuration parameters of a queue. This commit simplifies the code and increases readability by using o.a.a.a.a.c.QueueConfiguration as often as possible.

ARTEMIS-5302 use QueueConfiguration more

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConfiguration.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java

Adjust the configuration for consumer priority handling to an opt in policy for creating multipe differing priority federation receivers such that if a user configures bi-directional federation and enabled ignore federation receivers they wouldn't end up with an infinite reflection of receivers.

ARTEMIS-5339 Adjust configuration to avoid federation receiver loops

---

artemis-commons/src/main/java/org/apache/activemq/artemis/logs/AuditLogger.java
artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/broker/ProtonProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AMQPMirrorControllerTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AckManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AckManagerProvider.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/ProtonAbstractReceiver.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/mirror/MirrorRegistry.java
artemis-unit-test-support/src/main/java/org/apache/activemq/artemis/utils/Wait.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AckManagerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlUsingCoreTest.java
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/brokerConnection/mirror/AccumulatedInPageSoakTest.java

Say there are too many records in the JournalHashMap. In that case the sender should pace sending more data. The target should limit credits when the configured max pending records is reached.

ARTEMIS-5338 AckManager flow control

---

artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireConnection.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/config/WildcardConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/SimpleAddressManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerSessionImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/HierarchicalObjectRepository.java
artemis-server/src/test/java/org/apache/activemq/artemis/core/config/WildcardConfigurationTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/jms/multiprotocol/JMSMessageConsumerTest.java

Most protocols don't natively understand the address/queue model used by Artemis. When those protocols want anycast semantics the standard behavior is to create an address and a queue with the same name. However, sometimes a queue already exists on the address with that particular name in which case the broker will attach the consumer to that queue.
This is acceptable most of the time, but it is problematic when that queue uses a wild-card. In this case the consumer will potentially receive messages sent to other addresses (i.e. whatever the wild-card covers).
This commit fixes that by detecting the wild-card queue and ignoring it. Instead the broker will create a new queue specifically for the incoming consumer.

ARTEMIS-5337 consumer + auto-create receives from existing wildcard queue

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/api/core/management/AddressControl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/ActiveMQServerControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/AddressControlImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/ActiveMQAbstractView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/AddressField.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/AddressView.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/predicate/AddressFilterPredicate.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/management/impl/view/predicate/QueueFilterPredicate.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/ActiveMQServerControlTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/management/AddressControlUsingCoreTest.java

There are a number of attributes available via AddressControl that are not available on AddressView. These two classes should be harmonized so that, e.g. the web console's "Addresses" tab can have the same details as the JMX MBean view and vice versa.

ARTEMIS-5351 harmonize AddressControl and AddressView

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConsumerManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueuePolicyManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ServerConsumer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationQueuePolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/cli/DummyServerConsumer.java

When passing along a federation queue consumer that matches the includes of a federation queue policy retain the original consumer priority so that if the consumers loop the propagation will stop at the source that started the loop.

ARTEMIS-5368 Propagate Federation consumer priority unchanged

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/impl/PageTimedWriter.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/Transaction.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/transaction/impl/TransactionImpl.java
tests/soak-tests/src/main/resources/servers/validate-page-tx/broker.xml
tests/soak-tests/src/test/java/org/apache/activemq/artemis/tests/soak/paging/ValidatePageTXTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/paging/impl/PageTimedWriterUnitTest.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/postoffice/impl/BindingsImplTest.java

This is a regression after ARTEMIS-5305 / 24d1bbe603cadb6666a7992e296e6f94ae68e3a1
The commit record could reach the journal before the paged data.
This commit is delaying the write of the journal until all the data for the transaction has reached the storage.

ARTEMIS-5379 Delay journal transaction until page data is stored

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederation.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressConsumer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressSenderController.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationCapabilities.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationCommandProcessor.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConstants.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueueConsumer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationSource.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationTarget.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/proton/AMQPSessionContext.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java

When subscribing a federation address consumer a stable subscription queue name must be used to ensure that reconnections recover past subscriptions and consume messages sent while the receiver was offline. This also supports connections to previous versions where this was not done to ensure full backwards and forwards compatibility on federation configurations.

ARTEMIS-5381 Use a stable FQQN for federation address receivers

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressSenderController.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java

If the remote used an FQQN to define the address and stable subscription for the address consumer recover the subscription from the FQQN when the remote closes the consumer due to demand having been removed on the remote for that address.

ARTEMIS-5381 Use FQQN to remove federation address subscription if set

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ServerConsumerImpl.java

The previous fix adds a case were a deadlock can occur during server stop or stop of the federation is the federation is also handling a reconnect and a tracked server consumer is closing, this fix adjusts the locking logic to avoid that deadlock.

ARTEMIS-5381 Fix possible deadlock on federation or server stop

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/HierarchicalObjectRepository.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/settings/impl/NamedHierarchicalRepositoryChangeListener.java

This commit improves performance specifically for removing listeners from o.a.a.a.c.s.i.HierarchicalObjectRepository. It was previously using an ArrayList and the cost to remove an Object is O(n) on average whereas the same operation on a HashSet is O(1) on average assuming good hash values. Furthermore, the list was protected using a ReentrantReadWriteLock. However, by using a ConcurrentHashSet we can eliminate these locks further improving performance.
Switching to a ConcurrentHashSet required a few changes to the listeners themselves to ensure they have good hashCodes, etc.

ARTEMIS-5383 performance issues with HierarchicalRepositoryChangeListener

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/ActiveMQException.java

I hope that I'm not breaking any backward compatibility here but it would be great to have a full package name in the exception header. Currently Artemis exceptions only include the short name of the exception. On logging systems where exceptions are caught and tracked if they are repeating errors (like for example Google Error Reporting), this groups different Artemis exceptions into single error group.
See https://github.com/apache/logging-log4j2/pull/3586#discussion_r2044006120 for more information and screenshots.

ARTEMIS-5434 Use full exception name in exceptions

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/mirror/AckManagerProvider.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServer.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/leak-tests/src/test/java/org/apache/activemq/artemis/tests/leak/AckManagerLeakTest.java

When the broker starts with AMQP protocol support an AckManager instance is automatically created and added to the broker's list of "external components." However, this component is not removed when the broker is stopped (e.g. when an active backup shuts down due to fail-back). Over time these instances can accumulate and cause memory issues.

ARTEMIS-5446 AckManager instances leaking on backup

---

docs/user-manual/message-expiry.adoc

This also:
- makes the "Configuring Expiry Addresses" section the first section dealing with broker config
- fixes a few grammar/wording issues

ARTEMIS-5468 clarify docs on expiring messages from queue on expiry address

---

artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSession.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionCallback.java
artemis-protocols/artemis-mqtt-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/mqtt/MQTTSessionState.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/mqtt5/MQTT5Test.java

The previously committed solution to this problem caused `testPacketIdGeneratorNonCleanSession` in `o.a.a.a.t.i.m.MQTTTest` to fail. The problem with that solution is that it cleared out too much state.
This commit fixes that by only clearing out the send quota and leaving the other state in tact.

ARTEMIS-5469 reformulate previous solution

---

artemis-commons/src/main/java/org/apache/activemq/artemis/api/core/QueueConfiguration.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/server/ConfigurationTest.java

The queue configs loaded from broker properties use the queue name as the default value for the address if it is not set. Enforcing the queue address with the parent address before deploying them removes the requirement to set the address when it doesn't match the queue name.

ARTEMIS-5485 Enforce the queue address before deploying

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/paging/cursor/impl/PageSubscriptionImpl.java

Remove code that has been unreachable since original donation so should not have any side effect at this point.

ARTEMIS-4967 Remove unreachable code

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Upgrade.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis-service.xml
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis.cmd
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis-utility.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis-utility.profile.cmd
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile.cmd
artemis-cli/src/test/java/org/apache/activemq/artemis/util/JVMArgumentTest.java
tests/e2e-tests/src/main/resources/containerService/artemis.profile
tests/smoke-tests/src/main/filtered-resources/servers/windowsUpgrade/bin/artemis-service.xml
tests/smoke-tests/src/test/java/org/apache/activemq/artemis/tests/smoke/upgradeTest/CompareUpgradeTest.java

This commit cleans up the various scripts and profile files via the following changes:
- Remove ARTEMIS_INSTANCE_URI from all profiles since it is no longer used after we moved to Log4j2
- Remove ARTEMIS_INSTANCE_ETC_URI from all profiles; it is not necessary because the jolokia-access.xml can be loaded directly from the classpath
- Remove ARTEMIS_ETC_DIR from all profiles and instead rely on ARTEMIS_INSTANCE_ETC which is already being set in the scripts
- Remove unnecessary code from Create command
- Remove ARTEMIS_OOME_DUMP from the utility profiles since it's not used
- Adjust Upgrade command & related tests
- Fix Windows service file so it uses the same memory settings as the other configs
- Update the Windows' profile JAVA_ARGS to match those from Linux

ARTEMIS-5364 clean up scripts & profiles

---

.github/workflows/build.yml
pom.xml
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/transport/failover/FailoverConsumerOutstandingCommitTest.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/transport/failover/FailoverDuplicateTest.java
tests/activemq5-unit-tests/src/test/java/org/apache/activemq/transport/failover/FailoverPrefetchZeroTest.java

Update to errorprone 2.40.0.
Also Builds, but doesnt run, the optional activemq5-unit-tests module in check builds > JDK17 to more consistently fail across all runs. Removes unused methods / reduces visibility to appease errorprone checks for broken JUnit 4 test method definitions.
Replaces #5824

ARTEMIS-5582: Update to errorprone 2.40.0

---

artemis-ra/src/main/java/org/apache/activemq/artemis/ra/ActiveMQResourceAdapter.java
tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ResourceAdapterTest.java

A NullPointerException was thrown by
ActiveMQResourceAdapter.closeConnectionFactory() if called multiple times with same properties due to factory already been removed from knownConnectionFactories.
Note: this was mostly a "cosmetic" issue since exception was caught by caller in ActiveMQRAManagedConnection.destroy() and stacktrace logged
Fixed by adding proper null check and a debug log, also adding unit test proving issue is solved.

ARTEMIS-5562: Fix NPE on closeConnectionFactory

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/QueueImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/addressing/AddressingTest.java

This will log the infor earlier instead of being routed.

ARTEMIS-5621 logger.info when queue is disabled

---

artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressBindingsConsumer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressConduitConsumer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressConsumer.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationAddressPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConfiguration.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConstants.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConsumerConfiguration.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationConsumerManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationLocalPolicyManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationPolicySupport.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/connect/federation/AMQPFederationQueuePolicyManager.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPBridgeFromQueueTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationAddressPolicyTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationConnectTest.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/AMQPFederationServerToServerTest.java

Adds support to create federation receivers that carry the filter of the address binding or bindings that generated the demand on the address. This can reduce traffic across federation links if the bindings filters are sufficiently partitioning messages across consumers but can be less efficient than the default conduit subscription if poorly partitioned.

ARTEMIS-5625 Allow address federation to include bindings filters

---

artemis-server/src/main/java/org/apache/activemq/artemis/core/postoffice/impl/PostOfficeImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/connect/StopDuringMirrorTest.java

if a non transaction send happens while on mirror, the broker should upgrade the operation to an internal transaction to make sure the whole thing happens atomically.

ARTEMIS-5634 Mirror source and routing should use a TX
