activemq-dto/pom.xml
activemq-dto/src/main/java/org/apache/activemq/dto/BrokerDTO.java
activemq-dto/src/main/java/org/apache/activemq/dto/SecurityDTO.java
activemq-native/pom.xml
activemq-website/src/main/resources/index.html
distribution/activemq/pom.xml
distribution/activemq/src/main/assembly/dep.xml
distribution/activemq/src/main/resources/config/logging.properties
pom.xml

The distribution still needs some work, but this is progress worth committing.

Couple of fixes

---

pom.xml

For some reason this is not playing well with Idea. When I import the project nothing is being able to be executed.

removing apache parent for now

---

activemq-core-client/src/main/java/org/apache/activemq/core/client/ActiveMQClientMessageBundle.java
activemq-core-client/src/main/java/org/apache/activemq/core/protocol/core/impl/ChannelImpl.java
activemq-server/src/main/java/org/apache/activemq/core/remoting/server/impl/RemotingServiceImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/client/ConsumerStuckTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/cluster/bridge/BridgeTest.java

The timeout here needed to be increased to avoid test failure when isNetty=true.

Fix test, adjust logging

---

tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/client/SessionTest.java

this is to address https://builds.apache.org/job/ActiveMQ6-Nightly-Regression-Test/30/testReport/junit/org.apache.activemq.tests.integration.client/SessionTest/testQueueQuery/

fix potential race condition in test

---

activemq-rest/pom.xml
distribution/activemq/pom.xml
distribution/pom.xml
pom.xml

A few changes required to get snapshot release working and release:prepare

Release updates

---

pom.xml

and change the default profile to build the distro.
Also add enforcer rule for Java 8

upgrade to Java 8 minimum

---

activemq-server/src/main/java/org/apache/activemq/core/remoting/impl/netty/NettyAcceptor.java
activemq-server/src/main/java/org/apache/activemq/core/server/ActiveMQServerLogger.java

This replaces @andytaylor PR #122.
I've rebased and re-running PR tests as @andytaylor  is on PTO today.

improved logging on Netty Acceptor

---

activemq-core-client/src/main/java/org/apache/activemq/core/version/Version.java
activemq-core-client/src/main/java/org/apache/activemq/core/version/impl/VersionImpl.java
activemq-core-client/src/main/java/org/apache/activemq/utils/VersionLoader.java
activemq-core-client/src/main/resources/activemq-version.properties
activemq-native/pom.xml
activemq-server/src/main/java/org/apache/activemq/core/remoting/impl/netty/NettyAcceptor.java
activemq-server/src/main/java/org/apache/activemq/core/server/ActiveMQServerLogger.java
activemq-server/src/test/java/org/apache/activemq/core/version/impl/VersionImplTest.java
activemq-web/src/main/java/org/apache/activemq/component/WebServerComponent.java
pom.xml
tests/unit-tests/src/test/java/org/apache/activemq/tests/unit/util/VersionLoaderTest.java

This is fixing something I broke. The copy of the native libraries to its output.

native build is broken

---

README.md
pom.xml

Also changing the README to be in according to what's used now
Also add some wording about style on Idea

Renaming profiles to tests and fast-tests

---

examples/jms/stomp/src/main/java/org/apache/activemq/jms/example/StompExample.java

- add receiving stomp response from server.

Improve jms/Stomp example

---

activemq-jms-server/pom.xml
activemq-web/pom.xml
pom.xml
tests/integration-tests/pom.xml

Removes Duplicate deps and sets parent relative path on top level pom.

Duplicate deps

---

examples/core/embedded-remote/readme.html
examples/core/embedded/readme.html
examples/jms/proton-cpp/pom.xml
examples/jms/proton-ruby/src/main/scripts/receive.rb
examples/jms/proton-ruby/src/main/scripts/send.rb

Fix proton-cpp pom missing version
Fix proton-ruby script (update according to proton 0.8)
Fix core example doc

Fix proton-cpp pom missing version

---

docs/user-manual/en/configuration-index.md

Instead of creating anchors it's better to use the generated ID from the text.
https://github.com/gitlabhq/gitlabhq/blob/master/doc/markdown/markdown.md#alt-h2

Doc quick changes 

---

pom.xml

added some exclusions to the RAT plugin for when users build and redirect the output to log files

added some exclusions to the RAT plugin

---

RELEASING.md
pom.xml

disabled RAT plugin by default and updated the docs for releasing explaining how to enable it.

disabled RAT plugin by default

---

activemq-server/src/main/java/org/apache/activemq/core/paging/cursor/impl/PageSubscriptionImpl.java
activemq-server/src/main/java/org/apache/activemq/core/transaction/impl/TransactionImpl.java
pom.xml
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/DuplicateDetectionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/client/HangConsumerTest.java

I was looking for why the testsuite was broken, and I found these in the process

few changes I found when debugging the testsuite

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Configurable.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Stop.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/DataAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/DecodeJournal.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/EncodeJournal.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/PrintData.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/XmlDataExporter.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/tools/XmlDataImporter.java
artemis-cli/src/main/java/org/apache/activemq/artemis/factory/BrokerFactory.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/BrokerDTO.java
artemis-dto/src/main/java/org/apache/activemq/artemis/dto/ServerDTO.java

PrintData / Export and other tools are now reading default configuration from broker.xml
I also did some refactoring so Stop and Run will share some of the basic functions

Improving tools to use configuration

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Configurable.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/components/ExternalComponent.java
artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
artemis-web/src/test/java/org/apache/activemq/artemis/test/WebServerComponentTest.java

Fixing WebServer integration after created server

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/ActiveMQClientProtocolManager.java
artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/proton/ProtonProtocolManagerFactory.java
artemis-protocols/artemis-hornetq-protocol/pom.xml
artemis-protocols/artemis-hornetq-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/hornetq/HQPropertiesConversionInterceptor.java
artemis-protocols/artemis-hornetq-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/hornetq/HornetQProtocolManager.java
artemis-protocols/artemis-hornetq-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/hornetq/HornetQProtocolManagerFactory.java
artemis-protocols/artemis-hornetq-protocol/src/main/resources/META-INF/services/org.apache.activemq.artemis.spi.core.protocol.ProtocolManagerFactory
artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/OpenWireProtocolManagerFactory.java
artemis-protocols/artemis-stomp-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/stomp/StompProtocolManagerFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/CoreProtocolManager.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/protocol/core/impl/CoreProtocolManagerFactory.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/remoting/server/impl/RemotingServiceImpl.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java
artemis-server/src/main/java/org/apache/activemq/artemis/spi/core/protocol/ProtocolManagerFactory.java
tests/extra-tests/pom.xml
tests/extra-tests/src/test/java/org/apache/activemq/artemis/tests/extras/protocols/hornetq/HornetQProtocolTest.java

This is a repost of #227 with a small fix on the extra-tests/pom.xml

Hornetq protocol support

---

examples/core/perf/pom.xml
pom.xml

A couple of issues that were preventing building release profile.

Build issues

---

artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml
artemis-distribution/pom.xml
artemis-distribution/src/main/assembly/dep.xml
artemis-distribution/src/main/resources/README.html

Include HornetQ protocol in the distro and update README.

Hornetq distro

---

artemis-boot/src/main/java/org/apache/activemq/artemis/boot/Artemis.java
artemis-cli/pom.xml
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/Artemis.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Kill.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Run.java
artemis-cli/src/main/java/org/apache/activemq/artemis/integration/bootstrap/ActiveMQBootstrapLogger.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis-service.xml
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/bin/artemis.cmd
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/artemis.profile.cmd
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap.xml

- A few improvements on CLI (fixing Windows Service and adding a few options)
- Bootstrap was missing /etc on the classpath so config loaders such as JGroups wouldn't be able to load configurations

Improvements on CLI and Bootstrap

---

tests/extra-tests/pom.xml

These changes were accidentaly removed during a rebase.  Adding them back here.

Add back extra test changes accidentaly removed during rebase

---

artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/broker.xml
artemis-distribution/src/main/resources/bin/artemis

My last patch had a little flaw around libaio load (The main script is not finding the .so properly) and my configuration was wrong

Fixing libaio integration / creation

---

README.md
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/ActionAbstract.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/Create.java
artemis-cli/src/main/java/org/apache/activemq/artemis/cli/commands/InputAbstract.java
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap-web-settings.txt
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/bootstrap.xml
artemis-cli/src/main/resources/org/apache/activemq/artemis/cli/commands/etc/cluster-settings.txt
artemis-cli/src/test/java/org/apache/activemq/artemis/test/StreamClassPathTest.java
artemis-distribution/src/main/resources/README.html

--silent-input was being ignored on password. This is a little fix
I have also moved an abstract just for InputAbstract

A few fixes that I found from my work on examples
