activemq-jms-client/pom.xml
activemq-jms-server/pom.xml
activemq-protocols/activemq-amqp-protocol/pom.xml
activemq-protocols/activemq-proton-plug/pom.xml
activemq-rest/pom.xml
pom.xml
tests/byteman-tests/pom.xml
tests/jms-tests/pom.xml
tests/joram-tests/pom.xml
tests/performance-tests/pom.xml
tests/soak-tests/pom.xml
tests/stress-tests/pom.xml
tests/timing-tests/pom.xml

Geronimo now has a JMS 2 spec jar published.  I've updated the ActiveMQ 6 code base to point to it.  You were also missing apache parent, which is a requirement for apache maven based projects.

ACTIVEMQ6-40 Update to the geronimo jms 2 spec JAR.

---

activemq-server/src/main/java/org/apache/activemq/core/paging/PageTransactionInfo.java
activemq-server/src/main/java/org/apache/activemq/core/paging/cursor/PageIterator.java
activemq-server/src/main/java/org/apache/activemq/core/paging/cursor/PageSubscription.java
activemq-server/src/main/java/org/apache/activemq/core/paging/cursor/impl/PageSubscriptionImpl.java
activemq-server/src/main/java/org/apache/activemq/core/paging/impl/PageTransactionInfoImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/paging/PagingSendTest.java

The redelivery list was not isolated on the PageIterator. This is moving the
redelivery list to the Iterator so we would have proper isolation of the functionality.
The previous version was assuming a single instance of PageIterator, QueueImpl and PageSubscription.
When we started using more than one instance of the Iterator we created this bug.

ACTIVEMQ6-64 Messages duplicated during ScaleDown or queue.totalIterator()

---

tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/ra/OutgoingConnectionTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/ra/OutgoingConnectionTestJTA.java

Some of the outgoing connection tests require a dummy transaction
manager to setup a fake transaction.  The default transaction manager is
set to the JBoss TX manager and so the tests were failing.  This patch
split the OutgoingConnectionTest into ones that require a real TM
manager vs Dummy TM Manager.
.

Fix failing RA OutgoingConnectionTests

---

README.md
examples/jms/jms-bridge/pom.xml
pom.xml
tests/pom.xml
tests/unit-tests/pom.xml

This patch moves test dependencies into out of the main pom and into the
tests module pom.  This will make managing 3rd party category X
dependencies much easier going forward.  In addition each dependency
license has been outlined in the pom and README entry added to outline
future policy when adding 3rd party depdendencies.

Rework dependency management in top level poms

---

pom.xml

These are necessary because for some reason the Apache CI build doesn't recognize all the keystores as binary and it's choking on them.

A few more excludes for RAT plugin

---

activemq-server/src/main/java/org/apache/activemq/core/server/impl/QueueImpl.java

https://issues.apache.org/jira/browse/ACTIVEMQ6-71
remove the intermediateReference iterator as these may be moved anyway

ACTIVEMQ6-71 - fix duplicates in TotalQueueIterator

---

activemq-core-client/src/main/java/org/apache/activemq/api/config/ActiveMQDefaultConfiguration.java
activemq-server/src/main/java/org/apache/activemq/core/config/Configuration.java
activemq-server/src/main/java/org/apache/activemq/core/config/impl/ConfigurationImpl.java
activemq-server/src/main/java/org/apache/activemq/core/deployers/impl/FileConfigurationParser.java
activemq-server/src/main/java/org/apache/activemq/core/remoting/server/RemotingService.java
activemq-server/src/main/java/org/apache/activemq/core/remoting/server/impl/RemotingServiceImpl.java
activemq-server/src/main/java/org/apache/activemq/core/server/impl/ActiveMQServerImpl.java
activemq-server/src/main/resources/schema/activemq-configuration.xsd
activemq-server/src/test/java/org/apache/activemq/core/config/impl/DefaultsFileConfigurationTest.java
activemq-server/src/test/java/org/apache/activemq/core/config/impl/FileConfigurationTest.java
activemq-server/src/test/resources/ConfigurationTest-full-config.xml
docs/user-manual/en/SUMMARY.md
docs/user-manual/en/configuration-index.md
docs/user-manual/en/graceful-shutdown.md
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/server/GracefulShutdownTest.java

Implements a feature whereby the broker will not shutdown while there are
clients connected. A timeout can be specified so that even if there are
clients connected the broker will still shutdown after a certain time.

ACTIVEMQ6-52 Graceful shutdown

---

activemq-jms-server/src/main/java/org/apache/activemq/jms/bridge/impl/JMSBridgeImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/jms/bridge/JMSBridgeTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/jms/bridge/TransactionManagerLocatorImpl.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/util/JMSTestBase.java

A transaction manager is only required on the JMSBridge when the QoS
level is set to ONCE_AND_ONCE_ONLY.  Previous to the this patch it was
also checking for a TM on the AT_MOST_ONCE QoS level.  This patch also
ensures that the TM is set to null after each test run.

Only check TM exists for JMSBridge with ONCE_ONLY

---

tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/cluster/distribution/ClusterTestBase.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/persistence/DuplicateCacheTest.java

These fixes should help with a few failures seen on https://builds.apache.org/job/ActiveMQ6-Nightly-Regression-Test/27/#showFailuresLink.

A few test fixes

---

tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/cluster/bridge/BridgeStartTest.java

This is to address this failure: https://builds.apache.org/job/ActiveMQ6-Nightly-Regression-Test/29/testReport/junit/org.apache.activemq.tests.integration.cluster.bridge/BridgeStartTest/testTargetServerNotAvailableNoReconnectTries_isNetty_true_/.
I was able to reproduce the failure locally before the fix, but unable to reproduce the failure (even after several hundred runs) after the fix.

give receiver a bit more time on bridge test

---

activemq-core-client/src/main/java/org/apache/activemq/core/protocol/core/impl/BackwardsCompatibilityUtils.java
activemq-server/src/main/java/org/apache/activemq/core/protocol/core/impl/CoreProtocolManager.java

To support HornetQ clients we must pass back HornetQ connector factory
names. Currently the connector factory name returned as part of node up
broadcast group (after initial client connection and client sends suscribe
topology packet) is what ever the server is configured to use in its
cluster discovery.  Since the server has now been repackaged to
org.apache.activemq, the older HornetQ clients can not find the
connector factory class on it's class path.  To get around this problem
the server now checks the version of the client and if the client is
HornetQ the server renames the to org.hornetq and returns before sending
to the client.

Rename Connector class on NodeUp for HQ clients

---

activemq-protocols/activemq-amqp-protocol/src/main/java/org/apache/activemq/core/protocol/proton/plug/ProtonSessionIntegrationCallback.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/proton/ProtonTest.java

Implements a new feature for the broker whereby it may automatically
create and delete queues which are not explicitly defined through
the management API or file-based configuration when a client sends a
message to or receives from a queue via the AMQP protocol. Note,
the destination has to be named like "jms.queue.*" to be auto-
created. The queue may subsequently be deleted when it no longer has
any messages and consumers. Auto-creation and auto-deletion can both
be turned on/off via address-setting.

ACTIVEMQ-77 auto queue creation on AMQP send/rec

---

pom.xml

We should be using the Apache parent pom in our project.  This will give us a bunch of default apache configurations such as repositories, release set up and so on.  If we have any issues using the pom we should try to fix them rather than remove the parent.

Add apache parent to main pom.xml

---

activemq-rest/pom.xml

This is not required.  Builds fine and tests pass without this dep.

Remove servlet api dep from rest module

---

examples/jms/replicated-transaction-failover/src/main/java/org/apache/activemq/jms/example/ReplicatedTransactionFailoverExample.java
examples/jms/transaction-failover/src/main/java/org/apache/activemq/jms/example/TransactionFailoverExample.java

The TransactionFailoverExample IDs are not really unique if the journal is not cleaned up
This commit will make the IDs to use an UUID so the ID will always be unique even if you reuse the journal

Fixing TransactionFailoverExample

---

activemq-bootstrap/src/main/java/org/apache/activemq/cli/commands/Run.java
activemq-bootstrap/src/main/java/org/apache/activemq/cli/commands/Stop.java

ActiveMQ uses URI's for locating files on a file system.  Absolute file
URIs are generated using an ACTIVEMQ_HOME variable defined via the start
up scripts.  For Windows this will contain "\" character as file path
separator.  This is invalid for the file URI scheme.  This patch
rewrites the ACTIVEMQ_HOME variable ensuring "/" are used on both
Windows and Linux.
Tested on Windows 8 only.

Replace file separate in ACTIVEMQ_HOME for Windows

---

distribution/activemq/src/main/resources/README.html
examples/pom.xml

When running the examples from the distribution the example poms need to
find the top level activemq-pom.  For snapshot releases this will only
exist in the snapshot repo.

Add snapshot repo to examples pom.xml

---

activemq-maven-plugin/src/main/java/org/apache/activemq/server/ActiveMQBootstrap.java

The examples on windows are not working properly
This is because we are using concatenation to locate directories instead of File(parent, child)
Using that constructor we can then convert to URI and that would work independently of the OS

Fixing examples on windows

---

pom.xml

This should rename the source build to apache-activemq-6.0.0-source-release.zip.
It still need verification with the apache-release plugin.  We can add now and fix if we hit an issue on the next release.
Note:  This must be performed on a clean checkout, as it currently does not ignore idea files.  I will follow up post release with a better solution.

Add source build to release profile

---

distribution/activemq/pom.xml
distribution/activemq/src/main/assembly/source-assembly.xml
pom.xml

Builds the source assembly in the distribution build, and fixes previous issues of including unwanted files.  Still to do is the disabling of the source assembly on the top level pom as inherited by the Apache 16.

Add source assembly to distribution build

---

activemq-commons/src/main/java/org/apache/activemq/logs/ActiveMQUtilBundle.java
activemq-commons/src/main/java/org/apache/activemq/logs/ActiveMQUtilLogger.java
activemq-commons/src/main/java/org/apache/activemq/logs/AssertionLoggerHandler.java
activemq-commons/src/main/java/org/apache/activemq/utils/PasswordMaskingUtil.java
activemq-commons/src/main/java/org/apache/activemq/utils/TypedProperties.java
activemq-commons/src/main/java/org/apache/activemq/utils/UTF8Util.java
activemq-commons/src/main/java/org/apache/activemq/utils/UUIDGenerator.java
activemq-server/src/test/java/org/apache/activemq/core/config/impl/WrongRoleFileConfigurationParserTest.java
activemq-server/src/test/resources/logging.properties
tests/config/logging.properties
tests/config/logging.properties.trace
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/client/PagingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/server/AddressFullLoggingTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/server/FileLockTimeoutTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/server/SimpleStartStopTest.java

This was causing issues with javadoc
utils is also a package on activemq-server. ActiveMQUtilLogger is using a super class that was not part of the
source path on the javadoc plugin what caused it to exception and interrupt building

Moving ActiveMQLoggerHandler away from clashing package util

---

activemq-server/src/main/java/org/apache/activemq/core/persistence/impl/nullpm/NullStorageLargeServerMessage.java
activemq-server/src/test/java/org/apache/activemq/tests/util/UnitTestCase.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/jms/cluster/LargeMessageOverBridgeTest.java

https://issues.apache.org/jira/browse/ACTIVEMQ6-95
The message.copy is broken when you set persistence=false, and the bridge will use that method before forwarding the message
this commit is fixing NullStorageLargeServerMessage.copy and adding the proper testcase to validate the fix

ACTIVEMQ6-95 Large Message doesn't work on clustering & null Persistence

---

activemq-server/src/main/java/org/apache/activemq/core/config/FileDeploymentManager.java
activemq-server/src/test/java/org/apache/activemq/core/config/impl/FileConfigurationTest.java

Avoid loading problems of file configurations in
servlet containers when packaging the hornetq libs
not in the war file (e.g. in tomcat/lib/)
This was done with some refactoring from Clebert.
cherry-picking this from https://github.com/hornetq/hornetq/pull/1999

Use the context class loader in FileConfiguration

---

activemq-server/src/test/java/org/apache/activemq/tests/util/RemoveFolder.java
activemq-server/src/test/java/org/apache/activemq/tests/util/UnitTestCase.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/discovery/DiscoveryTest.java
tests/integration-tests/src/test/java/org/apache/activemq/tests/integration/jms/server/JMSServerStartStopTest.java
tests/integration-tests/src/test/resources/colocated-server-start-stop-config1.xml
tests/integration-tests/src/test/resources/colocated-server-start-stop-config2.xml
tests/integration-tests/src/test/resources/server-start-stop-config1.xml
tests/integration-tests/src/test/resources/test-jgroups-file_ping.xml

Sometimes /tmp doesn't support ext4 (most times is tmpfs under linux) and there's always a risk of leaving unnatended files in cases of crashed.
This is in alignment with how other tests run at apache.
Developers will be able to use tmpfs now

using temporary folders under ./target

---

pom.xml

#218 broke the build, needed a couple of fixes to the distribution module to account for the reduced offset.
#217 upgraded the main proton-j dependency to 0.9, but left the other at 0.8. There were some issues in 0.9 that we did a 0.9.1 to get fixes out for, so this upgrades both to that.

Upgrade to proton 0.9.1 and fix the build

---

artemis-distribution/pom.xml
pom.xml

A bug in version 2.2 was causing directory permissions in the assembly file to be ignored.

Bump Maven Assembly Plugin Version to 2.4

---

artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/FileConfigurationTest.java

The test wrongly assumes that Class.getResource(..) needs to specify the
System's line-separator. The contract for the method dictates:
"If the name begins with a '/' ('\u002f'), then the absolute name of
the resource is the portion of the name following the '/'."
Also, it manipulates File.getAbsolutePath() in a way that generates wrong
URL for Windows.

Fix FileConfigurationTest for Windows

---

artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/Topology.java
artemis-server/src/main/java/org/apache/activemq/artemis/core/server/cluster/impl/ClusterConnectionImpl.java

Topology serialization is already broken at this point, as its `topologyListeners` are not Serializable themselves.
Also, all the `executor` logic was simplified by making it `final`, defined at the constructor.

Make Topology non-serializable and also improve constructor
